# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pynamaz.ui'
#
# Created: Sat Jan  2 23:29:16 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(548, 573)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 521, 511))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 341, 261))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 30, 231, 211))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 6, 1, 1, 1)
        self.lcdNumberMaghribHour = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberMaghribHour.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberMaghribHour.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberMaghribHour.setLineWidth(1)
        self.lcdNumberMaghribHour.setSmallDecimalPoint(False)
        self.lcdNumberMaghribHour.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberMaghribHour.setObjectName(_fromUtf8("lcdNumberMaghribHour"))
        self.gridLayout_2.addWidget(self.lcdNumberMaghribHour, 5, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        self.lcdNumberFajrHour = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberFajrHour.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberFajrHour.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberFajrHour.setLineWidth(1)
        self.lcdNumberFajrHour.setSmallDecimalPoint(False)
        self.lcdNumberFajrHour.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberFajrHour.setObjectName(_fromUtf8("lcdNumberFajrHour"))
        self.gridLayout_2.addWidget(self.lcdNumberFajrHour, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 6, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.lcdNumberIshaHour = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberIshaHour.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberIshaHour.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberIshaHour.setLineWidth(1)
        self.lcdNumberIshaHour.setSmallDecimalPoint(False)
        self.lcdNumberIshaHour.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberIshaHour.setObjectName(_fromUtf8("lcdNumberIshaHour"))
        self.gridLayout_2.addWidget(self.lcdNumberIshaHour, 6, 2, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.lcdNumberAsrHour = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberAsrHour.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberAsrHour.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberAsrHour.setLineWidth(1)
        self.lcdNumberAsrHour.setSmallDecimalPoint(False)
        self.lcdNumberAsrHour.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberAsrHour.setObjectName(_fromUtf8("lcdNumberAsrHour"))
        self.gridLayout_2.addWidget(self.lcdNumberAsrHour, 4, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 1, 1, 1)
        self.lcdNumberDhuhrHour = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberDhuhrHour.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberDhuhrHour.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberDhuhrHour.setLineWidth(1)
        self.lcdNumberDhuhrHour.setSmallDecimalPoint(False)
        self.lcdNumberDhuhrHour.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberDhuhrHour.setObjectName(_fromUtf8("lcdNumberDhuhrHour"))
        self.gridLayout_2.addWidget(self.lcdNumberDhuhrHour, 3, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 2, 1, 1, 1)
        self.lcdNumberSunriseHour = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberSunriseHour.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberSunriseHour.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberSunriseHour.setLineWidth(1)
        self.lcdNumberSunriseHour.setSmallDecimalPoint(False)
        self.lcdNumberSunriseHour.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberSunriseHour.setObjectName(_fromUtf8("lcdNumberSunriseHour"))
        self.gridLayout_2.addWidget(self.lcdNumberSunriseHour, 2, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        self.lcdNumberIshaMinute = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberIshaMinute.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberIshaMinute.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberIshaMinute.setLineWidth(1)
        self.lcdNumberIshaMinute.setSmallDecimalPoint(False)
        self.lcdNumberIshaMinute.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberIshaMinute.setObjectName(_fromUtf8("lcdNumberIshaMinute"))
        self.gridLayout_2.addWidget(self.lcdNumberIshaMinute, 6, 3, 1, 1)
        self.lcdNumberMaghribMinute = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberMaghribMinute.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberMaghribMinute.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberMaghribMinute.setLineWidth(1)
        self.lcdNumberMaghribMinute.setSmallDecimalPoint(False)
        self.lcdNumberMaghribMinute.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberMaghribMinute.setObjectName(_fromUtf8("lcdNumberMaghribMinute"))
        self.gridLayout_2.addWidget(self.lcdNumberMaghribMinute, 5, 3, 1, 1)
        self.lcdNumberAsrMinute = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberAsrMinute.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberAsrMinute.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberAsrMinute.setLineWidth(1)
        self.lcdNumberAsrMinute.setSmallDecimalPoint(False)
        self.lcdNumberAsrMinute.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberAsrMinute.setObjectName(_fromUtf8("lcdNumberAsrMinute"))
        self.gridLayout_2.addWidget(self.lcdNumberAsrMinute, 4, 3, 1, 1)
        self.lcdNumberDhuhrMinute = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberDhuhrMinute.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberDhuhrMinute.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberDhuhrMinute.setLineWidth(1)
        self.lcdNumberDhuhrMinute.setSmallDecimalPoint(False)
        self.lcdNumberDhuhrMinute.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberDhuhrMinute.setObjectName(_fromUtf8("lcdNumberDhuhrMinute"))
        self.gridLayout_2.addWidget(self.lcdNumberDhuhrMinute, 3, 3, 1, 1)
        self.lcdNumberSunriseMinute = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberSunriseMinute.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberSunriseMinute.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberSunriseMinute.setLineWidth(1)
        self.lcdNumberSunriseMinute.setSmallDecimalPoint(False)
        self.lcdNumberSunriseMinute.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberSunriseMinute.setObjectName(_fromUtf8("lcdNumberSunriseMinute"))
        self.gridLayout_2.addWidget(self.lcdNumberSunriseMinute, 2, 3, 1, 1)
        self.lcdNumberFajrMinute = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberFajrMinute.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberFajrMinute.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberFajrMinute.setLineWidth(1)
        self.lcdNumberFajrMinute.setSmallDecimalPoint(False)
        self.lcdNumberFajrMinute.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberFajrMinute.setObjectName(_fromUtf8("lcdNumberFajrMinute"))
        self.gridLayout_2.addWidget(self.lcdNumberFajrMinute, 1, 3, 1, 1)
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(30, 20, 421, 61))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.labelCurrentDate = QtGui.QLabel(self.gridLayoutWidget_7)
        self.labelCurrentDate.setObjectName(_fromUtf8("labelCurrentDate"))
        self.gridLayout_8.addWidget(self.labelCurrentDate, 1, 0, 1, 1)
        self.lcdNumberCurrentMinute = QtGui.QLCDNumber(self.gridLayoutWidget_7)
        self.lcdNumberCurrentMinute.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberCurrentMinute.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberCurrentMinute.setLineWidth(1)
        self.lcdNumberCurrentMinute.setSmallDecimalPoint(False)
        self.lcdNumberCurrentMinute.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberCurrentMinute.setObjectName(_fromUtf8("lcdNumberCurrentMinute"))
        self.gridLayout_8.addWidget(self.lcdNumberCurrentMinute, 1, 2, 1, 1)
        self.lcdNumberCurrentHour = QtGui.QLCDNumber(self.gridLayoutWidget_7)
        self.lcdNumberCurrentHour.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberCurrentHour.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberCurrentHour.setLineWidth(1)
        self.lcdNumberCurrentHour.setSmallDecimalPoint(False)
        self.lcdNumberCurrentHour.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberCurrentHour.setObjectName(_fromUtf8("lcdNumberCurrentHour"))
        self.gridLayout_8.addWidget(self.lcdNumberCurrentHour, 1, 1, 1, 1)
        self.lcdNumberCurrentSecond = QtGui.QLCDNumber(self.gridLayoutWidget_7)
        self.lcdNumberCurrentSecond.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberCurrentSecond.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberCurrentSecond.setLineWidth(1)
        self.lcdNumberCurrentSecond.setSmallDecimalPoint(False)
        self.lcdNumberCurrentSecond.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberCurrentSecond.setObjectName(_fromUtf8("lcdNumberCurrentSecond"))
        self.gridLayout_8.addWidget(self.lcdNumberCurrentSecond, 1, 3, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 380, 377, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelNextPrayer = QtGui.QLabel(self.horizontalLayoutWidget)
        self.labelNextPrayer.setObjectName(_fromUtf8("labelNextPrayer"))
        self.horizontalLayout.addWidget(self.labelNextPrayer)
        self.lcdNumberNextPrayerHour = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumberNextPrayerHour.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberNextPrayerHour.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberNextPrayerHour.setLineWidth(1)
        self.lcdNumberNextPrayerHour.setSmallDecimalPoint(False)
        self.lcdNumberNextPrayerHour.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberNextPrayerHour.setObjectName(_fromUtf8("lcdNumberNextPrayerHour"))
        self.horizontalLayout.addWidget(self.lcdNumberNextPrayerHour)
        self.lcdNumberNextPrayerMinute = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumberNextPrayerMinute.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumberNextPrayerMinute.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumberNextPrayerMinute.setLineWidth(1)
        self.lcdNumberNextPrayerMinute.setSmallDecimalPoint(False)
        self.lcdNumberNextPrayerMinute.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberNextPrayerMinute.setObjectName(_fromUtf8("lcdNumberNextPrayerMinute"))
        self.horizontalLayout.addWidget(self.lcdNumberNextPrayerMinute)
        self.lcdNumberNextPrayerSecond = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumberNextPrayerSecond.setObjectName(_fromUtf8("lcdNumberNextPrayerSecond"))
        self.horizontalLayout.addWidget(self.lcdNumberNextPrayerSecond)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 360, 411, 111))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.tab_6)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(51, 90, 353, 131))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_5.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_5.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMen = QtGui.QMenu(self.menubar)
        self.menuMen.setObjectName(_fromUtf8("menuMen"))
        self.menuG_r_n_m = QtGui.QMenu(self.menuMen)
        self.menuG_r_n_m.setObjectName(_fromUtf8("menuG_r_n_m"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_k = QtGui.QAction(MainWindow)
        self.action_k.setObjectName(_fromUtf8("action_k"))
        self.actionCleanlooks = QtGui.QAction(MainWindow)
        self.actionCleanlooks.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionCleanlooks.setObjectName(_fromUtf8("actionCleanlooks"))
        self.actionGTK = QtGui.QAction(MainWindow)
        self.actionGTK.setObjectName(_fromUtf8("actionGTK"))
        self.actionPlastique = QtGui.QAction(MainWindow)
        self.actionPlastique.setObjectName(_fromUtf8("actionPlastique"))
        self.actionWindows = QtGui.QAction(MainWindow)
        self.actionWindows.setObjectName(_fromUtf8("actionWindows"))
        self.actionG_ncelle_2 = QtGui.QAction(MainWindow)
        self.actionG_ncelle_2.setObjectName(_fromUtf8("actionG_ncelle_2"))
        self.actionBespin = QtGui.QAction(MainWindow)
        self.actionBespin.setObjectName(_fromUtf8("actionBespin"))
        self.actionQtcurve = QtGui.QAction(MainWindow)
        self.actionQtcurve.setObjectName(_fromUtf8("actionQtcurve"))
        self.actionMotif = QtGui.QAction(MainWindow)
        self.actionMotif.setObjectName(_fromUtf8("actionMotif"))
        self.actionCDE = QtGui.QAction(MainWindow)
        self.actionCDE.setObjectName(_fromUtf8("actionCDE"))
        self.actionOxygen = QtGui.QAction(MainWindow)
        self.actionOxygen.setObjectName(_fromUtf8("actionOxygen"))
        self.menuG_r_n_m.addAction(self.actionBespin)
        self.menuG_r_n_m.addAction(self.actionCleanlooks)
        self.menuG_r_n_m.addAction(self.actionGTK)
        self.menuG_r_n_m.addAction(self.actionPlastique)
        self.menuG_r_n_m.addAction(self.actionWindows)
        self.menuG_r_n_m.addAction(self.actionQtcurve)
        self.menuG_r_n_m.addAction(self.actionMotif)
        self.menuG_r_n_m.addAction(self.actionCDE)
        self.menuG_r_n_m.addAction(self.actionOxygen)
        self.menuMen.addAction(self.menuG_r_n_m.menuAction())
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "VAKİTLER", None))
        self.label_5.setText(_translate("MainWindow", "YATSI", None))
        self.label_4.setText(_translate("MainWindow", "AKŞAM", None))
        self.label_2.setText(_translate("MainWindow", "ÖĞLE", None))
        self.label.setText(_translate("MainWindow", "İMSAK", None))
        self.label_3.setText(_translate("MainWindow", "İKİNDİ", None))
        self.label_24.setText(_translate("MainWindow", "GÜNEŞ", None))
        self.labelCurrentDate.setText(_translate("MainWindow", "::tarih::", None))
        self.labelNextPrayer.setText(_translate("MainWindow", "SONRAKİ VAKTE KALAN SÜRE", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Kalan süre", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Anasayfa", None))
        self.pushButton_2.setText(_translate("MainWindow", "mustafairan.wordpress.com", None))
        self.pushButton.setText(_translate("MainWindow", "www.diyanet.gov.tr", None))
        self.pushButton_3.setText(_translate("MainWindow", "github.com/mustafairan/pynamaz", None))
        self.label_14.setText(_translate("MainWindow", "Diyanet.gov.tr", None))
        self.label_15.setText(_translate("MainWindow", "Geliştirici Sayfası", None))
        self.label_17.setText(_translate("MainWindow", "Uygulama Deposu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Linkler", None))
        self.menuMen.setTitle(_translate("MainWindow", "Menü", None))
        self.menuG_r_n_m.setTitle(_translate("MainWindow", "Görünüm", None))
        self.action_k.setText(_translate("MainWindow", "Çıkış", None))
        self.actionCleanlooks.setText(_translate("MainWindow", "Cleanlooks", None))
        self.actionGTK.setText(_translate("MainWindow", "GTK+", None))
        self.actionPlastique.setText(_translate("MainWindow", "Plastique", None))
        self.actionWindows.setText(_translate("MainWindow", "Windows", None))
        self.actionG_ncelle_2.setText(_translate("MainWindow", "Güncelle", None))
        self.actionBespin.setText(_translate("MainWindow", "Bespin", None))
        self.actionQtcurve.setText(_translate("MainWindow", "Qtcurve", None))
        self.actionMotif.setText(_translate("MainWindow", "Motif", None))
        self.actionCDE.setText(_translate("MainWindow", "CDE", None))
        self.actionOxygen.setText(_translate("MainWindow", "Oxygen", None))

