# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pynamaz.ui'
#
# Created: Tue Dec 15 15:22:38 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(548, 573)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 521, 511))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.AnalogClock = QwtAnalogClock(self.tab)
        self.AnalogClock.setEnabled(True)
        self.AnalogClock.setGeometry(QtCore.QRect(360, 10, 131, 121))
        self.AnalogClock.setReadOnly(False)
        self.AnalogClock.setValid(True)
        self.AnalogClock.setOrientation(QtCore.Qt.Horizontal)
        self.AnalogClock.setLineWidth(7)
        self.AnalogClock.setFrameShadow(QwtDial.Sunken)
        self.AnalogClock.setMode(QwtDial.RotateNeedle)
        self.AnalogClock.setObjectName(_fromUtf8("AnalogClock"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 370, 391, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 26, 178, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_6.setGeometry(QtCore.QRect(210, 26, 161, 41))
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 341, 261))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 30, 231, 211))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 1, 1, 1)
        self.lcdNumber = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber.setLineWidth(1)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout_2.addWidget(self.lcdNumber, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_2.setLineWidth(1)
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.gridLayout_2.addWidget(self.lcdNumber_2, 1, 2, 1, 1)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_3.setLineWidth(1)
        self.lcdNumber_3.setSmallDecimalPoint(False)
        self.lcdNumber_3.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.gridLayout_2.addWidget(self.lcdNumber_3, 1, 3, 1, 1)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_4.setLineWidth(1)
        self.lcdNumber_4.setSmallDecimalPoint(False)
        self.lcdNumber_4.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.gridLayout_2.addWidget(self.lcdNumber_4, 0, 3, 1, 1)
        self.lcdNumber_5 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_5.setLineWidth(1)
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.gridLayout_2.addWidget(self.lcdNumber_5, 2, 3, 1, 1)
        self.lcdNumber_7 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_7.setLineWidth(1)
        self.lcdNumber_7.setSmallDecimalPoint(False)
        self.lcdNumber_7.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.gridLayout_2.addWidget(self.lcdNumber_7, 2, 2, 1, 1)
        self.lcdNumber_8 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_8.setLineWidth(1)
        self.lcdNumber_8.setSmallDecimalPoint(False)
        self.lcdNumber_8.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_8.setObjectName(_fromUtf8("lcdNumber_8"))
        self.gridLayout_2.addWidget(self.lcdNumber_8, 3, 2, 1, 1)
        self.lcdNumber_9 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_9.setLineWidth(1)
        self.lcdNumber_9.setSmallDecimalPoint(False)
        self.lcdNumber_9.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_9.setObjectName(_fromUtf8("lcdNumber_9"))
        self.gridLayout_2.addWidget(self.lcdNumber_9, 3, 3, 1, 1)
        self.lcdNumber_10 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_10.setLineWidth(1)
        self.lcdNumber_10.setSmallDecimalPoint(False)
        self.lcdNumber_10.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_10.setObjectName(_fromUtf8("lcdNumber_10"))
        self.gridLayout_2.addWidget(self.lcdNumber_10, 4, 2, 1, 1)
        self.lcdNumber_11 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_11.setLineWidth(1)
        self.lcdNumber_11.setSmallDecimalPoint(False)
        self.lcdNumber_11.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_11.setObjectName(_fromUtf8("lcdNumber_11"))
        self.gridLayout_2.addWidget(self.lcdNumber_11, 4, 3, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.tab)
        self.checkBox_13.setGeometry(QtCore.QRect(390, 470, 86, 21))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(30, 20, 231, 61))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 0, 451, 261))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 411, 211))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout_3.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.gridLayout_3.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.buttonBox_2 = QtGui.QDialogButtonBox(self.tab_2)
        self.buttonBox_2.setGeometry(QtCore.QRect(160, 400, 160, 25))
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 451, 301))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox_4 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_4.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_4.addWidget(self.checkBox, 3, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.gridLayoutWidget_4)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 6, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_4.addWidget(self.checkBox_2, 4, 0, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout_4.addWidget(self.checkBox_11, 1, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_4.addWidget(self.spinBox, 2, 1, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout_4.addWidget(self.checkBox_12, 2, 0, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_4.addWidget(self.spinBox_6, 4, 1, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_4.addWidget(self.spinBox_7, 3, 1, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_4.addWidget(self.spinBox_5, 0, 1, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_4.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 471, 271))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 483, 281))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.buttonBox_4 = QtGui.QDialogButtonBox(self.gridLayoutWidget_5)
        self.buttonBox_4.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_4.setObjectName(_fromUtf8("buttonBox_4"))
        self.gridLayout_6.addWidget(self.buttonBox_4, 11, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 7, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_6.addWidget(self.label_27, 8, 1, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout_6.addWidget(self.checkBox_20, 5, 0, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridLayout_6.addWidget(self.checkBox_18, 4, 0, 1, 1)
        self.checkBox_21 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.gridLayout_6.addWidget(self.checkBox_21, 6, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 8, 0, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridLayout_6.addWidget(self.checkBox_14, 3, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 9, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.gridLayout_6.addWidget(self.comboBox_5, 9, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(40, 40, 231, 261))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 4, 0, 1, 1)
        self.spinBox_10 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.gridLayout_7.addWidget(self.spinBox_10, 0, 1, 1, 1)
        self.spinBox_11 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.gridLayout_7.addWidget(self.spinBox_11, 1, 1, 1, 1)
        self.spinBox_12 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.gridLayout_7.addWidget(self.spinBox_12, 2, 1, 1, 1)
        self.spinBox_13 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.gridLayout_7.addWidget(self.spinBox_13, 3, 1, 1, 1)
        self.spinBox_14 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.gridLayout_7.addWidget(self.spinBox_14, 4, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 0, 311, 311))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.tab_6)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(40, 50, 371, 168))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.commandLinkButton = QtGui.QCommandLinkButton(self.gridLayoutWidget_8)
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.gridLayout_5.addWidget(self.commandLinkButton, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 1, 0, 1, 1)
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.gridLayoutWidget_8)
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.gridLayout_5.addWidget(self.commandLinkButton_2, 1, 1, 1, 1)
        self.commandLinkButton_3 = QtGui.QCommandLinkButton(self.gridLayoutWidget_8)
        self.commandLinkButton_3.setObjectName(_fromUtf8("commandLinkButton_3"))
        self.gridLayout_5.addWidget(self.commandLinkButton_3, 2, 1, 1, 1)
        self.commandLinkButton_4 = QtGui.QCommandLinkButton(self.gridLayoutWidget_8)
        self.commandLinkButton_4.setObjectName(_fromUtf8("commandLinkButton_4"))
        self.gridLayout_5.addWidget(self.commandLinkButton_4, 4, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 461, 411))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMen = QtGui.QMenu(self.menubar)
        self.menuMen.setObjectName(_fromUtf8("menuMen"))
        self.menuG_r_n_m = QtGui.QMenu(self.menuMen)
        self.menuG_r_n_m.setObjectName(_fromUtf8("menuG_r_n_m"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_k = QtGui.QAction(MainWindow)
        self.action_k.setObjectName(_fromUtf8("action_k"))
        self.actionGizle = QtGui.QAction(MainWindow)
        self.actionGizle.setObjectName(_fromUtf8("actionGizle"))
        self.actionCleanlooks = QtGui.QAction(MainWindow)
        self.actionCleanlooks.setObjectName(_fromUtf8("actionCleanlooks"))
        self.actionGTK_stili = QtGui.QAction(MainWindow)
        self.actionGTK_stili.setObjectName(_fromUtf8("actionGTK_stili"))
        self.actionPlastique = QtGui.QAction(MainWindow)
        self.actionPlastique.setObjectName(_fromUtf8("actionPlastique"))
        self.actionWindows = QtGui.QAction(MainWindow)
        self.actionWindows.setObjectName(_fromUtf8("actionWindows"))
        self.actionG_ncelle_2 = QtGui.QAction(MainWindow)
        self.actionG_ncelle_2.setObjectName(_fromUtf8("actionG_ncelle_2"))
        self.menuG_r_n_m.addAction(self.actionCleanlooks)
        self.menuG_r_n_m.addAction(self.actionGTK_stili)
        self.menuG_r_n_m.addAction(self.actionPlastique)
        self.menuG_r_n_m.addAction(self.actionWindows)
        self.menuMen.addAction(self.actionGizle)
        self.menuMen.addAction(self.menuG_r_n_m.menuAction())
        self.menuMen.addAction(self.actionG_ncelle_2)
        self.menuMen.addAction(self.action_k)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_6.setText(_translate("MainWindow", "SONRAKİ VAKTE KALAN SÜRE", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "VAKİTLER", None))
        self.label_3.setText(_translate("MainWindow", "İKİNDİ", None))
        self.label.setText(_translate("MainWindow", "İMSAK", None))
        self.label_2.setText(_translate("MainWindow", "ÖĞLE", None))
        self.label_4.setText(_translate("MainWindow", "AKŞAM", None))
        self.label_5.setText(_translate("MainWindow", "YATSI", None))
        self.checkBox_13.setText(_translate("MainWindow", "sessiz", None))
        self.label_23.setText(_translate("MainWindow", "::tarih::", None))
        self.label_11.setText(_translate("MainWindow", "Ankara", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Anasayfa", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_9.setText(_translate("MainWindow", "ÜLKE", None))
        self.label_8.setText(_translate("MainWindow", "ŞEHİR", None))
        self.label_7.setText(_translate("MainWindow", "İLÇE", None))
        self.label_10.setText(_translate("MainWindow", "KÖY/KASABA", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Bölge", None))
        self.checkBox_4.setText(_translate("MainWindow", "İmsak", None))
        self.checkBox.setText(_translate("MainWindow", "Akşam", None))
        self.checkBox_2.setText(_translate("MainWindow", "Yatsı", None))
        self.checkBox_11.setText(_translate("MainWindow", "Öğle", None))
        self.checkBox_12.setText(_translate("MainWindow", "İkindi", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Vakit Uyarıları", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Uyarılar", None))
        self.label_13.setText(_translate("MainWindow", "yol aracı", None))
        self.label_27.setText(_translate("MainWindow", "yol aracı", None))
        self.checkBox_20.setText(_translate("MainWindow", "Uyarı sesleri çal", None))
        self.checkBox_18.setText(_translate("MainWindow", "Vakitlerde ezan oku", None))
        self.checkBox_21.setText(_translate("MainWindow", "Ezan vaktinde sesi kapat", None))
        self.label_12.setText(_translate("MainWindow", "ezan sesi", None))
        self.label_26.setText(_translate("MainWindow", "uyarı sesi", None))
        self.checkBox_14.setText(_translate("MainWindow", "Sistem tepsisinde simge göster", None))
        self.label_16.setText(_translate("MainWindow", "kapatma ayarı", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Seçenekler", None))
        self.label_22.setText(_translate("MainWindow", "Sabah", None))
        self.label_19.setText(_translate("MainWindow", "Akşam", None))
        self.label_21.setText(_translate("MainWindow", "Öğle", None))
        self.label_20.setText(_translate("MainWindow", "İkindi", None))
        self.label_18.setText(_translate("MainWindow", "Yatsı", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Kazalar", None))
        self.commandLinkButton.setText(_translate("MainWindow", ":::link aç::", None))
        self.label_15.setText(_translate("MainWindow", "TextLabel", None))
        self.label_24.setText(_translate("MainWindow", "yazar", None))
        self.commandLinkButton_2.setText(_translate("MainWindow", "CommandLinkButton", None))
        self.commandLinkButton_3.setText(_translate("MainWindow", "CommandLinkButton", None))
        self.commandLinkButton_4.setText(_translate("MainWindow", "CommandLinkButton", None))
        self.label_25.setText(_translate("MainWindow", "risale", None))
        self.label_14.setText(_translate("MainWindow", "Diyanet", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Linkler", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Linkler", None))
        self.menuMen.setTitle(_translate("MainWindow", "Menü", None))
        self.menuG_r_n_m.setTitle(_translate("MainWindow", "Görünüm", None))
        self.action_k.setText(_translate("MainWindow", "Çıkış", None))
        self.actionGizle.setText(_translate("MainWindow", "Gizle", None))
        self.actionCleanlooks.setText(_translate("MainWindow", "Cleanlooks", None))
        self.actionGTK_stili.setText(_translate("MainWindow", "GTK+", None))
        self.actionPlastique.setText(_translate("MainWindow", "Plastique", None))
        self.actionWindows.setText(_translate("MainWindow", "Windows", None))
        self.actionG_ncelle_2.setText(_translate("MainWindow", "Güncelle", None))

from qwt_dial import QwtDial
from qwt_analog_clock import QwtAnalogClock
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pynamaz.ui'
#
# Created: Tue Dec 15 15:24:51 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(548, 573)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 521, 511))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.AnalogClock = QwtAnalogClock(self.tab)
        self.AnalogClock.setEnabled(True)
        self.AnalogClock.setGeometry(QtCore.QRect(360, 10, 131, 121))
        self.AnalogClock.setReadOnly(False)
        self.AnalogClock.setValid(True)
        self.AnalogClock.setOrientation(QtCore.Qt.Horizontal)
        self.AnalogClock.setLineWidth(7)
        self.AnalogClock.setFrameShadow(QwtDial.Sunken)
        self.AnalogClock.setMode(QwtDial.RotateNeedle)
        self.AnalogClock.setObjectName(_fromUtf8("AnalogClock"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 370, 391, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 26, 178, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_6.setGeometry(QtCore.QRect(210, 26, 161, 41))
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 341, 261))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 30, 231, 211))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 1, 1, 1)
        self.lcdNumber = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber.setLineWidth(1)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout_2.addWidget(self.lcdNumber, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_2.setLineWidth(1)
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.gridLayout_2.addWidget(self.lcdNumber_2, 1, 2, 1, 1)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_3.setLineWidth(1)
        self.lcdNumber_3.setSmallDecimalPoint(False)
        self.lcdNumber_3.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.gridLayout_2.addWidget(self.lcdNumber_3, 1, 3, 1, 1)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_4.setLineWidth(1)
        self.lcdNumber_4.setSmallDecimalPoint(False)
        self.lcdNumber_4.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.gridLayout_2.addWidget(self.lcdNumber_4, 0, 3, 1, 1)
        self.lcdNumber_5 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_5.setLineWidth(1)
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.gridLayout_2.addWidget(self.lcdNumber_5, 2, 3, 1, 1)
        self.lcdNumber_7 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_7.setLineWidth(1)
        self.lcdNumber_7.setSmallDecimalPoint(False)
        self.lcdNumber_7.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.gridLayout_2.addWidget(self.lcdNumber_7, 2, 2, 1, 1)
        self.lcdNumber_8 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_8.setLineWidth(1)
        self.lcdNumber_8.setSmallDecimalPoint(False)
        self.lcdNumber_8.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_8.setObjectName(_fromUtf8("lcdNumber_8"))
        self.gridLayout_2.addWidget(self.lcdNumber_8, 3, 2, 1, 1)
        self.lcdNumber_9 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_9.setLineWidth(1)
        self.lcdNumber_9.setSmallDecimalPoint(False)
        self.lcdNumber_9.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_9.setObjectName(_fromUtf8("lcdNumber_9"))
        self.gridLayout_2.addWidget(self.lcdNumber_9, 3, 3, 1, 1)
        self.lcdNumber_10 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_10.setLineWidth(1)
        self.lcdNumber_10.setSmallDecimalPoint(False)
        self.lcdNumber_10.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_10.setObjectName(_fromUtf8("lcdNumber_10"))
        self.gridLayout_2.addWidget(self.lcdNumber_10, 4, 2, 1, 1)
        self.lcdNumber_11 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_11.setLineWidth(1)
        self.lcdNumber_11.setSmallDecimalPoint(False)
        self.lcdNumber_11.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_11.setObjectName(_fromUtf8("lcdNumber_11"))
        self.gridLayout_2.addWidget(self.lcdNumber_11, 4, 3, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.tab)
        self.checkBox_13.setGeometry(QtCore.QRect(390, 470, 86, 21))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(30, 20, 231, 61))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 0, 451, 261))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 411, 211))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout_3.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.gridLayout_3.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.buttonBox_2 = QtGui.QDialogButtonBox(self.tab_2)
        self.buttonBox_2.setGeometry(QtCore.QRect(160, 400, 160, 25))
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 451, 301))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox_4 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_4.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_4.addWidget(self.checkBox, 3, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.gridLayoutWidget_4)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 6, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_4.addWidget(self.checkBox_2, 4, 0, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout_4.addWidget(self.checkBox_11, 1, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_4.addWidget(self.spinBox, 2, 1, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout_4.addWidget(self.checkBox_12, 2, 0, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_4.addWidget(self.spinBox_6, 4, 1, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_4.addWidget(self.spinBox_7, 3, 1, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_4.addWidget(self.spinBox_5, 0, 1, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_4.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 471, 271))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 483, 281))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.buttonBox_4 = QtGui.QDialogButtonBox(self.gridLayoutWidget_5)
        self.buttonBox_4.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_4.setObjectName(_fromUtf8("buttonBox_4"))
        self.gridLayout_6.addWidget(self.buttonBox_4, 11, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 7, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_6.addWidget(self.label_27, 8, 1, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout_6.addWidget(self.checkBox_20, 5, 0, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridLayout_6.addWidget(self.checkBox_18, 4, 0, 1, 1)
        self.checkBox_21 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.gridLayout_6.addWidget(self.checkBox_21, 6, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 8, 0, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridLayout_6.addWidget(self.checkBox_14, 3, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 9, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.gridLayout_6.addWidget(self.comboBox_5, 9, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(40, 40, 231, 261))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 4, 0, 1, 1)
        self.spinBox_10 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.gridLayout_7.addWidget(self.spinBox_10, 0, 1, 1, 1)
        self.spinBox_11 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.gridLayout_7.addWidget(self.spinBox_11, 1, 1, 1, 1)
        self.spinBox_12 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.gridLayout_7.addWidget(self.spinBox_12, 2, 1, 1, 1)
        self.spinBox_13 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.gridLayout_7.addWidget(self.spinBox_13, 3, 1, 1, 1)
        self.spinBox_14 = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.gridLayout_7.addWidget(self.spinBox_14, 4, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 0, 311, 311))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.tab_6)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(40, 50, 371, 168))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.commandLinkButton = QtGui.QCommandLinkButton(self.gridLayoutWidget_8)
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.gridLayout_5.addWidget(self.commandLinkButton, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 1, 0, 1, 1)
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.gridLayoutWidget_8)
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.gridLayout_5.addWidget(self.commandLinkButton_2, 1, 1, 1, 1)
        self.commandLinkButton_3 = QtGui.QCommandLinkButton(self.gridLayoutWidget_8)
        self.commandLinkButton_3.setObjectName(_fromUtf8("commandLinkButton_3"))
        self.gridLayout_5.addWidget(self.commandLinkButton_3, 2, 1, 1, 1)
        self.commandLinkButton_4 = QtGui.QCommandLinkButton(self.gridLayoutWidget_8)
        self.commandLinkButton_4.setObjectName(_fromUtf8("commandLinkButton_4"))
        self.gridLayout_5.addWidget(self.commandLinkButton_4, 4, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 461, 411))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMen = QtGui.QMenu(self.menubar)
        self.menuMen.setObjectName(_fromUtf8("menuMen"))
        self.menuG_r_n_m = QtGui.QMenu(self.menuMen)
        self.menuG_r_n_m.setObjectName(_fromUtf8("menuG_r_n_m"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_k = QtGui.QAction(MainWindow)
        self.action_k.setObjectName(_fromUtf8("action_k"))
        self.actionGizle = QtGui.QAction(MainWindow)
        self.actionGizle.setObjectName(_fromUtf8("actionGizle"))
        self.actionCleanlooks = QtGui.QAction(MainWindow)
        self.actionCleanlooks.setObjectName(_fromUtf8("actionCleanlooks"))
        self.actionGTK_stili = QtGui.QAction(MainWindow)
        self.actionGTK_stili.setObjectName(_fromUtf8("actionGTK_stili"))
        self.actionPlastique = QtGui.QAction(MainWindow)
        self.actionPlastique.setObjectName(_fromUtf8("actionPlastique"))
        self.actionWindows = QtGui.QAction(MainWindow)
        self.actionWindows.setObjectName(_fromUtf8("actionWindows"))
        self.actionG_ncelle_2 = QtGui.QAction(MainWindow)
        self.actionG_ncelle_2.setObjectName(_fromUtf8("actionG_ncelle_2"))
        self.menuG_r_n_m.addAction(self.actionCleanlooks)
        self.menuG_r_n_m.addAction(self.actionGTK_stili)
        self.menuG_r_n_m.addAction(self.actionPlastique)
        self.menuG_r_n_m.addAction(self.actionWindows)
        self.menuMen.addAction(self.actionGizle)
        self.menuMen.addAction(self.menuG_r_n_m.menuAction())
        self.menuMen.addAction(self.actionG_ncelle_2)
        self.menuMen.addAction(self.action_k)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_6.setText(_translate("MainWindow", "SONRAKİ VAKTE KALAN SÜRE", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "VAKİTLER", None))
        self.label_3.setText(_translate("MainWindow", "İKİNDİ", None))
        self.label.setText(_translate("MainWindow", "İMSAK", None))
        self.label_2.setText(_translate("MainWindow", "ÖĞLE", None))
        self.label_4.setText(_translate("MainWindow", "AKŞAM", None))
        self.label_5.setText(_translate("MainWindow", "YATSI", None))
        self.checkBox_13.setText(_translate("MainWindow", "sessiz", None))
        self.label_23.setText(_translate("MainWindow", "::tarih::", None))
        self.label_11.setText(_translate("MainWindow", "Ankara", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Anasayfa", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_9.setText(_translate("MainWindow", "ÜLKE", None))
        self.label_8.setText(_translate("MainWindow", "ŞEHİR", None))
        self.label_7.setText(_translate("MainWindow", "İLÇE", None))
        self.label_10.setText(_translate("MainWindow", "KÖY/KASABA", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Bölge", None))
        self.checkBox_4.setText(_translate("MainWindow", "İmsak", None))
        self.checkBox.setText(_translate("MainWindow", "Akşam", None))
        self.checkBox_2.setText(_translate("MainWindow", "Yatsı", None))
        self.checkBox_11.setText(_translate("MainWindow", "Öğle", None))
        self.checkBox_12.setText(_translate("MainWindow", "İkindi", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Vakit Uyarıları", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Uyarılar", None))
        self.label_13.setText(_translate("MainWindow", "yol aracı", None))
        self.label_27.setText(_translate("MainWindow", "yol aracı", None))
        self.checkBox_20.setText(_translate("MainWindow", "Uyarı sesleri çal", None))
        self.checkBox_18.setText(_translate("MainWindow", "Vakitlerde ezan oku", None))
        self.checkBox_21.setText(_translate("MainWindow", "Ezan vaktinde sesi kapat", None))
        self.label_12.setText(_translate("MainWindow", "ezan sesi", None))
        self.label_26.setText(_translate("MainWindow", "uyarı sesi", None))
        self.checkBox_14.setText(_translate("MainWindow", "Sistem tepsisinde simge göster", None))
        self.label_16.setText(_translate("MainWindow", "kapatma ayarı", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Seçenekler", None))
        self.label_22.setText(_translate("MainWindow", "Sabah", None))
        self.label_19.setText(_translate("MainWindow", "Akşam", None))
        self.label_21.setText(_translate("MainWindow", "Öğle", None))
        self.label_20.setText(_translate("MainWindow", "İkindi", None))
        self.label_18.setText(_translate("MainWindow", "Yatsı", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Kazalar", None))
        self.commandLinkButton.setText(_translate("MainWindow", ":::link aç::", None))
        self.label_15.setText(_translate("MainWindow", "TextLabel", None))
        self.label_24.setText(_translate("MainWindow", "yazar", None))
        self.commandLinkButton_2.setText(_translate("MainWindow", "CommandLinkButton", None))
        self.commandLinkButton_3.setText(_translate("MainWindow", "CommandLinkButton", None))
        self.commandLinkButton_4.setText(_translate("MainWindow", "CommandLinkButton", None))
        self.label_25.setText(_translate("MainWindow", "risale", None))
        self.label_14.setText(_translate("MainWindow", "Diyanet", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Linkler", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Linkler", None))
        self.menuMen.setTitle(_translate("MainWindow", "Menü", None))
        self.menuG_r_n_m.setTitle(_translate("MainWindow", "Görünüm", None))
        self.action_k.setText(_translate("MainWindow", "Çıkış", None))
        self.actionGizle.setText(_translate("MainWindow", "Gizle", None))
        self.actionCleanlooks.setText(_translate("MainWindow", "Cleanlooks", None))
        self.actionGTK_stili.setText(_translate("MainWindow", "GTK+", None))
        self.actionPlastique.setText(_translate("MainWindow", "Plastique", None))
        self.actionWindows.setText(_translate("MainWindow", "Windows", None))
        self.actionG_ncelle_2.setText(_translate("MainWindow", "Güncelle", None))

from qwt_dial import QwtDial
from qwt_analog_clock import QwtAnalogClock
