# -*- coding: utf-8 -*-

class UlkelerSehirler:    
    ulkeler = ['ABD', 'AFGANISTAN', 'ALMANYA', 'ANDORRA', 'ANGOLA', 'ANGUILLA', 'ANTIGUA VE BARBUDA', 'ARJANTIN', 'ARNAVUTLUK', 'ARUBA', 'AVUSTRALYA', 'AVUSTURYA', 'AZARBAYCAN', 'BAHAMALAR', 'BAHREYN', 'BANGLADES', 'BARBADOS', 'BELARUS', 'BELCIKA', 'BELIZE', 'BENIN', 'BERMUDA', 'BIRLESIK ARAP EMIRLIGI', 'BOLIVYA', 'BOSNA HERSEK', 'BOTSVANA', 'BREZILYA', 'BRUNEI', 'BULGARISTAN', 'BURKINA FASO', 'BURMA (MYANMAR)', 'BURUNDI', 'BUTAN', 'CAD', 'CECENISTAN', 'CEK CUMHURIYETI', 'CEZAYIR', 'CIBUTI', 'CIN', 'DANIMARKA', 'DOGU TIMOR', 'DOMINIK', 'DOMINIK CUMHURIYETI', 'EKVATOR', 'EKVATOR GINESI', 'EL SALVADOR', 'ENDONEZYA', 'ERITRE', 'ERMENISTAN', 'ESTONYA', 'ETYOPYA', 'FAS', 'FIJI', 'FILDISI SAHILI', 'FILIPINLER', 'FINLANDIYA', 'FRANSA', 'GABON', 'GAMBIYA', 'GANA', 'GINE', 'GRANADA', 'GRONLAND', 'GUADELOPE', 'GUAM ADASI', 'GUATEMALA', 'GUNEY AFRIKA', 'GUNEY KORE', 'GURCISTAN', 'GUYANA', 'HAITI', 'HINDISTAN', 'HIRVATISTAN', 'HOLLANDA', 'HOLLANDA ANTILLERI', 'HONDURAS', 'HONG KONG', 'INGILTERE', 'IRAK', 'IRAN', 'IRLANDA', 'ISPANYA', 'ISRAIL', 'ISVEC', 'ISVICRE', 'ITALYA', 'IZLANDA', 'JAMAIKA', 'JAPONYA', 'KAMBOCYA', 'KAMERUN', 'KANADA', 'KARADAG', 'KATAR', 'KAZAKISTAN', 'KENYA', 'KIRGIZISTAN', 'KOLOMBIYA', 'KOMORLAR', 'KONGO', 'KOSOVA', 'KOSTARIKA', 'KUBA', 'KUDUS', 'KUVEYT', 'KUZEY KIBRIS', 'KUZEY KORE', 'LAOS', 'LESOTO', 'LETONYA', 'LIBERYA', 'LIBYA', 'LIECHTENSTEIN', 'LITVANYA', 'LUBNAN', 'LUKSEMBURG', 'MACARISTAN', 'MADAGASKAR', 'MAKAO', 'MAKEDONYA', 'MALAVI', 'MALDIVLER', 'MALEZYA', 'MALI', 'MALTA', 'MARTINIK', 'MAURITIUS ADASI', 'MAYOTTE', 'MEKSIKA', 'MIKRONEZYA', 'MISIR', 'MOGOLISTAN', 'MOLDAVYA', 'MONAKO', 'MONTSERRAT (U.K.)', 'MORITANYA', 'MOZAMBIK', 'NAMBIYA', 'NEPAL', 'NIJER', 'NIJERYA', 'NIKARAGUA', 'NIUE', 'NORVEC', 'ORTA AFRIKA CUMHURIYETI', 'OZBEKISTAN', 'PAKISTAN', 'PALAU', 'PANAMA', 'PAPUA YENI GINE', 'PARAGUAY', 'PERU', 'PITCAIRN ADASI', 'POLONYA', 'PORTEKIZ', 'PORTO RIKO', 'REUNION', 'ROMANYA', 'RUANDA', 'RUSYA', 'SAMOA', 'SENEGAL', 'SEYSEL ADALARI', 'SILI', 'SINGAPUR', 'SIRBISTAN', 'SLOVAKYA', 'SLOVENYA', 'SOMALI', 'SRI LANKA', 'SUDAN', 'SURINAM', 'SURIYE', 'SUUDI ARABISTAN', 'SVALBARD', 'SVAZILAND', 'TACIKISTAN', 'TANZANYA', 'TAYLAND', 'TAYVAN', 'TOGO', 'TONGA', 'TRINIDAT VE TOBAGO', 'TUNUS', 'TURKIYE', 'TURKMENISTAN', 'UGANDA', 'UKRAYNA', 'UKRAYNA-KIRIM', 'UMMAN', 'URDUN', 'URUGUAY', 'VANUATU', 'VATIKAN', 'VENEZUELA', 'VIETNAM', 'YEMEN', 'YENI KALEDONYA', 'YENI ZELLANDA', 'YESIL BURUN', 'YUNANISTAN', 'ZAMBIYA', 'ZIMBABVE']
            
    ABD = ['AKRON', 'ALBANY', 'ALBUQUERQUE', 'ALEXANDRIA', 'ALLENTOWN', 'AMES', 'AMHERST', 'ANAHEIM', 'ANCHORAGE', 'ANDERSON', 'ANN ARBOR', 'ANNAPOLIS', 'ARNOLD', 'ARUBA', 'ATLANTA', 'AUBURN', 'AUGUSTA', 'AUSTIN', 'BALTIMORE', 'BANNER ELK', 'BATON ROUGE', 'BAY CITY', 'BEAUMONT', 'BENNINGTON', 'BENTON', 'BERKELEY', 'BETHESDA', 'BETHLEHEN', 'BINGHAMTON', 'BIRMINGHAM', 'BISMARCK', 'BLACKSBURG', 'BLOOMFIELD', 'BLOOMINGTON', 'BOCA RATON', 'BOISE', 'BOSTON', 'BOULDER', 'BOWLING GREEN', 'BOYNTON BEACH', 'BRAINERD', 'BRIDGEPORT', 'BRISTOL', 'BROOKLYN (Cattaraugus)', 'BUFFALO', 'BURBANK', 'BURLINGTON', 'CAMDEN', 'CARSON CITY', 'CHAMPAIGN', 'CHANDLER', 'CHARLESTON', 'CHARLOTTE', 'CHARLOTTESVILLE', 'CHEYENNE', 'CHICAGO', 'CHICO', 'CHULA VISTA', 'CINCINNATI', 'CLEARWATER', 'CLEMSON', 'CLEVELAND', 'COLLEGE STATION', 'COLORADO SPRINGS', 'COLUMBIA', 'COLUMBUS', 'CONCORD', 'CORDOVA', 'CORVALLIS', 'COSTA MESA', 'COUNCIL BLUFFS', 'DALLAS', 'DALY CITY', 'DANBURY', 'DANVILLE', 'DAVIS', 'DAYTON', 'DAYTONA BEACH', 'DENTON', 'DENVER', 'DES MOINES', 'DESTIN', 'DETROIT', 'DOTHAN', 'DOVER', 'DULUTH', 'DURHAM', 'EANTONTOWN', 'EAST LANSING', 'EL PASO', 'ELMIRA', 'ERIE', 'ESCONDIDO', 'EVANSVILLE', 'EXETER', 'FAIRFIELD', 'FALMOUTH', 'FENWICK ISLAND', 'FLINT', 'FLORENCE', 'FOLSOM', 'FORT BENNING', 'FORT COLLINS', 'FORT LAUDERDALE', 'FORT WAYNE', 'FORT WORTH', 'FRANKFORT', 'FREMONT', 'FRESNO', 'GAINESVILLE', 'GALESBURG', 'GARY', 'GENEVA', 'GLENDALE', 'GOLETA', 'GRAND CANYON', 'GRAND RAPIDS', 'GREENSBORO', 'GULF SHORES', 'HARRISBURG', 'HARTFORD', 'HATTIESBURG', 'HELENA', 'HILO', 'HONOLULU', 'HOUGHTON', 'HOUSTON', 'HUNTINGTON BEACH', 'HUNTSVILLE', 'INDIANA', 'INDIANAPOLIS', 'INGLEWOOD', 'IOWA CITY', 'IRVINE', 'ITHACA', 'JACKSON', 'JACKSONVILLEE', 'JEFFERSON CITY', 'JUNEAU', 'KANSAS CITY', 'KENOSHA', 'KENT', 'KINGSPORT', 'KNOXVILLE', 'KODIAK', 'LAFAYETTE', 'LANCASTER', 'LANSING', 'LAREDO', 'LAS VEGAS', 'LAWRENCE', 'LAWTON', 'LEXINGTON', 'LINCOLN', 'LITTLE ROCK', 'LOMPOC', 'LONG BEACH', 'LOS ANGELES', 'LOUISVILLE', 'LUBBOCK', 'LYNN', 'MADISON', 'MANCHESTER', 'MANHATTAN', 'MARYVILLE', 'MEMPHIS', 'MESA', 'MIAMI', 'MICHIGAN CENTER', 'MILFORD', 'MILWAUKEE', 'MINNEAPOLIS', 'MOBILE', 'MODESTO', 'MONTEREY', 'MONTGOMERY', 'MONTPELIER', 'MORGANTOWN', 'MOSCOW', 'NAKNEK', 'NASHVILLE', 'NEW BRUNSWICK', 'NEW HAVEN', 'NEW ORLEANS', 'NEW YORK', 'NEWARK', 'NEWTON', 'NORFOLK', 'NORTH PLAINFIELD', 'NORWALK', 'OAK RIDGE', 'OAKLAND', 'OCALA', 'OCEAN CITY', 'OCEANSIDE', 'OGDEN', 'OKLAHOMA CITY', 'OLYMPIA', 'OMAHA', 'ONTARIO', 'ORLANDO', 'OXFORD', 'OXNARD', 'PALM BEACH', 'PALM SPRINGS', 'PASADENA', 'PATERSON', 'PENDLETON', 'PENSACOLA', 'PETERSBURG', 'PHILADELPHIA', 'PHOENIX', 'PIERRE', 'PISCATAWAY', 'PITTSBURGH', 'PORTLAND', 'PRINCETON', 'PROVIDENCE', 'RALEIGH', 'RAPID CITY', 'RENO', 'RHINELANDER', 'RICHMOND', 'RIVERSIDE', 'ROCHESTER', 'ROCK SPRINGS', 'RODANTHE', 'ROLLA', 'RONKONKOMA', 'ROY', 'SACRAMENTO', 'SAINT PAUL', 'SAINT PETERSBURG', 'SALEM', 'SALINAS', 'SALT LAKE CITY', 'SAN ANTONIO', 'SAN BERNARDINO', 'SAN DIEGO', 'SAN FRANCISCO', 'SAN JOSE', 'SANTA BARBARA', 'SANTA CLARA', 'SANTA CLARITA', 'SANTA FE', 'SANTA MONICA', 'SAVANNAH', 'SCOTCH PLAINS', 'SCOTTSDALE', 'SEATTLE', 'SEWARD', 'SHEBOYGAN', 'SHELBY', 'SIMI VALLEY', 'SISKIYOU', 'SOMERSET', 'SPRING HILL', 'SPRINGFIELD', 'ST. LOUIS', 'STAMFORD', 'STATE COLLEGE', 'STEVENS POINT', 'STILLWATER', 'STOCKTON', 'STRATFORD', 'SUN VALLEY', 'SUPERIOR', 'SYRACUSE', 'TALLAHASSEE', 'TAMAQUA', 'TAMPA', 'TEMPE', 'THOUSAND OAKS', 'TITUSVILLE', 'TOLEDO', 'TOPEKA', 'TORRANCE', 'TRENTON', 'TROY', 'TUCSON', 'TULSA', 'TUSTIN', 'TWIN FALLS', 'UNION CITY', 'URBANA', 'VALDEZ', 'VALLEJO', 'VERNON', 'WARRENTON', 'WASHINGTON', 'WATERBURY', 'WEIRTON', 'WEST HOLLYWOOD', 'WESTFIELD', 'WICHITA', 'WICHITA FALLS', 'WILMINGTON', 'WINTER HAVEN', 'WORCESTER', 'YOUNGSTOWN']

    AFGANISTAN = ['CALALABAD', 'FARAH', 'FEYZABAD', 'GARDIZ', 'GHAZNI', 'HERAT', 'KABIL', 'KANDAHAR', 'KHANABAD', 'KHOLM', 'KONDOZ', 'LASHKAR GAH', 'MEYMANEH', 'MEZAR-I SERIF', 'MORGHAB', 'POL-E KHOMRI', 'SHEBERGHAN', 'TEYVAREH', 'ZARANJ']
    
    ALMANYA = ['AACHEN', 'AALEN', 'ACHERN', 'ACHIM', 'ADENAU', 'AHAUS', 'AHLEN', 'AHRENSBURG', 'AHRWEILER', 'AICHACH', 'ALBSTADT', 'ALDENHOVEN', 'ALFELD-LEINE', 'ALFTER-WITTERSCHLICK', 'ALLACH(MUNIH)', 'ALLENDORF/EDER', 'ALLENSBACH', 'ALLERSBERG', 'ALSDORF', 'ALSFELD-HESSEN', 'ALTDORF B. NURNBERG', 'ALTENA', 'ALTENERDING', 'ALTENKIRCHEN', 'ALZEY', 'AMBERG', 'AMERSFORT', 'ANDERNACH', 'ANSBACH', 'ARNSBERG', 'ARNSTORF', 'AROLSEN', 'ASBACH-BAUMENHEIM', 'ASCHAFFENBURG', 'ASCHEBERG', 'ATTENDORN', 'AUGSBURG', 'AUGUSTDORF', 'BAAR-EBENHAUSEN', 'BABENHAUSEN/BAVAIRA', 'BABENHAUSEN/HESSEN', 'BACKNANG', 'BAD BRAMSTEDT', 'BAD CAMBERG', 'BAD DURKHEIM', 'BAD EMS', 'BAD ESSEN', 'BAD HERSFELD', 'BAD HOMBURG', 'BAD HONNEF AM RHEIN', 'BAD KREUZNACH', 'BAD LAUTERBERG', 'BAD LIPPSPRINGE', 'BAD NAUHEIM', 'BAD OLDESLOE', 'BAD SACKINGEN', 'BAD SALZUFLEN', 'BAD SCHWALBACH', 'BAD SEGEBERG', 'BAD URACH', 'BAD VILBEL', 'BAD WALDSEE', 'BAD WILDUNGEN', 'BAD WURZACH', 'BADEN-BADEN', 'BADENDORF', 'BAD-SCHUSSENRIED', 'BAESWEILER', 'BALINGEN', 'BALVE', 'BAMBERG', 'BARMEN(Wuppertal)', 'BAUTZEN', 'BAYREUTH', 'BEBRA', 'BECKUM (NEUBECKUM)', 'BEELITZ', 'BEERFELDEN', 'BENDORF (RHINELAND)', 'BENSHEIM', 'BERGEDORF', 'BERGHEIM', 'BERGISH-GLADBACH', 'BERGKAMEN', 'BERGNEUSTADT', 'BERLIN', 'BERNAU', 'BESTWIG', 'BETTENHAUSEN', 'BETZDORF', 'BEXBACH', 'BIBERACH', 'BIBERACH/RISS', 'BIEBESHEIM AM RHEIN', 'BIEDENKOPF', 'BIELEFELD', 'BILLSTEDT', 'BINGEN', 'BISCHOFSHEIM', 'BISMARCK', 'BISSINGEN AN DER ENZ', 'BLANKENHEIM', 'BLAUBEUREN', 'BLOMBERG', 'BLUMBERG', 'BLUMENTHAL', 'BOBINGEN', 'BOBLINGEN', 'BOCHOLT', 'BOCHUM', 'BOFFZEN', 'BOHMTE', 'BONEN', 'BONN', 'BONNDORF', 'BOPFINGEN', 'BORKEN (HESSEN)', 'BORNHEIM', 'BOTTROP', 'BOTZINGEN', 'BRAKE', 'BRAKEL', 'BRAMBAUER (LUNEN)', 'BRAMSCHE', 'BRANDENBURG', 'BRAUNSCHWEIG', 'BREIDENBACH', 'BREMEN', 'BREMERHAVEN', 'BRETTEN', 'BREUBERG', 'BRILON', 'BRUCHSAL', 'BRUCKMUHL', 'BRUHL', 'BUCHEN', 'BUCHLOE', 'BUCHOLZ IN DER N.', 'BUCKEBURG', 'BUDINGEN', 'BUDLESDORF', 'BUGGINGEN', 'BULLAY', 'BUNDE', 'BURGAU', 'BURGDORF', 'BURGHAUSEN', 'BURGKIRCHEN AN DER A', 'BURGLENGENFELD', 'BURLADINGEN', 'BURSCHEID', 'BURSTADT', 'BUTZBACH', 'CALW (HIRSAU)', 'CASTROP-RAUXEL', 'CELLE', 'CHEMNITZ', 'CLOPENBURG', 'COBURG', 'COESFELD', 'CRAILSHEIM', 'CUXHAVEN', 'DACHAU', 'DAHLHAUSEN', 'DARMSTADT', 'DATTELN', 'DEGGENDORF', 'DELBRUCK', 'DELLWIG', 'DELMENHORST', 'DENZLINGEN', 'DERNE(DORT.)', 'DETMOLD', 'DETTINGEN/ERMS', 'DIEBURG', 'DIETENHEIM', 'DIETZENBACH', 'DILLENBURG', 'DILLINGEN (SAAR)', 'DILLINGEN(SAAR)', 'DINGOLFING', 'DINSLAKEN', 'DISSEN', 'DITZINGEN', 'DONAUWORTH', 'DORMAGEN', 'DORSTEN', 'DORTMUND', 'DRENSTEINFURT', 'DRESDEN', 'DUISBURG', 'DULMEN', 'DUREN', 'DURLACH', 'DUSSELDORF', 'EBERBACH', 'EBERSWALDE', 'EBINGEN', 'ECKERNFORDE', 'EHINGEN (DONAU)', 'EHRINGSHAUSEN', 'EICHSTATT', 'EISENBERG', 'EITORF', 'ELLWANGEN', 'ELMSHORN', 'ELSDORF', 'EMDEN', 'EMMELSHAUSEN', 'EMMENDINGEN', 'EMMERICH', 'EMMERTHAL', 'ENGELSKIRCHEN', 'ENNETACH / MENGEN', 'EPPINGEN', 'ERBACH', 'ERFTSTADT', 'ERFURT', 'ERKELENZ', 'ERKRATH', 'ERLANGEN', 'ERLE', 'ERLENBACH AM MAIN', 'ESCHBORN', 'ESCHWEILER', 'ESLOHE', 'ESPELKAMP', 'ESSEN', 'ESSLINGEN', 'ETTLINGEN', 'EUSKIRCHEN', 'EUTIN', 'FALKENSE', 'FAURSTENFELDBRUCK', 'FELSBERG', 'FILDERSTADT', 'FINDORF', 'FINKENWERDER', 'FLENSBURG', 'FORCHEIM', 'FRANKENBERG /EDER', 'FRANKENTHAL', 'FRANKFURT', 'FRECHEN', 'FREIBERG', 'FREIBURG', 'FREISING', 'FREUDENSATDT', 'FREYSTADT', 'FRIEDBERG (BAVARIA)', 'FRIEDBERG (HESSEN)', 'FRIEDRECHSDROF', 'FRIEDRICHSHAFEN', 'FULDA', 'FURSTENWALDE', 'FURTH', 'FURTH ODW. (HESSEN)', 'FURTHEN (SIEG)', 'FURTWANGEN', 'FUSSEN', 'GAGGENAU', 'GAILDORF', 'GAMMERTINGEN', 'GARBSEN', 'GARCHING', 'GARMISCH-PART.', 'GEESTHACHT', 'GEISENFELD', 'GEISLINGEN (STEIGE)', 'GELDERN', 'GELNHAUSEN', 'GELSENKIRCHEN', 'GENGENBACH', 'GENTHIN', 'GEORGSMARIENHUTTE', 'GERA', 'GERMERING', 'GERMERSHEIM', 'GEROLSTEIN', 'GERSTHOFEN', 'GESEKE', 'GEVELSBERG', 'GIENGEN AN DER BRENZ', 'GIESSEN', 'GIFHORN', 'GILCHING', 'GLADBECK', 'GLADENBACH', 'GLAUCHAU', 'GLUCKSTADT', 'GOPPINGEN', 'GORLITZ', 'GOSLAR', 'GOTTINGEN', 'GOTTMADINGEN', 'GRABEN-NEUDORF', 'GRASELLENBACH', 'GREIFSWALD', 'GREVEN', 'GREVENBROICH', 'GROMITZ', 'GRONAU', 'GROSS-GERAU', 'GRUNSTADT', 'GUGLINGEN -EIBENSBAC', 'GUMMERSBACH', 'GUNDELSHEIM', 'GUNZBURG', 'GUNZENHAUSEN', 'GUTERSLOH', 'HAGEN (Ruhr Valley)', 'HAIGER', 'HAIGERLOCH', 'HALLE(Saxony-Anhalt)', 'HALVER', 'HAMBURG', 'HAMELN', 'HAMM', 'HAMM (MARL)', 'HAMME', 'HANAU', 'HANNOVER', 'HARBURG', 'HARSEWINKEL', 'HASLACH', 'HASPE', 'HASSEL', 'HATTINGEN', 'HAUSHAM/MIESBACH', 'HECHINGEN', 'HEESSEN', 'HEIDE', 'HEIDELBERG', 'HEIDENHEIM', 'HEILBRONN', 'HEILIGENHAUS', 'HEINSBERG', 'HELMBRECHTS', 'HELMSTEDT', 'HEMER', 'HENGELO (GELDERLAND)', 'HEPBORN', 'HEPPENHEIM A.D.BERG.', 'HERFORD', 'HERNE', 'HERRENBERG', 'HERRINGEN', 'HERSBRUCK', 'HERTEN', 'HERZBERG AM HARZ', 'HERZOGENAURACH', 'HERZOGENRATH', 'HESSISCH LICHTENAU', 'HESSISCH OLDENDORF', 'HEUBACH', 'HILDEN', 'HILDESHEIM', 'HIRSCHHORN (HESSEN)', 'HOCHFELD (DUIS.)', 'HOCHHEIM AM MAIN', 'HOCHST IM ODENWALD', 'HOCKENHEIM', 'HOF(Bavaria)', 'HOFGEISMAR', 'HOFHEIM', 'HOHENLIMBURG', 'HOHENSTEIN -OBERSTET', 'HOHR -GRENZHAUSEN', 'HOLZMINDEN', 'HOMBRUCH', 'HOMBURG-SAAR', 'HORB-NECKAR', 'HORGAU', 'HORN - BAD MEINBERG', 'HORST', 'HOVEL', 'HOXTER', 'HOYERSWERDA', 'HUCKELHOVEN', 'HUFINGEN', 'HUNGEN', 'HUNTEBURG', 'HURTH', 'HUSUM', 'IBBENBUREN', 'ICHENHAUSEN', 'IDSTEIN', 'ILLERTISSEN', 'IMMENSTADT', 'INGELHEIM', 'INGOLSTADT', 'INNINGEN', 'ISERLOHN', 'ISNY', 'ITZEHOE', 'JUCHEN', 'JUNKERATH', 'JUTERBORG', 'KAISERSLAUTERN', 'KALTENKIRCHEN', 'KAMEN', 'KAMP -LINTFROT', 'KARBEN', 'KARLSRUHE', 'KARLSTADT', 'KASSEL', 'KAUFBEUREN', 'KEHL', 'KELHEIM', 'KELSTERBACH', 'KEMPTEN', 'KERPEN', 'KIEL', 'KIPFENBERG', 'KIRCHDORF', 'KIRCHDORF -ILLER', 'KIRCHHAIN', 'KIRCHHEIM (TECK)', 'KIRHHEIM (NECKAR)', 'KIRN', 'KITZINGEN', 'KOBLENZ', 'KOLBERMOOR', 'KOLN', 'KONGEN', 'KONIGSBRUNN', 'KONIGSLUTTER', 'KONIGSWINTER', 'KONSTANZ', 'KONZ', 'KORBACH', 'KORNWESTHEIM', 'KRAY', 'KREFELD', 'KREMMEN', 'KREUZLINGEN', 'KREUZTAL', 'KRONSHAGEN', 'KRUMBACH', 'KULMBACH', 'LAATZEN', 'LADENBURG', 'LAGE', 'LAHR (SCHW.)', 'LAICHINGEN', 'LAMPERTHEIM', 'LANDAU', 'LANDSBERG AM LECH', 'LANDSHUT', 'LANDSTUHL', 'LANGEN', 'LANGENARGEN', 'LANGENAU (WURTT)', 'LANGENFELD', 'LANGENHAGEN', 'LAPPERSDORF', 'LAUBACH (HESSEN)', 'LAUCHHAMMER', 'LAUDA', 'LAUENBURG', 'LAUENFORDE', 'LAUF A.D.PEGNITZ', 'LAUFACH', 'LAUINGEN', 'LAUPHEIM', 'LAUTERBACH', 'LEHRTE', 'LEICHLINGEN', 'LEIMEN', 'LEIPZIG', 'LEMGO', 'LEMWERDER', 'LENGERICH', 'LENNESTADT', 'LEONBERG', 'LEUTKIRCH', 'LEVERKUSEN', 'LICHTENFELS', 'LIMBURG AN DER LAHN', 'LIMESHAIN -ROMMERSHA', 'LINDAU (BAVARIA)', 'LINDENBERG IM ALLGAU', 'LINDLAR', 'LINZ AM RHEIN', 'LIPBACH', 'LIPPSTADT', 'LOBBERICH', 'LOHMAR', 'LOHNE', 'LOHR A.M.', 'LOLLAR', 'LONSEE', 'LORCH', 'LORRACH', 'LUBBECKE - GEHLENBEC', 'LUBBEN', 'LUBECK', 'LUCKENWALDE', 'LUDENSCHEID', 'LUDWIGSBURG', 'LUDWIGSHAFEN', 'LUGDE', 'LUNEBURG', 'LUNEN', 'LUSTADT', 'MAGDEBURG', 'MAGSTADT', 'MAINBURG', 'MAINZ', 'MANNHEIM', 'MARBURG', 'MARKDORF', 'MARKT ERLBACH', 'MARKT SCHWABEN', 'MARKTHEIDENFELD', 'MARKTOBERDORF', 'MARKTREDWITZ', 'MARL', 'MARSBERG', 'MAUERKIRCHEN', 'MAULBRONN', 'MAXDORF', 'MEIENRZHAGEN', 'MEISSEN', 'MELLE', 'MELSUNGEN', 'MEMMINGEN', 'MENDEN', 'MERZIG', 'MESCHEDE', 'MESSKIRCH', 'METTMANN', 'METZINGEN', 'MICHELSTADT', 'MIESBACH', 'MILTENBERG', 'MINDELHEIM', 'MINDEN', 'MOERS', 'MOGLINGEN', 'MOLLN', 'MONCHENGLADBACH', 'MONHEIM', 'MONTABAUR', 'MOOSBURG', 'MORFELDEN - WALLDORF', 'MOSBACH', 'MUHLHEIM', 'MUHLHOFEN', 'MULHEIM AN DER RUHR', 'MULLHEIM', 'MUNCHBERG', 'MUNCHEN', 'MUNDERKINGEN', 'MUNSINGEN', 'MUNSTER', 'MURNAU', 'MURRHARDT', 'MUTTERSTADT', 'NACHRODT', 'NAGOLD', 'NASSAU', 'NAUEN', 'NELLINGEN A.D.FILDER', 'NERESHEIM', 'NERSINGEN', 'NEU ULM', 'NEUBURG AN DER DONAU', 'NEUFAHRN (NDB)', 'NEU-ISENBURG', 'NEUKIRCHEN (NRW)', 'NEUKIRCHEN (SAARLAND', 'NEUKIRCHEN (SACHSEN-', 'NEUMARKT IN DER OBER', 'NEUMUNSTER', 'NEUSS', 'NEUSS - NORF', 'NEUSTADT (HESSEN)', 'NEUSTADT A.D. WEINST', 'NEUSTADT B. COBURG', 'NEUTRAUBLING', 'NEUWIED', 'NIDDA', 'NIEDERKASSEL', 'NIENBURG (WESER)', 'NIENHAGEN', 'NORDENHAM', 'NORDERSTEDT', 'NORDHORN', 'NORDLINGEN', 'NORTHEIM', 'NURNBERG', 'NURTINGEN', 'OBERADEN', 'OBERASBACH', 'OBERDERDINGEN', 'OBERHAUSEN (NR-W)', 'OBERNDORF A.N.', 'OBERSTENFELD / WURTT', 'OBERTSHAUSEN', 'OBERURSEL', 'ODENTHAL', 'OELDE', 'OER-ERKENSCHWICK', 'OFFENBACH', 'OFFENBURG', 'OGGERSHEIM (LUDWIGSH', 'OHRINGEN', 'OLCHING', 'OLDENBURG', 'OLPE', 'ORANIENBURG', 'ORTENBURG', 'OSNABRUCK', 'OSTERHOLZ-SCHARMBECK', 'OSTERODE/HARZ', 'OTTERSBERG', 'OVERATH', 'PADERBORN', 'PAPENBURG', 'PARSBERG', 'PASSAU', 'PEINE', 'PELKUM', 'PETERSHAGEN', 'PFALZGRAFENWEILER', 'PFORZHEIM', 'PFULLENDORF', 'PFUNGSTADT', 'PHILIPPSBURG', 'PINNEBERG', 'PIRMASENS', 'PLETTENBERG', 'POSTDAM', 'PREETZ', 'PULHEIM', 'QUICKBORN', 'RADEVORMWALD', 'RADOLFZELL', 'RAISDORF', 'RANSBACH-BAUMBACH', 'RASTATT', 'RATHENOV', 'RATINGEN', 'RAVENSBURG', 'RECKLINGHAUSEN', 'REDWITZ A.D.RODACH', 'REGENSBURG', 'REHAU', 'REHBURG-LOCCUM', 'REMAGEN', 'REMSCHEID', 'RENDSBURG', 'REPELEN (MOERS)', 'REUTLINGEN', 'RHEDA-WIEDENBRUCK', 'RHEINBACH', 'RHEINBERG', 'RHEINDAHLEN', 'RHEINE', 'RHEINFELDEN-KARSAU', 'RHEINHAUSEN (DUIS.)', 'RIETBERG', 'RINTELN', 'ROCKENHAUSEN', 'RODACH', 'RONSDORF', 'ROSENHEIM', 'ROSRATH', 'ROSTOCK', 'ROTENBURG', 'ROTH', 'ROTHAUSEN', 'ROTHENBACH -A.D.PEGN', 'ROTHENBURG O.D.TAUBE', 'ROTTENBURG', 'ROTTWEIL', 'RUMELN (DUIS.)', 'RUSSELSHEIM', 'SAARBRUCKEN', 'SAARLOUIS', 'SACHSENHEIM', 'SALZGITTER', 'SALZGITTER BAD', 'SALZKOTTEN', 'SALZWEDEL', 'SARSTEDT', 'SAULGAU', 'SCHIFFERSTADT', 'SCHIRNDING', 'SCHLESWIG', 'SCHLUCHTERN', 'SCHMELZ', 'SCHOMBERG', 'SCHONGAU', 'SCHOPFHEIM', 'SCHORNDORF', 'SCHROBENHAUSEN', 'SCHUTTORF', 'SCHWABACH', 'SCHWABISCH GMUND', 'SCHWABISCH HALL', 'SCHWANDORF', 'SCHWANINGEN', 'SCHWARZENBACH', 'SCHWARZENBEK', 'SCHWEINFURT', 'SCHWELM', 'SCHWERTE', 'SCHWETZINGEN', 'SEESEN', 'SELB', 'SELBITZ', 'SELTERS', 'SENDEN', 'SENDENHORST', 'SIEGBURG', 'SIEGEN', 'SIGMARINGEN', 'SIMMERN', 'SINDELFINGEN', 'SINDORF', 'SINGEN', 'SINSHEIM', 'SINZIG', 'SOEST', 'SOLINGEN', 'SOLTAU', 'SONTHEIM', 'SOULTZ', 'SPAICHINGEN', 'SPENGE', 'SPEYER', 'SPROCKHOVEL', 'ST. AUGUSTIN', 'ST.INGBERT', 'ST.WENDEL', 'STADE-BUTZFLETH', 'STADTALLENDORF', 'STADTHAGEN', 'STADTLOHN', 'STADTOLDENDORF', 'STADTPROZELTEN', 'STEELE', 'STEINFURT', 'STEINHAGEN', 'STEINHEIM', 'STEMWEDE-OPPENWEHE', 'STERZHAUSEN', 'STOLBERG', 'STRAUBING', 'STRAUSBERG', 'STUTTGART', 'SULINGEN', 'SULZBACH', 'SUSSEN', 'TELGTE', 'TETTAU', 'TRIER', 'TROISDORF', 'TROSSINGEN', 'TROSTBERG AN DER ALZ', 'TUBINGEN', 'TURKHEIM', 'TUTTLINGEN', 'UBACH-PALENBERG', 'UBERLINGEN', 'UCHTE', 'UELZEN', 'UERDING (KREFELD)', 'UETERSEN', 'UHINGEN', 'ULM', 'ULMEN', 'UNNA', 'UNTERSCHLEISSHEIM', 'URBACH', 'USINGEN', 'VAIHINGEN-ENZ', 'VECHTA', 'VELBERT', 'VERDEN', 'VIERNHEIM', 'VIERSEN', 'VILLINGEN-SCHWEN.', 'VILSBIBURG', 'VLOTHO', 'VOERDE', 'VOHRINGEN', 'VOHWINKEL', 'VOLKLINGEN', 'WACHTERSBACH', 'WAGENFELD', 'WAGHAUSEL (WIESS.)', 'WAIBLINGEN', 'WALDBROL', 'WALDENBUCH', 'WALDKRAIBURG', 'WALDSHUT-TIENGEN', 'WALLDORF', 'WALLERDORF', 'WALSRODE', 'WALTROP', 'WANGEN (BADEN-WURTT.)', 'WARDENBURG', 'WARENDORF', 'WARSTEIN', 'WASSENBERG', 'WASSERBURG / INN', 'WASSERBURG AM BODENS', 'WATTENSCHEID', 'WEDEL', 'WEGBERG', 'WEHINGEN', 'WEIDEN', 'WEIL AM RHEIN', 'WEILBURG', 'WEILERWIST', 'WEILHEIM', 'WEIMAR', 'WEINGARTEN', 'WEINHEIM', 'WEISSENBURG IN BAYER', 'WEISSENHORN', 'WELVER', 'WELZHEIM', 'WEMDING', 'WENDELSTEIN', 'WERDOHL', 'WERL', 'WERMELSKIRCHEN', 'WERNAU', 'WERNE A.D.LIPPE', 'WERTHEIM', 'WERTINGEN', 'WESEL', 'WESSELING', 'WESTERHOLT', 'WESTERSTEDE', 'WETTER (NRW)', 'WETZLAR', 'WICKEDE (DORT.)', 'WIEBELSKIRCHEN', 'WIEDENBRUCK', 'WIESBADEN', 'WIESLOCH', 'WILDBAD I. SCHW.', 'WILDESHAUSEN', 'WILHELMSBURG', 'WILHELMSHAVEN', 'WILLICH', 'WINNENDEN', 'WINSEN-LUHE', 'WINTERLINGEN', 'WIPPERFURTH', 'WITTEN', 'WITTENBERGE', 'WITTEN-HERBEDE', 'WITTLICH', 'WITZENHAUSEN', 'WOLFENBUTTEL', 'WOLFHAGEN', 'WOLFSBURG', 'WORMS', 'WULFRATH', 'WUNSTORF', 'WUPPERTAL', 'WURSELEN', 'WURZBURG', 'WURZEN', 'ZEITZ', 'ZIRNDORF', 'ZULPICH', 'ZWEIBRUCKEN', 'ZWICKAU']
    
    ANDORRA = ['ANDORRA LA VELLA']
    
    ANGOLA = ['BENGUELA', 'HUAMBO', 'KUITO', 'LUANDA', 'LUBANGO', 'LUCAPA', 'LUENA', 'MALANJE', 'SAURIMO', 'SUMBE', 'UIGE']
    
    ANGUILLA = ['THE VALLEY']
    
    ANTIGUA_VE_BARBUDA = ['FALMOUTH', 'SAINT JOHNS']
    
    ARJANTIN = ['AVALLANEDA', 'BAHIA BLANCA', 'BARILOCHE', 'BERAZATEGUI', 'BUENOS AIRES', 'CASEROS', 'CERES', 'CHACABUCO', 'CIPOLLETTI', 'COMODORA RIVADAVIA', 'CONCORDIA', 'CORDOBA', 'CORRIENTES', 'CRESPO', 'GENERAL ROCA', 'GENERAL SAN MARTIN', 'GENERAL SARMIENTO', 'GODOY CRUZ', 'GUALEGUAYCHU', 'LA PLATA', 'LAS HERAS', 'LOMAS DE ZAMORA', 'LUJAN DE CUYO', 'MALARGUE', 'MAR DEL PLATA', 'MARCOS JUAREZ', 'MARIANO MORENO', 'MENDOZA', 'MIRAMAR', 'MONTE GRANDE', 'MORON', 'NEUQUEN', 'PARANA', 'PASO DE LOS LIBRES', 'PINAMAR', 'PUERTO MADRYN', 'RESISTENCIA', 'RIO CUARTO', 'RIO GALLEGOS', 'RIO TERCERO', 'ROSARIO', 'SALTA', 'SALTO', 'SAN CLEMENTE DEL TUYU', 'SAN ISIDRO', 'SAN JUAN', 'SAN JUSTO', 'SAN MIGUEL DE TUCUMAN', 'SAN RAFAEL', 'SANTA FE', 'SANTA ROSA', 'SANTIAGO DEL ESTERO', 'TRELEW', 'TRES ARROYOS', 'USHUAIA', 'VICENTE LOPEZ', 'VILLA MARIA', 'VILLA NUEVA']
    
    ARNAVUTLUK = ['BAJRAM CURRI', 'BERAT', 'BURREL', 'DURRES', 'ELBASAN', 'ERSEKE', 'FIER', 'GJIROKASTER', 'ISKODRA(shkoder)', u'KORÇE', 'KRUJE', 'LUSHNJE', 'PERMET', 'PESHKOPI', 'POGRADEC', 'RRESHEN', 'SARANDE', 'TIRAN', 'VLORE']
    
    ARUBA = ['ORANJESTAD']
    
    AVUSTRALYA = ['ADELAIDE', 'ALBANY', 'ALBURY', 'ALICE SPRINGS', 'ALICE WELL', 'ARMIDALE', 'BALLARAT', 'BANKSTOWN', 'BATHURST', 'BELCONNEN', 'BENDIGO', 'BERWICK', 'BLACKTOWN', 'BOWEN', 'BOWRAL', 'BRIGHTON', 'BRISBANE', 'BROKEN HILL', 'BROOME', 'BUNBURY', 'BUNDABERG', 'BURNIE', 'BURPENGARY', 'CABOOLTURE', 'CAIRNS', 'CALOUNDRA', 'CAMDEN', 'CAMPBELLTOWN', 'CANBERRA', 'CARNARVON', 'CASTLEMAINE', 'CESSNOCK', 'CHELSEA', 'CHERMSIDE', 'CLARENCE', 'CLEVELAND', 'COFFS HARBOUR', 'COOMA (NSW)', 'COOTAMUNDRA', 'CRANBOURNE', 'CROYDON (Q)', 'DANDENONG', 'DARWIN', 'DEER PARK', 'DEVONPORT', 'DUBBO', 'ELIZABETH', 'EMERALD (Q)', 'FAIRFIELD', 'FRANKSTON', 'FREMANTLE', 'GEELONG', 'GEORGE TOWN ( T )', 'GERALDTON', 'GINNINDERRA', 'GLADSTONE', 'GLEN WAVERLEY', 'GLENORCHY', 'GOLD COAST', 'GOSFORD', 'GOULBURN', 'GRAFTON', 'GRIFFITH', 'GYMPIE', 'HAMILTON ( V )', 'HAMILTON (Tasmania)', 'HOBART', 'HORNSBY', 'HORSHAM', 'HURSTVILLE', 'INGHAM', 'INVERELL', 'IPSWICH', 'KALGOORLIE', 'KATOOMBA', 'KEMPSEY', 'KINGAROY', 'LAUNCESTON', 'LIDCOMBE', 'LISMORE', 'LITHGOW', 'LIVERPOOL', 'MACKAY', 'MAITLAND', 'MANLY', 'MARION', 'MARYBOROUGH (Q)', 'MARYBOROUGH (V)', 'MELBOURNE', 'MELTON', 'MILDURA', 'MILLECENT', 'MOE', 'MONA VALE', 'MOORABBIN', 'MOOROOLBARK', 'MORNINGTON (Q)', 'MORWELL', 'MOSMAN', 'MOUNT GAMBIER', 'MOUNT ISA', 'MUNDIWINDI', 'MURRAY BRIDGE', 'MURWILLUMBAH', 'NAMBOUR', 'NARRABRI', 'NELSON BAY', 'NEWCASTLE', 'NORTH CAMBERRA', 'NOWRA', 'NUNAWADING', 'OODNADATTA', 'ORANGE', 'PARRAMATTA', 'PENRITH', 'PERTH', 'PORT HEDLAND', 'PORT MACQUARIE', 'PORTLAND', 'PRAHRAN', 'PRESTON', 'QUEANBEYAN', 'REDCLIFFE', 'RENMARK', 'RICHMOND (Q)', 'ROCKDALE', 'ROCKHAMPTON', 'ROCKINGHAM', 'ROMA', 'RYDE', 'SALE', 'SALISBURY', 'SANDGATE', 'SHEPPARTON', 'SOUTHPORT', 'SPRINGVALE', 'SPRINGWOOD (Q)', 'SUNBURY', 'SUNSHINE', 'SUTHERLAND', 'SWAN HILL', 'SYDNEY', 'TAMWORTH', 'TEATREE GULLY', 'TOOWOOMBA', 'TORQUAY (Q)', 'TOWNSVILLE', 'TRARALGON', 'TUGGERANONG', 'ULLADULLA', 'WAGGA WAGGA', 'WANGARATTA', 'WARRAGUL', 'WARRNAMBOOL', 'WESTON CREEK', 'WHYALLA', 'WINDORAH', 'WINDSOR', 'WODEN VALLEY', 'WODONGA', 'WOLLONGONG', 'YOUNG']
    
    AVUSTURYA = ['ANSFELDEN', 'BAD VOSLAU', 'BADEN', 'BERNDORF', 'BLUDENZ', 'BREGENZ', 'DORNBIRN', 'EISENSTADT', 'FELDKIRCH', 'FREISTADT', 'GANSERNDORF', 'GMUND', 'GMUNDEN', 'GOTZIS', 'GRAZ', 'HAINBURG A.D.D.', 'HOHENEMS', 'HORN', 'INNSBRUCK', 'KAPFENBERG', 'KINDBERG', 'KITZBUHEL', 'KLAGENFURT', 'KLOSTERNEUBURG', 'KREMS AN DER DONAU', 'KUFSTEIN', 'LANDECK', 'LEOBEN', 'LIEZEN', 'LILIENFELD', 'LINZ', 'LUSTENAU', 'MITTERSILL', 'MODLING', 'MURZZUSCHLAG', 'REUTTE', 'RIED IM INNKREIS', 'SALZBURG', 'SANKT POLTEN', 'STEYR', 'TRAUN', 'VILLACH', 'VIYANA', 'WELS', 'WIENER NEUSTADT', 'WORGL', 'ZELL AM SEE', 'ZIRL', 'ZWETTL']
    
    AZARBAYCAN = ['AGDAM', 'ALI BAYRANLI', 'ASKERAN (XANKANDI)', 'ASTARA', 'BAKU', 'GENCE', 'GOYCAY', 'KACMAZ', 'KAZAKH', 'KUBA', 'KUSARY', 'LACHIN', 'LENKERAN', 'MINGACEVIR', 'NAHCIVAN', 'ORDUBAD', 'QARASU', 'SABIRABAD', 'SALYAN', 'SAMAXI', 'SEKI', 'SIYAZAN', 'SUMQAYIT', 'SUSA', 'TOVUZ', 'XUDAT', 'YEVLAX', 'ZAKATALY']
    
    BAHAMALAR = ['ABRAHAMS BAY', 'COCKBURN TOWN', 'COLONEL HILL', "COOPER'S TOWN", 'FREEPORT', 'FREETOWN', 'FRESH CREEK', 'GEORGETOWN', 'MARSH HARBOUR', 'MATTHEW TOWN', 'NASSAU', 'OLD BIGHT', 'ROCK SOUND', 'SAN ANDROS', 'SANDY POINT', 'SNUG CORNER']
    
    BAHREYN = ['AL MUHARRIK', "AR RIFA'ALGHARBI", 'MANAMA']
    
    BANGLADES = ['COMILLA', 'DHAKA', 'KHULNA', 'RAJSHAHI']
    
    BARBADOS = ['BRIDGETOWN', 'CHRISTCHURCH', 'SPEIGHTSTOWN']
    
    BELARUS = ['BABRUYSK', 'BARANAVICY', 'BARYSAW', 'BREST', 'GRODNO', 'HOMEL', 'KRYCHAW', 'LIDA', 'MAHILYOW', 'MAZYR', 'MINSK', 'MOLODECHNO [Maladzyechna]', 'ORSA', 'PINSK', 'POLATSK', 'SALIHORSK', 'SLONIM', 'VITEBSK']
    
    BELCIKA = ['AALST', 'AARSCHOT', 'ALLEUD', 'ANDENNE', 'ANTWERPEN', 'ARENDONK', 'ARLON', 'ATH', 'BERINGEN', 'BERLAAR', 'BEVEREN', 'BILZEN', 'BINCHE', 'BOORTMEERBEEK', 'BOUSSU', 'BRASSCHAAT', 'BRECHT', 'BREE', 'BRUGGE', 'BRUKSEL', 'CHARLEROI', 'CHATELET', 'COLFONTAINE', 'DEINZE', 'DENDERMONDE', 'DIEST', 'DIKSMUIDE', 'DILBEEK', 'EDEGEM', 'EISDEN', 'EVERGEM', 'FRAMERIES', 'GAVERE', 'GEEL', 'GENK', 'GENT', 'GERAARDSBERGEN', 'GRIMBERGEN', 'HAMME', 'HARELBEKE', 'HASSELT', 'HEIST-OP-DEN-BERG', 'HERENTALS', 'HEUSDEN', 'HOBOKEN', 'HOUTHALEN', 'HUY', 'IEPER', 'IZEGEM', 'JODOIGNE', 'KAPELLEN', 'KEERBERGEN', 'KNOKKE-HEIST', 'KORTRIJK', 'LA LOUVIERE', 'LANAKEN', 'LEUVEN (LOUVAIN)', 'LIEGE', 'LIER', 'LOKEREN', 'LOMMEL', 'M.FAMENNE', 'MAASEIK', 'MAASMECHELEN', 'MALDEGEM', 'MALMEDY', 'MECHELEN (MalInes)', 'MENEN', 'MERELBEKE', 'MOL', 'MONS', 'MORTSEL', 'MOUSCRON', 'NAMUR', 'NINOVE', 'NIVELLES', 'OOSTENDE', 'OOSTKAMP', 'OTTIGNIES-LAUVAIN-LA-NUVE', 'OUDENAARDE', 'OVERIJSE', 'RIXENSARD', 'ROESELARE', 'RONSE', 'SAINT-GHISLAIN', 'SCHERPENHEUVEL', 'SCHOTEN', 'SOIGNIES', 'ST.NIKLAAS', 'St.TRUIDEN', 'TEMSE', 'TIENEN', 'TONGEREN', 'TOURNAI', 'TURNHOUT', 'VERVIERS', 'VILVOORDE', 'VIRTON', 'WAREGEM', 'WATERLOO', 'WATERSCHEI', 'WAVRE', 'WESTERLOO', 'WEVELGEM', 'WINTERSLAG', 'WOLUWE-SAINT-LAMBERT', 'WOLUWE-SAINT-PIERRE', 'ZEEBRUGGE', 'ZELE', 'ZOLDER', 'ZOTTEGEM', 'ZWEVEGEM']
    
    BELIZE = ['BELIZE CITY', 'BELMOPAN', 'COROZAL', 'COROZALITO', 'DANGRIGA', 'ORANGE WALK', 'SAN IGNACIO']
    
    BENIN = ['ABOMEY', 'BATIA', 'COTONOU', 'DJOUGOU', 'GUENE', 'KANDI', 'KETOU', 'LOKOSSA', 'NATITINGOU', 'PARAKOU', 'PORTO-NOVO', 'QUIDAH', 'SAVALUO', 'SAVE']
    
    BERMUDA = ['HAMILTON', 'SAINT GEORGE', 'SOMERSET VILLAGE']
    
    BIRLESIK_ARAP_EMIRLIGI = ['ABU DHABI', 'AJMAN', 'ALAYN', 'DUBAYI', 'RAS AL KHAYMAH', 'SHARJAH']
    
    BOLIVYA = ['AIQUILE', 'APOLO', 'ATOCHA', 'BERMEJO', 'CARACOLLO', 'CHIMORE', 'CHULUMANI', 'COCHABAMBA', 'CORIOCO', 'CORIPATA', 'COTOCA (Santa Cruz)', 'GUAYARAMERIN', 'LA PAZ', 'MACHACAMARCA', 'MIZQUE', 'MONTERO', 'MOROCHATA', 'ORURO', 'PORTACHUEL (Santa Cruz)', 'POTOSI', 'PUERTO VILLARROEL', 'PUNATA', 'QUILLACOLLO', 'RIBERALTA', 'SACABA', 'SAN BORJA', 'SANTA ANA', 'SANTA CRUZ', 'SIPE SIPE', 'SUCRE', 'TARIJA', 'TRINIDAD', 'TUPIZA', 'VILLA TUNARI', 'VILLAZON', 'VINTO', 'YACUIBA']
    
    BOSNA_HERSEK = ['BANJA LUKA', 'BIHAC', 'BIJELJINA', 'BOSANSKA GRADISKA', 'BOZANSKI PETROVAC', 'BRCKO', 'BUGOJNO', 'DERVENTA', 'DOBOJ', 'DONJI VAKUF', 'FOCA', 'GORAZDE', 'GORNJI VAKUF', 'GRACANICA', 'GRADACAC', 'JAJCE', 'KONJIC', 'KOSOVA', 'LIVNO', 'MAGLAJ', 'MOSTAR', 'PRIJEDOR', 'SARAYBOSNA(sarajevo)', 'SREBRENICA', 'TRAVNIK', 'TREBINJE', 'TUZLA', 'VISOKO', 'ZENICA', 'ZVORNIK']
    
    BOTSVANA = ['GABORONE', 'GHANZI', 'LOBATSE', 'MAUN', 'SHAKAWE', 'SUNNYSIDE', 'TSHANE']
    
    BREZILYA = ['ABA ETETUBA', 'AMERICANA', 'APARECIDA DE GOIANIA', 'ARACATUBA', 'ARAJACU', 'ARARANGUA', 'ARARAQUARA', 'ATALAIA', 'ATIBAIA', 'BAGE', 'BARBACENA', 'BARCARENA', 'BARRA DO CORDA', 'BARRA MANSA', 'BARREIRAS (Bahia)', 'BAURU', 'BELEM', 'BELO HORIZONTE', 'BENTO GONCALVES', 'BETIM', 'BOA VISTA', 'BRAGANCA PAULISTA', 'BREZILYA', 'CAMPINA GRANDE', 'CAMPINAS', 'CAMPO GRANDE', 'CAMPOS DO JORDAO', 'CANDAS', 'CANELA', 'CANOAS', 'CARIACICA', 'CASCAVEL (Parana)', 'CATALAO (GoIas)', 'CAXIAS DO SUL', 'COARI', 'COLOMBO', 'CONTAGEM', 'CORURIPE', 'CRICIUMA', 'CRUZEIRO DO SUL (ACRE)', 'CUIABA', 'CURITABA', 'DELMIRO GOUVEIA', 'DIVINOPOLIS', 'FLORIANOPOLIS', 'FORTALEZA', 'FOZ DE IGUACU', 'GARANHUNS', 'GARIBALDI', 'GOIANIA', 'GRAMADO', 'GRAVATAI', 'GUARATINGUETA', 'GUARUJA', 'IBIRITE (Minas..)', 'IGACI', 'ILLHEUS', 'INAJA', 'INDAIA TUBA', 'ITABUNA', 'ITAGUAI', 'ITAPETIN INGA', 'ITATIBA', 'JEQUIE', 'JOAO PESSOA', 'JOINVILLE', 'JUIZ DE FORA', 'JUNDIAI', 'LARANJAL DO JARI', 'LIMEIRA', 'LONDRINA', 'MACAPA', 'MACEIO', 'MANACAPURU', 'MANAUS', 'MANICORE', 'MARINGA', 'MATA GRANDE', 'MATRIZ DE CAMARAJIBE', 'MAUES', 'MONTENEGRO (R.G.S.)', 'MURICI', 'NATAL', 'NEPOMUCENO (M.G)', 'NIOPOLIS', 'NOVA IGUACU', 'NOVA LIMA (M.G)', 'NOVO HANBURGO', 'PALMAS', 'PALMEIRA DOS INDIOS', 'PAO DE ACUCAR', 'PARNAIBA', 'PARNAMIRIM', 'PASSO FUNDO', 'PELOTAS', 'PENEDO', 'PETROPOLIS', 'PILAR', 'PINDAMON HANGABA', 'PIRACICABA', 'PIRAPORA', 'PIRASSUNUNGA', 'PLANALTINA', 'PORTO ALEGRE', 'PORTO NACIONAL', 'PORTO VELHO', 'PRAIA GRANDE', 'QUEIMADOS', 'RECIFE', 'RIBEIRAO DAS NEVES', 'RIBEIRAO PIRES', 'RIBEIRAO PRETO', 'RIO BRANCO', 'RIO CLARO', 'RIO DE JANEIRO', 'RIO LARGO', 'SALVADOR', "SANTA BARBARA D'OESTE", 'SANTA CRUZ DO SUL', 'SANTA LUZIA', 'SANTA RITA DO S.', 'SANTANA ', 'SANTANA DO IPANEMA', 'SANTAREM', 'SANTO ANGELO', 'SANTOS', 'SAO CARLOS (Sao Poulu)', 'SAO JOSE', 'SAO JOSE DA LAJE', 'SAO JOSE DO RIO PRETO', 'SAO JOSE DOS PINHAIS', 'SAO LEOPOLDO', 'SAO LUIS (Maranhao)', 'SAO LUIS DO QUITUNDE', 'SAO MIGUEL DOS CAMPOS', 'SAO PAULO', 'SAO SEBASTIAO (Alogora)', 'SAO VICENTE', 'SAPUCAIA DO SUL', 'SENA MADUREIRA', 'SETE LAGOAS (M.GoroIs)', 'SOBRAL (Cearal)', 'SUMARE', 'TANGARA DA SERRA (M.G.)', 'TAPAUA', 'TARAUACA', 'TAUBATE', 'TERESINA', 'TERESOPOLIS (R.D.J.)', 'TOLEDO', 'TRAIPU', 'TRES LAGOAS (M.G.D.S.)', 'UBERABA', 'UBERLANDIA', 'UNIAO DA VITORIA', 'UNIAO DOS PALMARES', 'VALINHOS', 'VARZEA GRANDE', 'VENDA NOVA', 'VIAMAO', 'VICOSA', 'VILA VELHA', 'VITORIA', 'VOLTA REDONDA']
    
    BRUNEI = ['BANDAR SERI BEGAWAN', 'KUALA BELAIT']
    
    BULGARISTAN = ['BLAGOEVGRAD', 'BURGAS', 'DIMITROVORAD', 'DOBRUCA (Tolbukhin)', 'ESKICUMA', 'ESKIZAGRA', 'FILIBE', 'HASKOY (Khaskovo)', 'ISLIMYELI(Sliven)', 'KAZANLUK', 'KIRCAALI', 'LOVECH', 'LUKOVIT', 'MESTANLI (Montana)', 'MONTANA', 'NESSEBAR', 'PAZARCIK (pazardzhik)', 'PETRICH', 'PLEVNE (Pleven)', 'PLOVDIV', 'RAZGRAD', 'RUSCUK (Ruse)', 'SAMOKOV', 'SILISTRA', 'SMOLYAN', 'SOFYA', 'STALIN (VARNA)', 'SUMNU (shumen)', 'VARNA', 'VELIKO TURNOVO', 'VRATSA']
    
    BURKINA_FASO = ['BANFORA', 'BOBO-DIOULASSO', 'BOROMO', 'DIAPAGA', 'FADA-NGOURMA', 'KOUDOUGOU', 'OUAGADOUGOU', 'OUAHIGOUYA', 'TENKODOGO']
    
    BURMA_MYANMAR = ['BASSEIN', 'HENZADA', 'MANDALAY', 'MERGUI', 'MONYWA', 'MOULMEIN', 'PEGU', 'PYINMANA (Naypyidaw)', 'TAUNGGYI', 'TAVOY', 'THATON', 'TOUNGOO', 'YANGON', 'YE']
    
    BURUNDI = ['BUJUMBURA', 'BURURI', 'GITEGA', 'NGOZI', 'RUTANA', 'RUYIGI']
    
    BUTAN = ['THIMPHU']
    
    CAD = ['ABECHE', 'ABOU-DEIA', 'AM TIMAN', 'ATI', 'BILTINE', 'BOL', 'BONGOR', 'DOBA', 'KELO', 'KOUMRA', 'LAI', 'MAO', 'MOUNDOU', 'NDJAMENA', 'OUM HADJER', 'SARH']
    
    CECENISTAN = ['GROZNY', 'GUEDERMES', 'SHALI', 'URUS-MARTAN']
    
    CEK_CUMHURIYETI = ['BLANSKO', 'BRNO', 'CESKE BUDEJOVICE', 'CHEB', 'DECIN', 'FRYDEK-MISTEK', 'HAVIROV', 'HRADEC KRALOVE', 'JIHLAVA', 'KARLOVY VARY', 'KLADNO', 'KLATOVY', 'KOPRIVNICE', 'KRNOV', 'LIBEREC', 'MLADA BOLESLAV', 'MOST', 'NACHOD', 'NOVY JICIN', 'OLOMOUC', 'OPAVA', 'OSTRAVA', 'PARDUBICE', 'PLZEN', 'PRAG', 'PRIBRAM', 'TABOR', 'TEPLICE', 'TRINEC', 'USTI NAD LABEM', 'ZLIN', 'ZNOJMO']
    
    CEZAYIR = ['ANNABA', 'BATNA', 'BECHAR', 'BEJAIA', 'BISKRA', 'BLIDA', 'CEZAYIR', 'CONSTANTINE', 'ECH CHELIFF', 'MASCARA', 'MOSTAGANEM', 'ORAN', 'OUED ATHMENIA', 'SETIF', 'SIDI BEL ABBES', 'SKIKDA', 'TEBESSA', 'TLEMCEN']
    
    CIBUTI = ['ALI SABIH', 'CIBUTI', 'DIKHIL', 'OBOCK']
    
    CIN = ['AIHUI ( HeIhe )', 'ALTAY', 'ANDA', 'ANKANG', 'ANQING', 'ANSHAN', 'ANYANG', 'BAODING', 'BAOJI', 'BAOSHAN', 'BEIHAI', 'BIJIE', 'BOSE', 'BUGT', 'CHANGCHUN (JILIN)', 'CHANGDE ( HUNAN )', 'CHANGSHA', 'CHANGSHU', 'CHANGTING ( FUJON)', 'CHANGZHI', 'CHANGZHOU (JIANGSU PRO.)', 'CHANZHOU', 'CHAOYANG', 'CHENGDE', 'CHENGDU', 'CHENZHOU ( HUNAN )', 'CHIFENG', 'CHONGQING', 'CHUXIONG', 'DALI ( SHANXI )', 'DALI ( YUNNAN )', 'DALIAN', 'DANDONG', 'DANYANG', 'DA-QAIDAM', 'DAQING', 'DAXIAN', 'DINGHAI', 'DONGFANG', 'DONGSHENG ( IMAR )', 'DONGYING', 'DULAN', 'DUNHUA', 'DUNHUANG', 'DUOLUN', 'DUSHAN', 'ENSHI', 'ERENHOT', 'FANGXIAN ( HUBE )', 'FENGJIE', 'FOSHAN', 'FUJIN', 'FUSHUN', 'FUXIN', 'FUYANG', 'FUYU', 'FUYUAN ( HeIlangjong )', 'FUZHOU (FUJIAN PRO.)', 'GANZHOU', 'GOLMUD', 'GUANGZHOU', 'GUANZHU', 'GUILIN', 'GUIYANG (GUIZHOU)', 'GUSHI', 'HAILAR', 'HAIYANG', 'HAMI', 'HANGZHOU', 'HARBIN', 'HECHI', 'HEFEI', 'HEYUAN', 'HOTAN', 'HUADIAN', 'HUAILAI', 'HUHHOT', 'HUIMIN', 'HUIZE', 'HUIZHOU', 'HUOSHAN', 'JIANGCHEN ( YANGJIANG )', 'JIANGLING ( HUBEI )', 'JIANGYIN', "JIAN'OU", 'JIEXIU', 'JILIN', 'JINAN', 'JINCHENG', 'JINGDEZHEN', 'JINING ( IMAR )', 'JINING ( Shondog )', 'JINZHOU', 'JIXI', 'KAIFENG ( HENAN )', 'KANGDING', 'KARAMAY', 'KASHI', 'KESHAN', 'KORLA', 'KOTAN', 'KUANDIAN', 'KUNMING', 'KUQA', 'LAIWU', 'LANGZHONG', 'LANZHOU', 'LETING', 'LHASA', 'LIAN XIAN ( LIonzhu )', 'LIANYUNGANG', 'LIAOYANG', 'LINGLING ( Yongzhov )', 'LINJIANG', 'LINXI', 'LINYI', 'LISHI ( SHANXI )', 'LIUZHOU', 'LIYANG', 'LONGKOU', 'LUOYANG', 'LUZHOU', 'MENGZHAI', 'MIANYANG', 'MUDANJIANG', 'NAGQU', 'NAN TONG', 'NANCHANG', 'NANCHONG', 'NANJING ( JIANGSU )', 'NANNING', 'NANPING', 'NANYANG', 'NEIJANG', 'NINGBO', 'PEKIN', 'PING TUNG CITY', 'PINGLIANG', 'PINGXIANG ( GZAR )', 'PINGXIANG ( JIANGXI )', 'QAMDO', 'QINGDAO', 'QINGJIANG', 'QINGLONG', 'QINGYUAN', 'QINHUANGDAO', 'QINZHOU', 'QIQIHAR', 'QUANZHOU', 'QUFU', 'QUXIAN ( SICHUAN )', 'QUZHOU ( HEBEI )', 'QUZHOU ( ZHEJIANG ) ', 'RIZHAO', 'RONGJIANG', 'SHACHE', 'SHANGHAI', 'SHANTOU', 'SHANWEI', 'SHAOGUAN', 'SHAOWU', 'SHAOYANG', 'SHENYANG', 'SHENZHEN', 'SHIJIAZHUANG ( HEBEI )', 'SHIYAN ( HUBEI )', 'SIPING ( JILIN )', 'SUZHOU', 'TAIYUAN', 'TANGSHAN', 'TENGCHONG', 'TIANJIN', 'TIANSHUIBU', 'TONGLIAO', 'URUMQI', 'WEIFANG', 'WENZHOU', 'WUGANG', 'WUHAN', 'WUXI', 'WUZHOU', 'XIAMEN', "XI'AN (SHAANXI)", 'XICHANG', 'XIGAZE', 'XILIN HOT', 'XINGTAI', 'XINING', 'XINXIAN', 'XINXIANG', 'XINYANG', 'XUZHOU', 'YA XIAN (SANYA)', "YA'AN", "YAN'AN", 'YANGJIANG', 'YANGZHOU', 'YANJI', 'YANTAI', 'YIBIN', 'YICHUN', 'YINCHUAN', 'YINGKOU', 'YINING', 'YUANJIANG', 'YUEYANG', 'YULIN ( GZAR )', 'YUSHU ( QINGHAI )', 'ZAOYANG', 'ZHANGJIAKOU', 'ZHANGZHOU', 'ZHANJIANG ( GUANGDONG )', 'ZHENGZHOU', 'ZHENJIANG', 'ZHENZHOU', 'ZHUHAI', 'ZHUMADIAN', 'ZHUZHOU', 'ZIBO', 'ZIGONG', 'ZUNYI']
    
    DANIMARKA = ['AABENRAA', 'AALBORG', 'AARHUS', 'BILLUND', 'BIRKEROD', 'ESBJERG', 'FREDERICIA', 'FREDERIKSHAVN', 'FREDERIKSSUND', 'HADERSLEV', 'HELSINGE TOFTE', 'HELSINGOR', 'HERNING', 'HILLEROD', 'HJORRING', 'HOLBAEK', 'HOLSTEBRO', 'HORSENS (Aalborg)', 'HORSENS (Vejle)', 'IKAST', 'KOGE', 'KOLDING', 'KOPENHAG', 'NAESTVED', 'NIVEROD', 'NORRESUNDBY', 'NYBO', 'ODENSE', 'RANDERS', 'RIBE', 'RINGKOBING', 'RINGSTED', 'ROSKILDE', 'SILKEBORG', 'SKIVE', 'SLAGELSE', 'SONDERBORG', 'SVENDBORG', 'VEJLE', 'VIBORG']
    
    DOGU_TIMOR = ['DILI']
    
    DOMINIK = ['ROSEAU']
    
    DOMINIK_CUMHURIYETI = ['AZUA DE COMPOSTELA', 'BAJOS DE HAINA', 'BANI', 'BARAHONA', 'BONAO', 'LA ROMANA', 'LA VEGA', 'MOCA', 'PUERTO PLATA', 'SAN CRISTOBAL', 'SAN FRANCISCO DE MACORIS', 'SAN JUAN', 'SAN PEDROXDE MACORIS', 'SANTIAGO', 'SANTO DOMINGO']
    
    EKVATOR = ['AMBATO', 'AZOGUES', 'BABAHOYO', 'BAHIA DE CARAQUEZ', 'CUENCA', 'ESMERALDAS', 'GUARANDA', 'GUAYAQUIL', 'IBARRA', 'LATACUNGA', 'LOJA', 'MACAS', 'MACHALA', 'MANTA', 'NUEVA LOJA', 'PORTOVIEJO', 'PUERTO BAQUERIZO MORENO', 'PUYO', 'QUITO', 'RIOBAMBA', 'SANTO DOMINGO DE LOS COLORADOS', 'TENA', 'TULCAN']
    
    EKVATOR_GINESI = ['CIUDAD DE LUBA', 'MALABO']
    
    EL_SALVADOR = ['APOPA', 'MEJICANOS', 'NUEVA SAN SALVADOR', 'SAN MIGUEL', 'SAN SALVADOR', 'SANTA ANA', 'SOYAPANGO', 'VILLA DELGADO', 'ZACATECOLUCA']
    
    ENDONEZYA = ['AMBON', 'BALIKPAPAN', 'BANDA ACEH', 'BANDAR LAMPUNG', 'BANDUNG (JAWA BARAT)', 'BANJARMASIN', 'BEKASI', 'BENGKULU', 'BINJAI', 'BLITAR', 'BOGOR', 'CIANJUR', 'CILACAP', 'CIMAHI', 'CIREBON', 'DENPASAR (BALI)', 'DEPOK', 'ENDE', 'FAKFAK', 'JAKARTA', 'JAMBI', 'JAYAPURA', 'KLATEN', 'KUPANG (TIMOR ADASI)', 'MAKASSAR', 'MALANG', 'MANADO', 'MATARAM', 'MEDAN', 'PADANG', 'PALANGKARAYA', 'PALEMBANG', 'PALU', 'PANGKALPINANG', 'PASURUAN', 'PEKANBARU', 'PEMATANGSIANTAR', 'PONTIANAK', 'PURWOKERTO', 'RABA', 'SAMARINDA', 'SEMARANG', 'SIDOARJO', 'SORONG', 'SUKABUMI', 'SUKANEGARA', 'SURABAYA', 'TANJUNGBALAI', 'TANJUNGKARANG-T.', 'TASIKMALAYA', 'TEBING TINGGI', 'YOGYAKARTA']
    
    ERITRE = ['ADI UGRI', 'ASMARA', 'BARENTU', 'BEYLUL', 'ED', 'MERSA FATMA']
    
    ERMENISTAN = ['ERIVAN', 'GYUMRI', 'VANADZOR']
    
    ESTONYA = ['JOGEVA', 'KURESSAARE', 'PARNU', 'POLVA', 'RAKVERE', 'TALLINN', 'TAPA', 'TARTU', 'VILJANDI', 'VORU']
    
    ETYOPYA = ['ADIS ABABA', 'BAHIR DAR', 'DESE', 'DIRE DAWA', 'GONDER', 'HARER', 'JIMA', 'MEKELE']
    
    FAS = ['AGADIR', 'BENI MELLAL', 'FEZ', 'KASABLANKA', 'KENITRA', 'KHOURIBGA', 'MARAKES', 'MEKNES', 'MOHAMMEDIA', 'OUJDA', 'RABAT', 'SAFI', 'SALE', 'SETTAT', 'TANGIER', 'TETOUAN']
    
    FIJI = ['LAUTOKA', 'LEVUKA', 'SUVA']
    
    FILDISI_SAHILI = ['ABIDJAN', 'BOUAKE', 'DALOA', 'KORHOGO', 'YAMOUSSOUKRO']
    
    FILIPINLER = ['ANGELES', 'BACALOD', 'BAGUIO', 'BATANGAS', 'BINAN', 'BUTUAN', 'CABANATUAN', 'CAGAYAN DE ORO', 'CALBAYOG', 'CEBU', 'COTABATO', 'DAGUPAN', 'DAVAO', 'GENERAL SANTOS', 'ILOILO', 'LAOAG', 'LAPU-LAPU', 'LEGASPI', 'LIPA', 'LUCENA', 'MALOLOS', 'MANILA', 'MUNTINGLUPA', 'NAGA CITY', 'OLONGAPO', 'ORMOC', 'PAGADIAN', 'ROXAS', 'SAN CARLOS', 'SAN FERNANDO', 'SAN JOSE DEL MONTE', 'SAN PABLO', 'SAN PEDRO', 'TACLOBAN', 'TARLAC', 'ZAMBOANGA CITY']
    
    FINLANDIYA = ['ESPOO', 'HAMEENLINNA', 'HELSINKI', 'HYVINKAA', 'IISALMI', 'IMATRA', 'JARVENPAA', 'JOENSUU', 'JYVASKYLA(YVSK)', 'KAAJANI', 'KANGASNIEMI', 'KARKKILA', 'KEMI', 'KERAVA', 'KOKKOLA', 'KOTKA', 'KOUVOLA', 'KUOPIO', 'LAHTI', 'LAPPEENRANTA', 'LOHJA', 'MARIEHAMN', 'MIKKELI', 'NOKIA', 'OULU', 'PARIKKALA', 'PORI', 'PORVOO', 'RAAHE', 'RAUMA', 'RIIHIMAKI', 'ROVANIEMI', 'SALO', 'SEINAJOKI', 'TAMPERE', 'TORNIO', 'TURKU', 'VAASA', 'VALKEAKOSKI', 'VANTAA', 'VARKAUS']
    
    FRANSA = ['ABBEVILLE', 'AIX-EN-PROVENCE', 'ALBI', 'ALENCON', 'AMIENS', 'ANGERS', 'ANGLET', 'ANGOULEME', 'ANNECY', 'ANNEMASSE', 'ANTIBES', 'ARLES', 'AUXERRE', 'AVIGNON', 'BAR-LE-DUC', 'BAYONNE', 'BEAUNE', 'BEAUVAIS', 'BELFORT', 'BELLEGARDE', 'BESANCON', 'BEZIERS', 'BIARRITZ', 'BISCHWILLER', 'BITCHE', 'BLOIS', 'BORDEAUX', 'BOURG EN BRESSE', 'BOURGES', 'BOURGOIN JAILLEU', 'BOUZONVILLE', 'BREST', 'BRIGNOLES', 'CAEN', 'CALAIS', 'CAMBRAI', 'CANNES', 'CARCASSONNE', 'CASTRES (TARN)', 'CERGY', 'CHALONS-EN-CHAMPAGNE', 'CHAMBERY', 'CHARLEVILLE-MEZIERES', 'CHATEAUBRIANT', 'CHATEAUROUX', 'CLERMONT-FERRAND', 'CLICHY S/BOIS', 'CLUSES', 'COLMAR', 'COMPIEGNE', 'CREIL', 'CREPY EN VALOIS', 'DIJON', 'DOUAI', 'ELANCOURT', 'EPERNAY', 'EPINAL', 'ESPALION', 'FAMECK', 'FONTAINEBLEAU', 'FORBACH', 'FREJUS', 'GAP', 'GIEN', 'GOUSSAINVILLE', 'GRENOBLE', 'HENIN-BEAUMONT', 'HYERES', 'LA ROCHELLE', 'LA TESTE-DE-RUCH', 'LA VERPILLIERE', 'LAIGLE', 'LANGRES', 'LE CREUSOT', 'LE HAVRE', 'LE MANS', 'LE PEAGE DE ROUSSILLION', 'LENS', 'LILLE', 'LIMOGES', 'LORIENT', 'LUNEVILLE', 'LYON', 'MACON', 'MANTES LA JOLIE', 'MARIGNANE', 'MARSEILLE', 'MARTIGUES', 'MEAUX', 'MENTON', 'METZ', 'MOLSHEIM', 'MONSOLS', 'MONTARGIS', 'MONTBELIARD', 'MONTELIMAR', 'MONTEREAU', 'MONTPELLIER', 'MOREZ', 'MULHOUSE', 'NANCY', 'NANTES', 'NANTUA', 'NARBONNE', 'NEVERS', 'NICE', 'NIMES', 'OBERNAI', 'ORANGE', 'ORLEANS', 'OYONNAX', 'PARIS', 'PAU', 'PERPIGNAN', 'POITIERS', 'PONT A MOUSSON', 'PONTARLIER', 'PONTOISE', 'PROVINS', 'QUIMPER', 'RAON-L ETAPE', 'REIMS', 'RENNES', 'RODEZ', 'ROUEN', 'SAINT MALO', 'SAINT-DIZIER', 'SAINT-NAZAIRE', 'SALLANCHES', 'SAVERNE', 'SELESTAT', 'SENS', 'ST. AFFRIQUE', 'St. DIE', 'St. ETIENNE', "ST.-RAMBERT-D'ALBON", 'STRASBOURG', 'TANINGES', 'THIERS', 'TOULON', 'TOULOUSE', 'TOURS', 'TREVOUX', 'TROYES', 'VALABRES', 'VALENCE(DROME)', 'VANNES', 'VERSAILES', 'VICHY', 'VIERZON', 'WISSEMBOURG']
    
    GABON = ['LIBREVILLE', 'MAKOKOU', 'OYEM', 'PORT GENTIL', 'TCHIBANGA']
    
    GAMBIYA = ['BANJUL', 'SERROKUNDA']
    
    GANA = ['ACCRA', 'BOLGATANGA', 'CAPE COAST', 'KOFORIDUA', 'KUMASI', 'SEKONDI', 'TAKORADI', 'TAMALE', 'TEMA']
    
    GINE = ['CONAKRY', 'KANKAN', 'KINDIA', 'LABE', 'NZEREKORE']
    
    GRANADA = ['SAINT GEORGES']
    
    GRONLAND = ['NUUK']
    
    GUADELOPE = ['BASSE-TERRE', 'PONTE-A-PITRE']
    
    GUAM_ADASI = ['AGANA']
    
    GUATEMALA = ['CHIQUIMULA', 'COBAN', 'ESCUINTLA', 'GUATEMALA CITY', 'HUEHUETENANGO', 'JALAPA', 'MIXCO', 'PUERTO BARRIOS', 'QUEZALTENANGO', 'SAN PEDRO CARCHA', 'VILLA NUEVA', 'ZACAPA']
    
    GUNEY_AFRIKA = ['ALEXANDRA', 'BLOEMPONTEIN', 'BOKSBURG', 'CAPE TOWN', 'DURBAN', 'EAST LONDON', 'GEORGE', 'GERMISTON', 'JOHANNESBURG', 'KEMPTON PARK', 'KIMBERLEY', 'KLERKSDORP', 'KURUMAN', 'MABULA', 'MDANTSANE', 'NELSPRUIT', 'NEWCASTLE', 'PAROW', 'PIETERMARITZBURG', 'PORT ELIZABETH', 'PRETORIA', 'ROODE POORT', 'SOWETO', 'SPRINGS', 'STELLENBOSCH', 'ULUNDI', 'UMLAZI', 'UPINGTON', 'VEREENIGING', 'WELKOM', 'WORCESTER']
    
    GUNEY_KORE = ['ANDONG-SI', 'ANSAN', 'ANYANG', 'BUCHEON', 'CHANGWON', 'CHEONGJU', 'CHUNGJU', 'DAEGU', 'DAEJEON', 'GANGNEUNG', 'GIMHAE', 'GIMJE', 'GOHEUNG', "GUNP'O", 'GUNSAN', 'GWANGJU', 'GYEONGJU', 'IKSAN', 'INCHEON', 'JEJU', 'JEON JU', 'JINHAE', 'JINJU', 'MASAN', 'MIRYANG', 'MOKPO', 'NAJU', 'PAJU', 'POCHEON', 'POHANG', 'PUSAN', 'SEONGNAM', 'SEUL', 'SUNCHEON', 'SUWON', 'UIJEONGBU', 'ULSAN', 'WONJU', 'YEOSU', 'YONGIN']
    
    GURCISTAN = ['BATUM', 'CHALA', 'GAGRA', 'GALI', 'KEDA', 'KOBULETI', 'KUTAISI', 'POTI', 'RUSTAVI', 'SOKHUMI', "T'ELAVI", 'TIFLIS', 'TSKHINVALI']
    
    GUYANA = ['GEORGETOWN', 'LINDEN', 'NEW AMSTERDAM']
    
    HAITI = ['CAP-HAITEN', 'CARREFOUR', 'DELMAS', 'GONAIVES', 'LES CAYES', 'PORT -AU -PRINCE']
    
    HINDISTAN = ['ADILABAD', 'AGRA', 'AHMEDABAD', 'AHMEDNAGAR', 'AKOLA', 'AMBALA', 'AMRAVATI', 'AMRITSAR', 'BALESHWAR', 'BANGALORE', 'BARDDHAMAN', 'BARIPADA', 'BELGAUM', 'BHAVANI', 'BHILAI', 'BHIWANDI', 'BHOPAL', 'BHUBANESHWAR', 'BHUJ', 'BILASPUR', 'BOMBAY', 'CALCUTTA', 'CALICUT', 'CHANDIGARH', 'CHENNAI', 'CHHATARPUR', 'CHHINDWARA', 'COCHIN', 'COIMBATORE', 'CUDDALORE', 'CUTTACK', 'DEHRA DUN', 'DIBRUGARH', 'DURG', 'DURGAPUR', 'ERODE', 'FAIZABAD', 'GANDHINAGAR (GUJARAT)', 'GAUHATI', 'GONDIA', 'GULBARGA', 'GUNTUR', 'GURGAON', 'GUWAHATI', 'GWALIOR', 'HALDIA', 'HISAR', 'HOSHIARPUR', 'HYDERABAD', 'ICHALKARANJI', 'IMPHAL', 'INDORE', 'JABALPUR', 'JAIPUR', 'JALANDHAR ( JULLUNDUR )', 'JALGAON (MAHARASTITRA)', 'JAMMU', 'JAMSHEDPUR', 'JORHAT', 'KAKINADA', 'KALOL', 'KALYAN', 'KANPUR', 'KHARAGPUR (WEST BENGAL)', 'KOLHAPUR', 'KORBA', 'KOTTAYAM', 'KUMBAKANOM', 'LUCKNOW', 'LUDHIANA', 'MADURAI', 'MALAPPURAM', 'MANDYA', 'MANGALORE', 'MEERUT', 'MIRAJ', 'MYSORE', 'NAGPUR', 'NALGONDA', 'NELLORE', 'PATNA', 'PIMPRI', 'PONDICHERRY', 'PORT BLAIR', 'PUNE', 'RAIGARH', 'RAIPUR', 'RAJAPALAIYAM', 'RAJKOT', 'RANCHI', 'RAURKELA', 'SALEM', 'SAMBALPUR', 'SANGLI', 'SECUNDERABAD', 'SHOLAPUR', 'SIVAKASI', 'SRINAGAR', 'TENALI', 'THANE', 'THANJAVUR', 'TIRUCHIRAPPALLI', 'TIRUNELVELI', 'TIRUPPUR', 'TRIVANDRUM', 'UDAIPUR', 'UNNAO', 'VADODARA', 'VASAI', 'VIJAYAWADA', 'VISHAKHAPATNAM', 'WARDHA', 'YAVATMAL', 'YENI DELHI']
    
    HIRVATISTAN = ['BASKA', 'BJELOVAR', 'DARUVAR', 'DUBROVNIK', 'GRACAC', 'KARLOVAC', 'KOPRIVNICA', 'KRIZEVCI', 'OGULIN', 'OSIJEK', 'OTOCAC', 'POZEGA', 'PULA', 'RIJEKA', 'SENJ', 'SISAK', 'SLAVONSKI BROD', 'SLUNT', 'SPLIT', 'VARAZDIN', 'ZADAR', 'ZAGREB']
    
    HOLLANDA = ['AALSMEER', 'ALKMAAR', 'ALMELO', 'ALMERE-HAVEN', 'ALMERE-STAD', 'ALPHEN AAN DEN RIJN', 'AMERSFOORT', 'AMSTERDAM', 'APELDOORN', 'ARNHEM', 'ASSEN', 'BAARN', 'BARNEVELD', 'BERGEN OP ZOOM', 'BEVERWIJK', 'BILTHOVEN', 'BOXTEL', 'BREDA', 'CAPELLE AAN DEN LJSSEL', 'CASTRICUM', 'CULEMBORG', 'DE BILT', 'DELFT', 'DEN HAAG', 'DEN HELDER', 'DEVENTER', 'DOETINCHEM', 'DONGEN', 'DORDRECHT', 'DRACHTEN', 'DRONTEN', 'EDE', 'EERBEEK', 'EINDHOVEN', 'EMMELOORD', 'EMMEN', 'ENKHUIZEN', 'ENSCHEDE', 'GELEEN', 'GOES', 'GORINCHEM', 'GOUDA', 'GRONINGEN', 'HAARLEM', 'HARDERWIJK', 'HEEMSKERK', 'HEEMSTEDE', 'HEERENVEEN', 'HEERHUGOWAARD', 'HEERLEN', 'HELMOND', 'HENGELO (overijssel)', 'HILLEGOM', 'HILVERSUM', 'HOOFDDORP', 'HOOGEVEEN', 'HOORN', 'HUIZEN', 'KAMPEN', 'KATWIJK AAN DE RIJN', 'LEERDAM', 'LEEUWARDEN', 'LEIDEN', 'LEIDERDORP', 'LEIDSCHENDAM', 'LELYSTAD', 'LISSE', 'LOERBEEK', 'MAASSLUIS', 'MAASTRICHT', 'MEPPEL', 'MIDDELBURG', 'NAALDWIJK', 'NIEUWEGEIN', 'NIJMEGEN', 'OLDENZAAL', 'OOSTERHOUT', 'OSS', 'PAPENDRECHT', 'PURMEREND', 'RAALTE', 'RIJSSEN', 'ROERMOND', 'ROOSENDAAL', 'ROSMALEN', 'ROTTERDAM', 'SCHIEDAM', 'S-HERTOGENBOSCH', 'SITTARD', 'SLIEDRECHT', 'SNEEK', 'SOEST', 'SPIJKENISSE', 'STADSKANAAL', 'STEENWIJK', 'STEIN', 'TERNEUZEN', 'THE HAGUE', 'TIEL', 'TILBURG', 'UDEN', 'UTRECHT', 'VALKENSWAARD', 'VEENENDAAL', 'VELDHOVEN', 'VENLO', 'VENRAY', 'VLAARDINGEN', 'VLISSINGEN', 'VOORBURG', 'WAALWIJK', 'WAGENINGEN', 'WEERT', 'WINTERSWIJK', 'WOERDEN', 'ZAANDAM', 'ZEIST', 'ZEVENAAR', 'ZOETERMEER', 'ZUTPHEN', 'ZWOLLE']
    
    HOLLANDA_ANTILLERI = ['WILLEMSTAD']
    
    HONDURAS = ['CHOLUTECA', 'COMAYAGUA', 'DANLI', 'EL PROGRESO', 'GRACIAS', 'JUTICALPA', 'LA CEIBA', 'LA PAZ', 'PUERTO CORTES', 'PUERTO LEMPIRA', 'SAN PEDRO SULA', 'SANTA BARBARA', 'SANTA ROSA DE COPAN', 'TEGUCIGALPA', 'TELA', 'TRUJILLO', 'YORO']
    
    HONG_KONG = ['ABERDEEN', 'HONG KONG', 'KOWLOON', 'LAMMA ADASI', 'VICTORIA']
    
    INGILTERE = ['ABERDEEN', 'ASHFORD', 'BANBURY', 'BANGOR', 'BARNSLEY', 'BASILDON', 'BATH', 'BEDFORD', 'BELFAST', 'BIRMINGHAM', 'BLACKBURN', 'BLACKPOOL', 'BOURNEMOUTH', 'BRADFORD', 'BRIDGWATER', 'BRIDLINGTON', 'BRIGHTON', 'BRISTOL', 'CAMBRIDGE', 'CANTERBURY', 'CARDIFF', 'CARLISLE', 'CHELMSFORD', 'CHELTENHAM', 'CHESTER', 'CHICHESTER', 'COLCHESTER', 'COVENTRY', 'DARLINGTON', 'DERBY', 'DONCASTER', 'DOVER', 'DUDLEY', 'DUNDEE', 'DURHAM', 'EASTBOURNE', 'EDINBURGH', 'EPSOM', 'EXETER', 'FOLKESTONE', 'GIBRALTAR', 'GLASGOW', 'GLOUCESTER', 'GRANTHAM', 'GUILDFORD', 'HARROGATE', 'HENLEY ON THEM.', 'HENLOW', 'HORSHAM', 'HUDDERSFIELD', 'HULL', 'IPSWICH', 'LANCASTER', 'LEEDS', 'LEICESTER', 'LIVERPOOL', 'LONDONDERRY', 'LONDRA', 'LOWESTOFT', 'LUTON', 'MAIDSTONE', 'MANCHESTER', 'MARGATE', 'MARKETHARBOROUGH', 'MIDDLESBROUGH', 'MILTON KEYNES', 'NEWCASTLEUPNT.', 'NEWPORT', 'NORTHAMPTON', 'NORWICH', 'NOTTINGHAM', 'OXFORD', 'PENZANCE', 'PETERBOROUGH', 'PLYMMOUTH', 'POOLE', 'PORTSMOUTH', 'POYNTON', 'PRESTON', 'RAMSGATE', 'READING', 'ROTTERHAM', 'SALISBURY', 'SCARBOROUGH', 'SHEFFIELD', 'SOLIHULL', 'SOUTHAMPTON', 'SOUTHEND-ON SEA', 'ST. HELENS', 'STAFFORD', 'STOCKPORT', 'STOKE ON TRENT', 'STRATFORD-UPON-AVON', 'STROUD', 'SUNDERLAND', 'SWANSEA', 'SWINDON', 'TAMWORTH', 'TORQUAY', 'TUNBRIDGE WELS', 'TWICKENHAM', 'WAKEFIELD', 'WALLINGFORD', 'WARRINGTON', 'WARWICK', 'WELLS', 'WILMSLOW', 'WIMBLEDON', 'WINCHESTER', 'WOLVERHAMPTON', 'WORTHING', 'YEOVIL', 'YORK']
    
    IRAK = ['AL AMARAH', 'AL HILLAH', 'AL KUT', 'AN NAJAF', 'AN NASIRIYAH', 'AR RAMADI', 'BAGDAT', 'BAQUBAH', 'BASRA', 'ERBIL', 'KERBELA', 'KERKUK', 'MUSUL', 'SAMARRA', 'SULEYMANIYE']
    
    IRAN = ['AHVAZ', 'AMOL', 'ARAK', 'ARDABIL', 'BABOL', 'BOJNURD', 'BORUJERD', 'DEZFUL', 'GORGAN', 'HAMADAN', 'HURREMABAD', 'ILAM', 'ISFEHAN', 'KARAJ', 'KERMAN', 'KERMANSHAH', 'KHVOY', 'MALAYER', 'MARAGHEH', 'MASHHAD', 'QAEMSHAHR', 'QAZVIN', 'RAJAISHAHR', 'RASHT', 'REZAIYEH', 'SANANDAJ', 'SHIRAZ', 'TABRIZ', 'TAHRAN', 'URMIA', 'YAZD', 'ZAHEDAN', 'ZANJAN']
    
    IRLANDA = ['ATHLONE', 'CARLOW', 'CORK', 'DUBLIN', 'DUNDALK', 'GALWAY', 'LIMERIC', 'TRALEE']
    
    ISPANYA = ['ALBACETE', 'ALCALA DE HENR.', 'ALGECIRAS', 'ALICANTE', 'ALMERIA', 'ARRECIFE', 'BADAJOZ', 'BARCELONA', 'BILBAO', 'BURGOS', 'CADIZ', 'CARTAGENA', 'CASTELLON DE LA PLANA', 'CEUTA', 'CIUDADELA', 'CORDOBA', 'ELCHE', 'GIJON', 'GRANADA', 'HUELVA', 'IBIZA', 'JAEN', 'JEREZ DE LA FRONTERA', 'LA CORUNA', 'LA LAGUNA', 'LAS PALMAS', 'LEON', 'LLEIDA', 'LOGRONO', 'MADRID', 'MALAGA', 'MARBELLA', 'MURCIA', 'ORENSE', 'OVIEDO', 'PALMA DE MALLARCO', 'PAMPLONA', 'SALAMANCA', 'SAN ANTONIO ABAD', 'SAN CRISTOBAL DE LA LAGUNA', 'SAN SEBASTIAN', 'SANTA CRUZ DE TENERIFE', 'SANTANDER', 'SANTIAGO DE CO.', 'SEVILLE', 'TARRAGONA', 'TOLEDO', 'VALENCIA', 'VALLADOLID', 'VIGO', 'VITORIA', 'ZARAGOZA']
    
    ISRAIL = ['ASHDOD', 'BEERSHEBA', 'HAIFA', 'HEBRON (W.B.)', 'NABULUS (W.B.)', 'NAZARETH', 'NETANYA', 'RISHON LE ZIYYON', 'TEL AVIV']
    
    ISVEC = ['ALINGSAS', 'ANGELHOLM', 'ARVIKA', 'AVESTA', 'BODEN', 'BORAS', 'BORLANGE', 'BOTKYRKA', 'ENKOPING', 'ESKILSTUNA', 'ESLOV', 'FALKENBERG', 'FALUN', 'FINSPANG', 'GALLIVARE', 'GAVLE', 'GISLAVED', 'GOTEBORG', 'HALMSTAD', 'HARNOSAND', 'HASSLEHOLM', 'HELSINGBORG', 'HOGANAS', 'HUDIKSVALL', 'JONKOPING', 'KALMAR', 'KARLSHAMM', 'KARLSKOGA', 'KARLSKRONA', 'KARLSTAD', 'KATRINEHOLM', 'KIRUNA', 'KRAMFORS', 'KRISTIANSTAD', 'KRISTINEHAMN', 'KUNGALV', 'KUNGSBACKA', 'LAHOLM', 'LANDSKRONA', 'LIDKOPING', 'LINDESBERG', 'LINKOPING', 'LJUNGBY', 'LJUSDAL', 'LUDVIKA', 'LULEA', 'LUND', 'LYSEKIL', 'MALMO', 'MARIESTAD', 'MARSTA', 'MJOLBY', 'MORA', 'MOTALA', 'NASSJO', 'NORRKOPING', 'NORRTALJE', 'NYKOPING', 'NYNASHAMN', 'OREBRO', 'OSKARSHAMN', 'OSTERSUND', 'PITEA', 'RONNEBY', 'SALA', 'SANDVIKEN', 'SIGTUNA', 'SIMRIS', 'SKARA', 'SKOVDE', 'SODERHAMN', 'SODERTALJE', 'SOLLEFTEA', 'SOLVESBORG', 'STOCKHOLM', 'STRANGNAS', 'SUNDSVALL', 'TIERP', 'TRELLEBORG', 'TROLLHATTAN', 'UDDEVALLA', 'ULRICEHAMN', 'UMEA', 'UPPSALA', 'VANERSBORG', 'VARBERG', 'VARNAMO', 'VASTERAS', 'VASTERVIK', 'VAXJO', 'VETLANDA', 'VISBY', 'YSTAD']
    
    ISVICRE = ['AARAU', 'BAAR', 'BASEL', 'BERN', 'BIEL', 'CENEVRE', 'CHUR', 'DAVOS', 'FLUMS', 'FRAUENFELD', 'FRIBOURG', 'LA CHAUX DE FONDS', 'LIESTAL', 'LOZAN', 'LUCERNE', 'LUGANO', 'MARTIGNY', 'MELS', 'MONTHEY', 'MONTREUX', 'NEUCHATEL', 'OLTEN', 'SANKT GALLEN', 'SARGANS', 'SCHAFFHAUSEN', 'SIERRE', 'SION', 'SOLOTHURN', 'ST. MORITZ', 'THUN', 'WINTERTHUR', 'YVERDON LES BAINS', 'ZUG', 'ZURIH']
    
    ITALYA = ['ACQUI TERME', 'AGRIGENTO', 'ALBA', 'ALBENGA', 'ALGHERO', 'ANCONA', 'AOSTA', 'AREZZO', 'AUGUSTA', 'AVELLINO', 'BARI', 'BASSANO DEL GRAPPA', 'BELLUNO', 'BERGAMO', 'BIELLA', 'BOLOGNA', 'BOLZANO BOZEN', 'BRESCIA', 'CAGLIARI', 'CALTANISSETTA', 'CAMPOBASSO', 'CASERTA', 'CASTELFRANCO VENETO', 'CASTELVETRANO', 'CATANIA', 'CATANZARO', 'CECINA', 'CESENA', 'CHIETI', 'CIVITAVECCHIA', 'COMERIO', 'COMO', 'CONEGLIANO', 'CONVERSANO', 'COSENZA', 'CREMONA', 'CROTONE', 'CUNEO', 'ENNA', 'FABRIANO', 'FERMO', 'FERRARA', 'FLORENCE', 'FOGGIA', 'FOLIGNO', 'FOLLONICA', 'FORLI', 'FROSINONE', 'GAETA', 'GENOVA', 'GHEDI', 'GROSSETO', 'IMOLA', 'IMPERIA', 'IVREA', 'JESI', 'LA SPEZIA', "L'AQUILA", 'LATINA', 'LECCE', 'LECCO', 'LIVORNO', 'LUCCA', 'MACERATA', 'MANTUA', 'MASSA', 'MATERA', 'MERANO', 'MESSINA', 'MILANO', 'MILAZZO', 'MODENA', 'MONOPOLI', 'MURAVERA', 'NAPOLI', 'NOVARA', 'NUORO', 'OLBIA', 'ORISTANO', 'OSIMO', 'PADOVA', 'PALERMO', 'PARMA', 'PERUGIA', 'PESARO', 'PESCARA', 'PIACENZA', 'PINEROLO', 'PISA', 'PORDENONE', 'POTENZA', 'PUTIGNANO', 'RAVENNA', 'REGGIO DI CALABRIA', 'REGGIO EMILIA', 'RIBERA', 'RIETI', 'RIMINI', 'ROMA', 'ROVIGO', 'SALERNO', 'SAN BENEDETTO DEL TRONTO', 'SAN REMO', 'SASSARI', 'SAVONA', 'SESTRI LEVANTE', 'SIENA', 'SONDRIO', 'SPOLETO', 'SYRACUSE', 'TARANTO', 'TERNI', 'TORINO', 'TRAPANI', 'TRENTO', 'TREVISO', 'TRIESTE', 'UDINE', 'VALENZA', 'VARESE', 'VENEDIK', 'VERBANIA', 'VERONA', 'VIAREGGIO', 'VIBO VALENTIA', 'VICENZA', 'VILLAPUTZU', 'VITERBO', 'VOGHERA']
    
    IZLANDA = ['REYKJAVIK']
    
    JAMAIKA = ['KINGSTON', 'MANDEVILLE', 'MONTEGO BAY', 'SPANISH TOWN']
    
    JAPONYA = ['ABIKO', 'AIZUWAKAMATSU', 'AKASHI', 'AKITA', 'ANJO', 'AOMORI', 'ASAHIKAWA', 'ASHIKAGA', 'ATSUGI', 'BEPPU', 'CHIBA', 'EBETSU', 'FUJI', 'FUJIEDA', 'FUJINOMIYA', 'FUJISAWA', 'FUKAYA', 'FUKUE', 'FUKUI', 'FUKUOKA', 'FUKUSHIMA', 'GIFU', 'HACHIOJI', 'HADANO', 'HAKODATE', 'HAMAMATSU', 'HANDA', 'HIGASHIMURAYAMA', 'HIGASHIOSAKA', 'HIKONE', 'HIMERJI', 'HINO', 'HIRARA', 'HIRATSUKA', 'HIROSIMA', 'HITACHI', 'ICHIHARA', 'IMABARI', 'ISESAKI', 'IWAKUNI', 'KAGOSHIMA', 'KANAZAWA', 'KASHIWA', 'KASHIWAZAKI', 'KASUGAI', 'KAWAGOE', 'KAWASAKI', 'KIRYU', 'KISARAZU', 'KITAKYUSHU', 'KOBE', 'KOCHI', 'KOFU', 'KOMAKI', 'KOMATSU', 'KUMAGAYA', 'KUMAMOTO', 'KURASHIKI', 'KURE', 'KURUME', 'KUSATSU', 'KUSHIRO', 'KYOTO', 'MAEBASHI', 'MATSUE', 'MATSUMOTO', 'MATSUYAMA', 'MISHIMA', 'MITO', 'MIYAZAKI', 'MORIOKA', 'NAGANO', 'NAGAOKA', 'NAGAREYAMA', 'NAGASAKI', 'NAGATA-KU', 'NAGOYA', 'NAHA', 'NAZE', 'NIIGATA', 'NOBEOKA', 'NUMAZU', 'OBIHIRO', 'ODAWARA', 'OITA', 'OKAYAMA', 'OKAZAKI', 'OKINAWA', 'OMUTA', 'OSAKA', 'OSAKA(gifu)', 'OTA (gunma-ken)', 'OYAMA', 'SAITAMA', 'SANDA', 'SAPPORO', 'SASEBO', 'SAYAMA', 'SENDAI', 'SHIZUKI', 'SHIZUOKA', 'SOKA', 'SUZUKA', 'TACHIKAWA', 'TAJIMI', 'TAKAMATSU', 'TAKAOKA', 'TAKASAKI', 'TAMA', 'TEINE-KU', 'TOKOROZAWA', 'TOKUSHIMA', 'TOKYO', 'TOTTORI', 'TOYAKAWA', 'TOYAMA', 'TOYOHASHI', 'TOYOTA (AICHI)', 'TSUKUBA', 'TSURUOKA', 'URASOE', 'UTSUNOMIYA', 'WAKAYAMA', 'YAIZU', 'YAMAGUCHI', 'YAO', 'YOKKAICHI', 'YOKOHOMA', 'YOKOSUKA']
    
    KAMBOCYA = ['BATTAMBANG', 'KAMPONG CHAM', 'KAMPOT', 'KRACHEH', 'PHNOM PENH', 'POUTHISAT', 'PREY VENG', 'SIEM REAB']
    
    KAMERUN = ['BAFOUSSAM', 'BAMENDA', 'DOUALA', 'GAROUA', 'LIMBE', 'MAROUA', 'NKONGSAMBA', 'YAOUNDE']
    
    KANADA = ['ABBOTSFORD', 'BANFF', 'BARRIE', 'BRAMPTON', 'BURLINGTON', 'BURNABY', 'CALGARY', 'CAMBRIDGE', 'CHARLOTTETOWN', 'CHATHAM', 'COQUITLAM', 'EDMONTON', 'FREDERICTON', 'GATINEAU', 'GUELPH', 'HALIFAX', 'HAMILTON', 'HARRISON ISLAND', 'HEBRON', 'IQALUIT', 'JASPER', 'KAMLOOPS', 'KINGSTON', 'KITCHENER', 'LAVAL', 'LONDON', 'LONGUEUIL', 'LOUISE ADASI', 'MARKHAM', 'MISSISSAUGA', 'MONCTON', 'MONTREAL', 'NANAIMO', 'OAKVILLE', 'OSHAWA', 'OTTAVA', 'OWEN SOUND', 'QUEBECK', 'REGINA', 'RICHMOND', 'RICHMOND HILL', 'RIMOUSKI', 'SAANICH', 'SAINT JOHN', 'SEPT-ILES', 'SHERBROOKE', 'ST. CATHARINES', 'SUDBURY', 'SURREY', 'SYDNEY', 'THUNDER BAY', 'TORONTO', 'VANCOUVER', 'VAUGHAN', 'VICTORIA', 'WINDSOR', 'WINNIPEG']
    
    KARADAG = ['BIJELD POLJE', 'GUSINJE', 'NIKSI', 'PLJEVLJA', 'PODGORICA', 'ULCINJ']
    
    KATAR = ['AR RAYYAN', 'DOHA', 'DUKHAN']
    
    KAZAKISTAN = ['AKMOLA (ASTANA)', 'AKTAU (TUPQARAKHAN)', 'AKTEPE (aktyubinsk)', 'ALMATI', 'ARQALYK', 'ATRAU', 'BAUTINO', 'CIMKENT', 'DZHAMBUL', 'DZHEZKAZGAN', 'EKIBASTUZ', 'FORT SHEVCHENKO', 'GURYEV', 'KARAGANDA', 'KENTAU', 'KHROMKAU', 'KOKCHETAV', 'KOSCHAGYL', 'KUSTANAY', 'KYZYK', 'KYZYLORDA', 'OSKEMEN', 'PAVLODAR', 'PETROPAVLOVSK', 'RUDNYY', 'SEMEY', 'TALDY KURGAN', 'TARAZ', 'TERENOZEK', 'TOLGAR', 'TURKISTAN', 'URALSK']
    
    KENYA = ['ELDORET', 'KISUMU', 'MACHAKOS', 'MOMBASA', 'NAIROBI', 'NAKURU']
    
    KIRGIZISTAN = ['BATKEN', 'BISKEK', 'CELALABAD', 'KARA-BALTA', 'KARAKOL', 'KOCHKORKA', 'NARYN', 'OSH', "RYBACH'YE", 'TALAS', 'TOKMOK']
    
    KOLOMBIYA = ['ARAUCA', 'ARMENIA', 'BARRANCABERMEJA', 'BARRANQUILLA', 'BOGOTA', 'BUCARAMANGA', 'BUGA', 'CALI', 'CARTAGENA', 'CARTAGO', 'CIENAGA', 'CUCUTA', 'DOSQUEBRADAS', 'ENVIGADO', 'FLORENCIA', 'FLORIDABLANCE', 'IBAGUE', 'ITAGUI', 'LETICIA', 'MANIZALES', 'MEDELLIN', 'MONTERIA', 'NEIVA ( ARAUCA )', 'NEIVA ( HUILA )', 'PALMIRA', 'PASTO', 'PEREIRA', 'POPAYAN', 'QUIBDO', 'RIOHACHA', 'SAN ANDRES', 'SANTA MARTA', 'SINCELEJO', 'SOACHA', 'SOGAMOSO', 'SOLEDAD', 'TUNJA', 'VALLEDUPAR ( CESAR )', 'VILLAVIVICENCIO', 'YOPAL']
    
    KOMORLAR = ['MORONI']
    
    KONGO = ['BOMA', 'BRAZZAVILLE', 'BUKAVU', 'GOMA', 'KANANGA', 'KIKWIT', 'KINSHASA', 'KISANGANI', 'KOLWEZU', 'LIKASI', 'LUBUMBASHI', 'MATADI', 'MBANDAKA', 'MBUJI-MAYI', 'POINTE NOIRE', 'TSHIKAPA']
    
    KOSOVA = ['KOSOVSKA MITROVICA', 'PRISTINA', 'PRIZREN']
    
    KOSTARIKA = ['ALAJUELA', 'CARTAGO', 'HEREDIA', 'LIBERIA', 'LIMON', 'SAN JOSE']
    
    KUBA = ['BAYAMO', 'CAMAGUEY', 'CIEGO DE AVILA', 'CIENFUEGOS', 'GUANTANAMO', 'HAVANA', 'HOLGUIN', 'LAS TUNAS', 'MANZANILLO', 'MATANZAS', 'NUEVA GERONA', 'PINAR DEL RIO', 'SANTA CLARA', 'SANTIAGO DE CUBA']
    
    KUDUS = ['KUDUS']
    
    KUVEYT = ['JAHRA', 'JALIB ASH SHUYUKH', 'KUVEYT', 'SALMIYA (AS SALIMIYAH)']
    
    KUZEY_KIBRIS = ['GAZI MAGOSA', 'GIRNE', 'ISKELE', 'LEFKE', 'LEFKOSE']
    
    KUZEY_KORE = ['PYONGYANG']
    
    LAOS = ['BAN DONKON', 'LOUANG NAMTHA', 'MUANG SING', 'MUANG VANGVIANG', 'SARAVAN', 'VIENTIANE', 'XAM NUA']
    
    LESOTO = ['MASERU']
    
    LETONYA = ['DAUGAVPILS', 'JELGAVA', 'LIEPAJA', 'OGRE', 'RIGA', 'RUJIENA', 'TUKUMS', 'VALDEMARPILS', 'VENTSPILS']
    
    LIBERYA = ['BUCHANAN', 'MONROVIA']
    
    LIBYA = ['AL BAYDA', 'AL KHUMS', 'AWBARI', 'BINGAZI', 'GHAT', 'MISRATAH', 'MURZUQ', 'SABHA', 'TOBRUK', 'TRIPOLI', 'ZUWARAH']
    
    LIECHTENSTEIN = ['VADUZ']
    
    LITVANYA = ['ALYTAUS', 'DRUSKININKAI', 'KAUNAS', 'KLAIPEDA', 'PALANGA', 'SIAULIAI', 'UTENA', 'VILNIUS']
    
    LUBNAN = ['BAALBEK', 'BEYRUT', 'JUNIYAH', 'SAYDA', 'SUR', 'TRABLUSGARP', 'ZAHLAH']
    
    LUKSEMBURG = ['DIEKIRCH', 'ESCH', 'LUKSEMBURG']
    
    MACARISTAN = ['BUDAPESTE', 'DEBRECEN', 'DUNAUJVAROS', 'EGER', 'ESZTERGOM', 'GYOR', 'HODMEZOVASARHELY', 'JASZBERENY', 'KECSKEMET', 'MISKOLC', 'NAGYKOROS', 'NYIREGYHAZA', 'PASZTO NAGYKANIZSA', 'PECS', 'SIOFOK', 'SOPRON', 'SZEGED', 'SZEKESFEHERVAR', 'SZEKSZARD', 'SZOLNOK', 'SZOMBATHELY', 'ZALAEGERSZEG']
    
    MADAGASKAR = ['ANTANANARIVO', 'ANTSIRABE', 'FIANARANTSOA', 'MAHAJANGA', 'TOAMASINA']
    
    MAKAO = ['MAKAO']
    
    MAKEDONYA = ['DEBAR', 'GOSTIVAR', 'KICEVO', 'KUMANOVO', 'MANASTIR(bitola)', 'OHRID', 'PRILEP', 'STIP', 'STRUGA', 'TETOVO', 'TITOV VELES', 'USKUP']
    
    MALAVI = ['BLANTYRE', 'CHITIPA', 'LILONGWE']
    
    MALDIVLER = ['MALE']
    
    MALEZYA = ['ALUR SETAR', 'BATU GAJAH', 'BATU PAHAT', 'GEORGE TOWN', 'IPOH', 'JOHOR BAHARU', 'KANGAR', 'KELANG', 'KELUANG', 'KOTA BAHARU', 'KOTA KINABALU', 'KOTA TINGGI MERSING', 'KUALA LUMPUR', 'KUALA TERENGGANU', 'KUANTAN', 'KUCHING', 'KULIM', 'LABUAN', 'MELAKA', 'MIRI', 'MUAR', 'PENANG', 'SANDAKAN', 'SEGAMAT', 'SEREMBAN', 'SIBU', 'SUNGAI PETANI', 'TAIPING', 'TAWAI', 'TAWAU', 'TELUK INTAN']
    
    MALI = ['BAMAKO', 'GAO', 'SEGOU', 'TOMBOUCTOU']
    
    MALTA = ['BIRKIRKARA', 'SLIEMA', 'VALLETTA', 'VICTORIA']
    
    MARTINIK = ['FORT-DE-FRANCE']
    
    MAURITIUS_ADASI = ['BEAU BASSIN', 'PORT LOUIS']
    
    MAYOTTE = ['MAMOUDZOU']
    
    MEKSIKA = ['ACAMBARO', 'ACAPULCO', 'AGUA PRIETA', 'AGUASCALIENTES', 'ALAMOS', 'ALLENDE', 'APATZINGEN', 'ARANDAS', 'ATLIXCO', 'BOCA DEL RIO', 'CAMPECHE', 'CANCUN', 'CELAYA', 'CHETUMAL', 'CHIHUAHUA', 'CHILPANCINGO', 'CIUDAD ACUNA', 'CIUDAD DEL CARMEN', 'CIUDAD DELICIAS', 'CIUDAD HIDALGO', 'CIUDAD JUAREZ', 'CIUDAD LERDO', 'CIUDAD MADERO', 'CIUDAD OBREGON', 'CIUDAD VALLES', 'CIUDAD VICTORIA', 'COLIMA', 'CORDOBA', 'CUAUTLA', 'CUERNAVACA', 'CULIACAN', 'DURANGO', 'ENSENADA', 'GOMEZ PALACIO', 'GUADALAJARA', 'GUANAJUATA', 'GUAYMAS', 'HERMOSILLO', 'HERQUICA ZTACUARD', 'HIDALGO DEL PARRAL', 'IRAPUATO', 'JALAPA', 'LA PAZ', 'LAGOS DE MORENO', 'LEON', 'LOS MOCHIS', 'MANZANILLO', 'MAZATLAN', 'MERIDA', 'METAMOROS', 'METEPEC', 'MEXICALI', 'MEXICO CITY', 'MONCLOVA', 'MONTERREY', 'MORELIA', 'NAVOJOA', 'NAVOLATO', 'NOGALES', 'NUEVO LAREDO', 'OAXACA', 'ORIZABA', 'PACHUCA', 'PENJAMO', 'PLAYA DEL CARMEN', 'PUEBLA', 'PUERTO VALLARTA', 'QUERATARO', 'REYNOSA', 'SALAMANCA', 'SALTILLO', 'SAN CRISTOBAL DE LAS CASAS', 'SAN JUAN DEL RIO', 'SAN LUIS POTOSI', 'SAN LUIS RIO COLORADO', 'SAN MARTIN TEX. D.L.', 'SAN MIGUEL DE ALLENDE', 'TAMPICO', 'TAXCO', 'TEPATITLAN DE MORE LOS', 'TEPIC', 'TIJUANA', 'TLAJOMULCO DE ZUNIGA', 'TOLUCA', 'TONALA', 'TORREON', 'TULANCINGO', 'TUXTLA GUTIERREZ', 'URUAPAN DEL PROGRESO', 'VALLE DE SANTIAGO', 'VERACRUZ', 'VILLAHERMOSA', 'XALAPA ( JALAPA )', 'ZACATECAS', 'ZAPOPAN']
    
    MIKRONEZYA = ['PALIKIR']
    
    MISIR = ['AL FAYYUM', 'AL GHARDAGAH', 'AL MAHALLAH AL KUBRA', 'AL MANSURAH', 'AL MINYA', 'ASWAN', 'ASYUT', 'AZ ZAQAZIO', 'BANHA', 'BENI SUEF', 'DAMANHUR', 'ISKENDERIYE', 'ISMAILIA', 'KAFR AD DAWWAR', 'KAFR ASH SHAYKH', 'KAHIRE', 'LUXOR', 'PORT SAID', 'QINA', 'SUEZ', 'SUHAJ', 'TANTA']
    
    MOGOLISTAN = ['BAYAN OLGEY', 'DARHAN', 'ERDENET', 'JIBHALANTA', 'JIRGALANT', 'NALAYH', 'OLGIY', 'SUHBAATAR', 'ULAN BATOR']
    
    MOLDAVYA = ['BALTI', 'CHADYR-LUNGA', 'KISHINEV', 'KOMRAT', 'TIGHINA', 'TIRASPOL']
    
    MONAKO = ['MONAKO', 'MONTE KARLO']
    
    MONTSERRAT_UK = ['PLYMOUTH']
    
    MORITANYA = ['FDERIK', 'NOUAKCHOTT']
    
    MOZAMBIK = ['BEIRA', 'CHIMOIO', 'MAPUTO', 'MATOLA', 'NACALA', 'NAMPULA', 'QUELIMANE', 'TETE']
    
    NAMBIYA = ['LUDERITZ', 'ORANJEMUND', 'OSHAKATI', 'OTJIWARONGO', 'WINDHOEK']
    
    NEPAL = ['BHAKTABUR', 'BRATNAGAR', 'BUTWAI', 'DHARAN BAZAR', 'KATHMANDU']
    
    NIJER = ['AGADEZ', 'MARADI', 'NIAMEY', 'TAHOUA', 'TILLABERY', 'ZINDER']
    
    NIJERYA = ['ABA', 'ABUJA', 'AKWA', 'BENIN CITY', 'CALABAR', 'DEBA HABE', 'DOSSO', 'ENUGU', 'GUSAU', 'IBADAN', 'IFE', 'IKIRE', 'IWO', 'KADUNA', 'KANO', 'KATSINA', 'LAFIA', 'LAGOS', 'MAIDUGURI', 'MAKURDI', 'MINNA', 'ONITSHA', 'OSHOGBO', 'PORT HARCOURT', 'SAKI', 'SAPELE', 'SOKOTO', 'TOURBANGUIDA', 'WARRI', 'ZARIA']
    
    NIKARAGUA = ['BLUEFIELDS', 'BOACO', 'CHINANDEGA', 'ESTELI', 'GRANADA', 'JINOTEGA', 'JINOTEPE', 'JUIGALPA', 'LEON', 'MANAGUA', 'MASAYA', 'MATAGALDA', 'OCOTOL', 'PUERTO CABEZAS', 'RIVAS']
    
    NIUE = ['ALOFI']
    
    NORVEC = ['ARENDAL', 'BERGEN', 'BODO', 'DRAMMEN', 'EVENSKJAER', 'FREDRICKSTAD', 'GEILO', 'HAMAR', 'HARSTAD', 'HENNING', 'KIRKENES', 'KRISTIANSAND', 'LILLEHAMMER', 'OSLO', 'ROROS', 'SARPSBORG', 'SKIEN', 'STAVANGER', 'TONSBERG', 'TROMSO', 'TRONDHEIM', 'ULSTEINVIK']
    
    ORTA_AFRIKA_CUMHURIYETI = ['BAMBARI', 'BANGUI', 'BIRAO', 'BOUAR', 'CARNOT', 'DUANDA DJALLE', 'NOLA', 'OBO', 'YALINGA']
    
    OZBEKISTAN = ['ANDIZHAN', 'ANGREN', 'BUHARA', 'CHINAZ', 'CHIRCHIQ', 'FERGANA', 'JIZZAKH', 'KOKAND', 'KUKON', 'MARGHILON', 'NAMANGAN', 'NAWOIY', 'NUKUS', 'OLMALIQ', 'QARSHI', 'SEMERKAND', 'TASKENT', 'TERMEZ', 'URGENC']
    
    PAKISTAN = ['BAHAWALPUR', 'CHINIOT', 'DERA GHAZI KHAN', 'FAISALABAD', 'GUJRANWALA', 'GUJRAT', 'HYDERABAD', 'ISLAMABAD', 'JHANG SADAR', 'KARACHI', 'KASUR', 'LAHOR', 'LARKANA', 'MARDAN', 'MIRPUR KHAS', 'MULTAN', 'NAWABSHAH', 'OKARA', 'PESHAWER', 'QUETTA', 'RAHIMYAR KHAN', 'RAWALPINDI', 'SAHIWAL', 'SARGODHA', 'SHEKHUPURA', 'SIALKOT', 'SUKHUR', 'WAH']
    
    PALAU = ['KOROR']
    
    PANAMA = ['BOCAS DEL TORO', 'CHANGUINOLA', 'CHEPIGANA', 'CHITRE', 'COLON', 'DAVID', 'LAS TABLAS', 'PACORA', 'PANAMA CITY', 'PENONOME', 'SAN MIGUELITO', 'SANTIAGO']
    
    PAPUA_YENI_GINE = ['ALOTAU', 'BUNA', 'DARU', 'LAE', 'MADANG', 'MOROBE', 'PORT MORESBY', 'VANIMO', 'WEWAK']
    
    PARAGUAY = ['ASUNCION', 'CIUDAD DEL ESTE', 'CONCEPCION', 'CORONEL OVIEDO', 'SAN PEDRO DEL PARANA', 'VILLARRICA']
    
    PERU = ['AREQUIPA', 'AYACUCHO', 'CAJAMARCA', 'CHICLAYO', 'CHIMBOTE', 'CUZCO', 'HUANCAYO', 'HUANUCO', 'HUARAZ', 'ICA', 'IQUITOS', 'LIMA', 'MOYOBAMBA', 'PIURA', 'PUCALLPA', 'PUERTO MALDONADO', 'PUNO', 'SULLANA', 'TACNA', 'TRUJILLO']
    
    PITCAIRN_ADASI = ['ADAMSTOWN']
    
    POLONYA = ['BIALYSTOK', 'BIELSKO-BIALA', 'BYDGOSZCZ', 'BYTOM', 'CHORZOW', 'CZESTOCHOWA', 'DABROWA GORNICZA', 'ELBLAG', 'GDANSK', 'GDYNIA', 'GLIWICE', 'GORZOW WIELKOPOLSKI', 'GRUDZIADZ', 'JASTRZEBIE ZBROS', 'KALISZ', 'KATOWICE', 'KIELCE', 'KOSZALIN', 'KRAKOW', 'LEGNICA', 'LODZ', 'LUBLIN', 'NOWY BYTOM', 'OLZSTYN', 'OPOLE', 'PLOCK', 'POZNAN', 'RADOM', 'RYBNIK', 'RZESZOW', 'SLUPSK', 'SONSDWIEC', 'SZCZECIN', 'TARNOW', 'TORUN', 'TYCHY', 'VARSOVA', 'WALBRZYCH', 'WLOCLAWEK', 'WODZISLAW SLASKI', 'WROCLAW', 'ZABRZE', 'ZIELONA GORA']
    
    PORTEKIZ = ['AVEIRO', 'BRAGA', 'CALDAS DA RAINHA', 'CAMINHA', 'CHAVES', 'COIMBRA', 'ESPINHO', 'EVORA', 'FARO', 'FUNCHAL', 'LEIRIA', 'LIZBON', 'MIRANDELA', 'PONTA DELGADA', 'PORTO', 'SANTAREM', 'SETUBAL', 'SINES', 'VILA NOVA DE GAIA', 'VISEU']
    
    PORTO_RIKO = ['BAYAMON', 'CAROLINA', 'PONCE', 'SAN GERMAN', 'SAN JUAN']
    
    REUNION = ['SAINT DENIS']
    
    ROMANYA = ['ARAD', 'BABADAG', 'BACAU', 'BAIA MARE', 'BARLAD', 'BOGAZKOY', 'BOTOSANI', 'BRASOV', 'BUKRES(bucharest)', 'BUZAU', 'CLUJ-NAPOCA', 'COBADIN', 'DROBETA-TURNU SEVERIN', 'FOCSANI', 'GALATI', 'HIRSOVA', 'IASI', 'IBRAIL(braila)', 'KOSTENCE(constanta)', 'KRAYOVA(CRAIO)', 'MANGALIA', 'MECIDIYE', 'ORADEA', 'PETROSANI', 'PIATRA NEAMT', 'PITESTI', 'PLOIESTI', 'RAMNICU VALCEA', 'REGHIN', 'SATU MARE', 'SUBI(SIBIU)', 'SUCEAVA', 'TARGOVISTE', 'TEMISVAR', 'TIRGU MURES', 'TULCEA']
    
    RUANDA = ['BUTARE', 'KIGALI']
    
    RUSYA = ['ABAKAN', 'ANADYR', 'ANGARSK', 'APATITY', 'ARCHANGELSK', 'ASTRAKHAN', 'BARNAUL', 'BATAYSK', 'BELGOROD', 'BIROBIDZHAN', 'BIYSK', 'BLAGOVESHENSK', 'BRATSK', 'BRYANSK', 'CHAYKOVSKY', 'CHEBOKSARY', 'CHELYABINSK', 'CHEREPOVETS', 'CHERKESSK', 'CHITA', 'DE-KASTRI', 'DERBENT', 'DONETSK', 'ELISTA', 'IRKUTSK', 'ISTRA', 'IVANOVO', 'IZHEVSK', 'KABARDINKA', 'KALININGRAD', 'KALUGA', 'KARACHAYEVSK', 'KASHIRA', 'KAZAN', 'KEMEROVO', 'KHABAROVSK', 'KHABEZ', 'KHANTI-MANSISKY', 'KINESHMA', 'KIROV', 'KIRZHACH', 'KISELEVSK', 'KISLOVODSK', 'KLIN', 'KOLPINO', 'KORSAKOV', 'KOSTOMUKSHA', 'KOVROV', 'KRASNODAR', 'KRASNOYARSK', 'KURGAN', 'KURSK', 'KYZYL', 'LAZARREVSKOYE', 'LIPETSK', 'MAGADAN', 'MAGNITOGORSK', 'MAYKOP (ADIGE)', 'MIASS', 'MICHURINSK', "MINERAL'NYYE VODY", 'MOHACKALE', 'MOSKOVA', 'MOZDOK', 'MURMANSK', 'NABEREZHNYYE CHELNY', 'NAKHODKA', 'NALCHIK', 'NIJNINOVGOROD', 'NINJA BAKANSI', 'NIZHNIY TAGIL', 'NOGINSK', 'NOGLIKI', 'NORILSK', 'NOVGOROD', 'NOVOCHERKASSK', 'NOVOKUZNETSK', 'NOVOROSSIYSK', 'NOVOSHAKHTINSK', 'NOVOSIBIRSK', 'NYURBA', 'OBNINSK', 'OMSK', 'ORENBURG', 'PENZA', 'PERM', 'PERVOURALSK', 'PETRODVORETS', 'PETROPAVLOVSK-KAMCHATSKIY', 'PETROZAVODSK', 'POKACHEVA', 'PREGRADNAYA', 'PROKHLADNYY', 'PROKOPYEVSK', 'PSKOV', 'PUSHKIN', 'PYATIGORSK', 'RAMENSKOYE', 'ROSTOV NA DONU', 'ROSTOV(yaroslavl)', 'RUBTSOVSK', 'RYAZAN', 'RYBINSK', 'SALEKHARD', 'SAMARA', 'SARANSK', 'SARATOV', 'SAZONOVO', 'SERGIEV-POSAD', 'SERPUKHOV', 'SEVERODVINSK', 'SHADRINSK', 'SHAKHTY', 'SIMBIRSK', 'SMOLENSK', 'SOCHI', 'SOLIKAMSK', 'St. PETERSBURG', 'STAVROPOL', 'STUPINO', 'SURGUT', 'SYKTYVKAR', 'SYZRAN', 'TAGANROG', 'TAMBOV', 'TOLYATTI', 'TOMSK', 'TROITSK', 'TUAPSE', 'TULA', "TVER'", 'TYRNY-AUZ (BUKHALDZE)', 'TYUMEN', 'UCHKEKEN', 'UCHKULAN', 'UFA', 'UKHTA', 'ULAN UDE', 'ULYANOVSK', 'USSURIYSK', 'UST-ILIMSK', "VAR''YEGAN", 'VELIKYE LUKI', 'VLADIKAFKAS', 'VLADIMIR', 'VLADIVOSTOK', 'VOLGOGRAD', 'VOLOGDA', 'VORONEZH', 'VOTKINSK', 'VYBORG', 'YAKUTSK', 'YAROSLAVL', 'YEKATERINBURG', 'YESSENTUKI', 'YOSHKAR-OLA', 'YUZHNO-SAKHALINSK', 'ZHUKOVSKIY', 'ZLATOUST']
    
    SAMOA = ['APIA']
    
    SENEGAL = ['DAKAR', 'KAOLACK', 'LINGUERE', 'SAINT-LOUIS', 'THIES', 'ZIGUINCHOR']
    
    SEYSEL_ADALARI = ['VICTORIA']
    
    SILI = ['ANTOFAGASTA', 'ARICA', 'CHILLAN', 'COIHAIQUE', 'CONCEPCION', 'COPIAPO', 'COQUIMBO', 'CURICO', 'IQUIQUE', 'LA SERENA', 'LAS CONDES', 'LOS ANGELES', 'OSORNO', 'PUERTO MONTT', 'PUNTA ARENAS', 'QUILPUE', 'RANCAGUA', 'SANTIAGO', 'TALCA', 'TALCAHUANO', 'TEMUCO', 'VALDIVIA', 'VALPARAISO', 'VINA DEL MAR']
    
    SINGAPUR = ['SINGAPUR']
    
    SIRBISTAN = ['BELGRAT', 'CACAK', 'KRAGUJEVAC', 'MITROVA', 'NIS', 'NOVI SAD', 'SMEDEREVO', 'SUBOTICA', 'ZEMUN', 'ZRENJANIN']
    
    SLOVAKYA = ['BANSKA BYSTRICA', 'BARDEJOV', 'BRATISLAVA', 'HUMENNE', 'KOSICE', 'LIPTOVSKY MIKULAS', 'MICHALOVCE', 'NITRA', 'PIESTANY', 'PRESOV']
    
    SLOVENYA = ['CELJE', 'DRAVOGRAD', 'KOCEVJE', 'KOPER', 'KRSKO', 'LJUBLJANA', 'MARIBOR', 'MURSKA SOBOTA', 'NOVO MESTO', 'VELENJE']
    
    SOMALI = ['BANDARBEYLA', 'BULO BURTI', 'CALUULA', 'DHORZI', 'EYL', 'KISMAAYO', 'MOGADISHU', 'OBBIA']
    
    SRI_LANKA = ['COLOMBO', 'JAFFNA', 'KANDY', 'MATARA', 'MORATUWA', 'SRI JAYAWARDENEPURA', 'TRINCOMALEE']
    
    SUDAN = ['AL QADARIF', 'AL UBAYYID', 'HARTUM', 'JUBA', 'KASSALA', 'NASIR', 'NYALA', 'PORT SUDAN', 'TAWKAR', 'WAD MADANI', 'WADI HALFA']
    
    SURINAM = ['BROKOPONDO', 'PARAMARIBO']
    
    SURIYE = ['AL LADHIQIYAH', 'AL QAMISHLI', 'AR RAQQAH', 'DAYR AZ ZAWR', 'HALEP', 'HAMAH', 'HIMS', 'IDLIB', 'SAM']
    
    SUUDI_ARABISTAN = ['AD DAMMAM', 'AL HUFUF', 'BURAYDAH', 'CIDDE', 'HAIL', 'MEDINE', 'MEKKE', 'RIYAD', 'SHAQRA', 'TABUK']
    
    SVALBARD = ['LONGYEARBYEN', 'SVEAGRUVA']
    
    SVAZILAND = ['MBABANE']
    
    TACIKISTAN = ['DUSEMBE', 'KHORUGH', 'KHUJAND', 'KULOB']
    
    TANZANYA = ['ARUSHA', 'DAR ES SALAAM', 'DODOMA', 'MBEYA', 'MOROGORO', 'MWANZA', 'SHINYANGA', 'TABORA', 'TANGA', 'WETE', 'ZANZIBAR']
    
    TAYLAND = ['BAN THUNG (KO SAMUI)', 'BANGKOK', 'BURIRAM', 'CHAIYAP HUM', 'CHIANG MAI', 'CHON BURI', 'KHON KAEN', 'NAKHON RATCHASIMA', 'NAKHON SAWAN', 'NAKORN PHANOM', 'PHITSANULOK', 'PHUKET', 'RAYONG', 'SURAT THANI', 'UBON RATCHATHANI', 'UDON THANI']
    
    TAYVAN = ['CHIAYI', 'CHU-NAN', 'HSIN-CHU', 'HUA-LIEN', 'KAOHSIUNG', 'PANCHIAO', 'PINGTUNG', 'TAICHUNG', 'TAINAN', 'TAIPEI']
    
    TOGO = ['LOME', 'NIAMTOUGOU', 'SOKODE']
    
    TONGA = ['NUKUALOFA']
    
    TRINIDAT_VE_TOBAGO = ['ARIMA', 'PORT OF SPAIN', 'SAN FERNANDO']
    
    TUNUS = ['AL QAYRAWAN', 'BIZERTE', 'GABES', 'GAFSA', 'LA GOULETTA', 'SFAX', 'SUSAH', 'TUNUS']
    
    TURKIYE = ['ADANA', 'ADIYAMAN', 'AFYON', 'AGRI', 'AKSARAY', 'AMASYA', 'ANKARA', 'ANTALYA', 'ARDAHAN', 'ARTVIN', 'AYDIN', 'BALIKESIR', 'BARTIN', 'BATMAN', 'BAYBURT', 'BILECIK', 'BINGOL', 'BITLIS', 'BOLU', 'BURDUR', 'BURSA', 'CANAKKALE', 'CANKIRI', 'CORUM', 'DENIZLI', 'DIYARBAKIR', 'DUZCE', 'EDIRNE', 'ELAZIG', 'ERZINCAN', 'ERZURUM', 'ESKISEHIR', 'GAZIANTEP', 'GIRESUN', 'GUMUSHANE', 'HAKKARI', 'HATAY', 'ICEL', 'IGDIR', 'ISPARTA', 'ISTANBUL', 'IZMIR', 'KAHRAMANMARAS', 'KARABUK', 'KARAMAN', 'KARS', 'KASTAMONU', 'KAYSERI', 'KILIS', 'KIRIKKALE', 'KIRKLARELI', 'KIRSEHIR', 'KOCAELI', 'KONYA', 'KUTAHYA', 'MALATYA', 'MANISA', 'MARDIN', 'MUGLA', 'MUS', 'NEVSEHIR', 'NIGDE', 'ORDU', 'OSMANIYE', 'RIZE', 'SAKARYA', 'SAMSUN', 'SANLIURFA', 'SIIRT', 'SINOP', 'SIRNAK', 'SIVAS', 'TEKIRDAG', 'TOKAT', 'TRABZON', 'TUNCELI', 'USAK', 'VAN', 'YALOVA', 'YOZGAT', 'ZONGULDAK']
    
    TURKMENISTAN = ['ASKABAT', 'CHARJEW', 'KERKI', 'KOHNE URGENC', 'MERV', 'NEBIT DAG', 'TASAUZ', 'TURKMENBASI']
    
    UGANDA = ['ARUA', 'GULU', 'KABALE', 'KAMPALA', 'KITGUM', 'TORORO']
    
    UKRAYNA = ['ALCHEVSK', 'BERDYANSK', 'BILA TSERKVA', 'CHERKASY', 'CHERNIHIN', 'CHERNIVTSI', 'DERDYCHIV', 'DNIPROPETROVSK', 'DONETSK', 'HORLIVKA', 'IVANO FRANKIVSK', 'IZMAYIL', 'KAMYANETS PODILSKYY', 'KHARKHOV', 'KHERSON', 'KIEV', 'KILIYA', 'KIROVOHRAD', 'KONOTOP', 'KRANSNYY LUCH', 'KREMENCHUK', 'KROVOHRAD', 'KRYVYY RIH', 'LISICHANSK', 'LUGANS', 'LUHANSK', 'LUTSK', 'LVIV', 'MAKEYEVKA', 'MARIUPOL', 'MELITOPOL', 'MYKOLAYIV', 'NIKOPOL', 'NIZHYN', 'OLEKSANDRIYA', 'POLTAVA', 'RENI', 'RIVNE', 'SHOSTKA', 'STAKHANOV', 'SUMY', 'SVERDLOVSK', 'SYEVERODONETSK', 'TERNOPIL', 'UMAN', 'UZHHOROD', 'VINNYTSYA', 'YENAKIYEVO', 'ZAPORIZHZHYA', 'ZAPOROJIE', 'ZHYTOMYR']
    
    UKRAYNA_KIRIM = ['AKMESCIT (Simferopol)', 'ALUSHTA', 'BAHCESARAY', 'CANKOY', 'ESKI KIRIM', 'GOZLEVE', 'ISGI', 'KARASUPAZAR', 'KEFE', 'KERCH', 'ODESSA', 'RAZDOLNI', 'SIVASTAPOL', 'SUDAK', 'YALTA']
    
    UMMAN = ['MASKAT', 'MIRBAT', 'NIZWA', 'SALALAH', 'SUHAR', 'SUR']
    
    URDUN = ['AL-AQABAH', 'AMMAN', 'AZ ZARQA', 'IRBID']
    
    URUGUAY = ['ARTIGAS', 'CARMELO', 'COLONIA DEL SACRAMENTO', 'DURAZNO', 'MALDONADO', 'MELO', 'MERCEDES', 'MONTEVIDEO', 'PAYSANDU', 'RIVERA', 'ROCHA', 'SALTO', 'SAN JOSE DE MAYO', 'TACUAREMBO', 'TIRINIDAD']
    
    VANUATU = ['PORT-VILA']
    
    VATIKAN = ['VATIKAN']
    
    VENEZUELA = ['ACARIGUA', 'BARCELONA', 'BARINAS', 'BARQUISIMETO', 'BARUTA', 'CARACAS', 'CATIA LA MAR', 'CIUDAD BOLIVAR', 'CIUDAD GUAYANA', 'CORO', 'CUMANA', 'GUACARA', 'GUANARE', 'GUARENAS', 'LOS TEQUES', 'MARACAIBO', 'MARACAY', 'MATURIN', 'MERIDA', 'PETARE', 'PORLAMAR', 'PUERTO CABELLO', 'PUERTO LA CRUZ', 'PUNTO FIJO', 'SAN CARLOS', 'SAN CRISTOBAL', 'SAN FELIPE', 'TURMERO', 'VALENCIA', 'VALERA']
    
    VIETNAM = ['BIEN HOA', 'BUON ME THUOT', 'CAM PHA', 'CAN THO', 'DA LAT', 'DA NANG', 'HAIPHONG', 'HANOI', 'HO CHI MINH CITY', 'HONG GAI', 'HUE', 'LONG XUYEN', 'MY THO', 'NAM DINH', 'NHA TRANG', 'PHAN THIET', 'QUANG TRI', 'QUI NHON', 'RACH GIA', 'THAI NGUYEN', 'VINH', 'VUNG TAU']
    
    YEMEN = ['ADEN', 'AL HUDAYDAH', 'AL MUKALLA', 'SANAA', 'TAIZZ', 'THAMUD']
    
    YENI_KALEDONYA = ['KOUMAC', 'NOUMEA']
    
    YENI_ZELLANDA = ['AUCKLAND', 'CHRISTCHURCH', 'GISBORNE', 'HAMILTON', 'HASTINGS', 'MANUKAU', 'NAPIER', 'NEW PLYMOUTH', 'PALMERSTON NORTH', 'PORIRUA', 'QUEENSTOWN', 'ROTARUA', 'TAUPO', 'TAURANGA', 'WAIPUKURAU', 'WAITAKERE', 'WANGANUI', 'WELLINGTON', 'WHAKATANE', 'WHANGAREI']
    
    YESIL_BURUN = ['MINDELO', 'PRAIA']
    
    YUNANISTAN = ['ATINA', 'CORINTH', 'DEDEAGAC', 'ERMOUPOLIS', 'GUMULCINE(kornotini)', 'IDANNINA', 'IGOUMENITSA', 'IRAKLION', 'ISKECE(xanthi)', 'KALAMARIA', 'KALAMATA', 'KARDITSA', 'KATAKOLON', 'KATERINI', 'KAVALA', 'KERKIRA', 'KHANIA', 'KOS', 'KOZANI', 'LAMIA', 'LARISA', 'MYTILENE', 'NEAPOLIS', 'PATRASS', 'RODOS', 'SELANIK(thessaloniki)', 'SERRAI', 'TRIKALA', 'TRIPOLIS', 'VEROIA', 'VOLOS']
    
    ZAMBIYA = ['CHINGOLA', 'KABWE', 'KITWE', 'LIVINGSTONE', 'LUANSHYA', 'LUSAKA', 'MUFULIRA', 'NDOLA']
    
    ZIMBABVE = ['BULAWAYO', 'CHITUNGWIZA', 'GWERU', 'HARARE', 'MUTARE']
    
    zamanTurkiye = {'ADANA': '1985', 'ADIYAMAN': '1986', 'AFYON': '1987', 'AGRI': '1988', 'AKSARAY': '1989', 'AMASYA': '1990', 'ANKARA': '1991', 'ANTALYA': '1992', 'ARDAHAN': '1993', 'ARTVIN': '1994', 'AYDIN': '1995', 'BALIKESIR': '1996', 'BARTIN': '1997', 'BATMAN': '1998', 'BAYBURT': '1999', 'BILECIK': '2000', 'BINGOL': '2001', 'BITLIS': '2002', 'BOLU': '2003', 'BURDUR': '2004', 'BURSA': '2005', 'CANAKKALE': '2006', 'CANKIRI': '2007', 'CORUM': '2008', 'DENIZLI': '2009', 'DIYARBAKIR': '2010', 'DUZCE': '2011', 'EDIRNE': '2012', 'ELAZIG': '2013', 'ERZINCAN': '2014', 'ERZURUM': '2015', 'ESKISEHIR': '2016', 'GAZIANTEP': '2017', 'GIRESUN': '2018', 'GUMUSHANE': '2019', 'HAKKARI': '2020', 'HATAY': '2021', 'ICEL': '2024', 'IGDIR': '2022', 'ISPARTA': '2023', 'ISTANBUL': '2025', 'IZMIR': '2026', 'KAHRAMANMARAS': '2027', 'KARABUK': '2028', 'KARAMAN': '2029', 'KARS': '2030', 'KASTAMONU': '2031', 'KAYSERI': '2032', 'KILIS': '2036', 'KIRIKKALE': '2033', 'KIRKLARELI': '2034', 'KIRSEHIR': '2035', 'KOCAELI': '2037', 'KONYA': '2038', 'KUTAHYA': '2039', 'MALATYA': '2040', 'MANISA': '2041', 'MARDIN': '2042', 'MERSIN': '2146', 'MUGLA': '2043', 'MUS': '2044', 'NEVSEHIR': '2045', 'NIGDE': '2046', 'ORDU': '2047', 'OSMANIYE': '2048', 'RIZE': '2049', 'SAKARYA': '2050', 'SAMSUN': '2051', 'SANLIURFA': '2055', 'SIIRT': '2052', 'SINOP': '2053', 'SIRNAK': '2056', 'SIVAS': '2054', 'TEKIRDAG': '2057', 'TOKAT': '2058', 'TRABZON': '2059', 'TUNCELI': '2060', 'USAK': '2061', 'VAN': '2062', 'YALOVA': '2063', 'YOZGAT': '2064', 'ZONGULDAK': '2065'}
