# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pynamaz.ui'
#
# Created: Wed Feb  3 19:46:40 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 573)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 521, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 341, 261))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 30, 231, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 1, 1, 1)
        self.lcdNumberMaghribHour = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberMaghribHour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberMaghribHour.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberMaghribHour.setLineWidth(1)
        self.lcdNumberMaghribHour.setSmallDecimalPoint(False)
        self.lcdNumberMaghribHour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberMaghribHour.setObjectName("lcdNumberMaghribHour")
        self.gridLayout_2.addWidget(self.lcdNumberMaghribHour, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        self.lcdNumberFajrHour = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberFajrHour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberFajrHour.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberFajrHour.setLineWidth(1)
        self.lcdNumberFajrHour.setSmallDecimalPoint(False)
        self.lcdNumberFajrHour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberFajrHour.setObjectName("lcdNumberFajrHour")
        self.gridLayout_2.addWidget(self.lcdNumberFajrHour, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.lcdNumberIshaHour = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberIshaHour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberIshaHour.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberIshaHour.setLineWidth(1)
        self.lcdNumberIshaHour.setSmallDecimalPoint(False)
        self.lcdNumberIshaHour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberIshaHour.setObjectName("lcdNumberIshaHour")
        self.gridLayout_2.addWidget(self.lcdNumberIshaHour, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.lcdNumberAsrHour = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberAsrHour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberAsrHour.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberAsrHour.setLineWidth(1)
        self.lcdNumberAsrHour.setSmallDecimalPoint(False)
        self.lcdNumberAsrHour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberAsrHour.setObjectName("lcdNumberAsrHour")
        self.gridLayout_2.addWidget(self.lcdNumberAsrHour, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 1, 1, 1)
        self.lcdNumberDhuhrHour = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberDhuhrHour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberDhuhrHour.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberDhuhrHour.setLineWidth(1)
        self.lcdNumberDhuhrHour.setSmallDecimalPoint(False)
        self.lcdNumberDhuhrHour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberDhuhrHour.setObjectName("lcdNumberDhuhrHour")
        self.gridLayout_2.addWidget(self.lcdNumberDhuhrHour, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 2, 1, 1, 1)
        self.lcdNumberSunriseHour = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberSunriseHour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberSunriseHour.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberSunriseHour.setLineWidth(1)
        self.lcdNumberSunriseHour.setSmallDecimalPoint(False)
        self.lcdNumberSunriseHour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberSunriseHour.setObjectName("lcdNumberSunriseHour")
        self.gridLayout_2.addWidget(self.lcdNumberSunriseHour, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        self.lcdNumberIshaMinute = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberIshaMinute.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberIshaMinute.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberIshaMinute.setLineWidth(1)
        self.lcdNumberIshaMinute.setSmallDecimalPoint(False)
        self.lcdNumberIshaMinute.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberIshaMinute.setObjectName("lcdNumberIshaMinute")
        self.gridLayout_2.addWidget(self.lcdNumberIshaMinute, 6, 3, 1, 1)
        self.lcdNumberMaghribMinute = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberMaghribMinute.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberMaghribMinute.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberMaghribMinute.setLineWidth(1)
        self.lcdNumberMaghribMinute.setSmallDecimalPoint(False)
        self.lcdNumberMaghribMinute.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberMaghribMinute.setObjectName("lcdNumberMaghribMinute")
        self.gridLayout_2.addWidget(self.lcdNumberMaghribMinute, 5, 3, 1, 1)
        self.lcdNumberAsrMinute = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberAsrMinute.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberAsrMinute.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberAsrMinute.setLineWidth(1)
        self.lcdNumberAsrMinute.setSmallDecimalPoint(False)
        self.lcdNumberAsrMinute.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberAsrMinute.setObjectName("lcdNumberAsrMinute")
        self.gridLayout_2.addWidget(self.lcdNumberAsrMinute, 4, 3, 1, 1)
        self.lcdNumberDhuhrMinute = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberDhuhrMinute.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberDhuhrMinute.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberDhuhrMinute.setLineWidth(1)
        self.lcdNumberDhuhrMinute.setSmallDecimalPoint(False)
        self.lcdNumberDhuhrMinute.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberDhuhrMinute.setObjectName("lcdNumberDhuhrMinute")
        self.gridLayout_2.addWidget(self.lcdNumberDhuhrMinute, 3, 3, 1, 1)
        self.lcdNumberSunriseMinute = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberSunriseMinute.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberSunriseMinute.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberSunriseMinute.setLineWidth(1)
        self.lcdNumberSunriseMinute.setSmallDecimalPoint(False)
        self.lcdNumberSunriseMinute.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberSunriseMinute.setObjectName("lcdNumberSunriseMinute")
        self.gridLayout_2.addWidget(self.lcdNumberSunriseMinute, 2, 3, 1, 1)
        self.lcdNumberFajrMinute = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumberFajrMinute.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberFajrMinute.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberFajrMinute.setLineWidth(1)
        self.lcdNumberFajrMinute.setSmallDecimalPoint(False)
        self.lcdNumberFajrMinute.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberFajrMinute.setObjectName("lcdNumberFajrMinute")
        self.gridLayout_2.addWidget(self.lcdNumberFajrMinute, 1, 3, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(30, 20, 421, 61))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 1, 3, 1, 1)
        self.labelCurrentDate = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.labelCurrentDate.setObjectName("labelCurrentDate")
        self.gridLayout_8.addWidget(self.labelCurrentDate, 1, 1, 1, 1)
        self.labelCurrentCity = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.labelCurrentCity.setText("")
        self.labelCurrentCity.setObjectName("labelCurrentCity")
        self.gridLayout_8.addWidget(self.labelCurrentCity, 1, 0, 1, 1)
        self.lcdNumberCurrentMinute = QtWidgets.QLCDNumber(self.gridLayoutWidget_7)
        self.lcdNumberCurrentMinute.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberCurrentMinute.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberCurrentMinute.setLineWidth(1)
        self.lcdNumberCurrentMinute.setSmallDecimalPoint(False)
        self.lcdNumberCurrentMinute.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberCurrentMinute.setObjectName("lcdNumberCurrentMinute")
        self.gridLayout_8.addWidget(self.lcdNumberCurrentMinute, 1, 5, 1, 1)
        self.lcdNumberCurrentHour = QtWidgets.QLCDNumber(self.gridLayoutWidget_7)
        self.lcdNumberCurrentHour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberCurrentHour.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberCurrentHour.setLineWidth(1)
        self.lcdNumberCurrentHour.setSmallDecimalPoint(False)
        self.lcdNumberCurrentHour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberCurrentHour.setObjectName("lcdNumberCurrentHour")
        self.gridLayout_8.addWidget(self.lcdNumberCurrentHour, 1, 4, 1, 1)
        self.lcdNumberCurrentSecond = QtWidgets.QLCDNumber(self.gridLayoutWidget_7)
        self.lcdNumberCurrentSecond.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberCurrentSecond.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberCurrentSecond.setLineWidth(1)
        self.lcdNumberCurrentSecond.setSmallDecimalPoint(False)
        self.lcdNumberCurrentSecond.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberCurrentSecond.setObjectName("lcdNumberCurrentSecond")
        self.gridLayout_8.addWidget(self.lcdNumberCurrentSecond, 1, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 1, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 380, 377, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelNextPrayer = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelNextPrayer.setObjectName("labelNextPrayer")
        self.horizontalLayout.addWidget(self.labelNextPrayer)
        self.lcdNumberNextPrayerHour = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumberNextPrayerHour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberNextPrayerHour.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberNextPrayerHour.setLineWidth(1)
        self.lcdNumberNextPrayerHour.setSmallDecimalPoint(False)
        self.lcdNumberNextPrayerHour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberNextPrayerHour.setObjectName("lcdNumberNextPrayerHour")
        self.horizontalLayout.addWidget(self.lcdNumberNextPrayerHour)
        self.lcdNumberNextPrayerMinute = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumberNextPrayerMinute.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberNextPrayerMinute.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumberNextPrayerMinute.setLineWidth(1)
        self.lcdNumberNextPrayerMinute.setSmallDecimalPoint(False)
        self.lcdNumberNextPrayerMinute.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberNextPrayerMinute.setObjectName("lcdNumberNextPrayerMinute")
        self.horizontalLayout.addWidget(self.lcdNumberNextPrayerMinute)
        self.lcdNumberNextPrayerSecond = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumberNextPrayerSecond.setObjectName("lcdNumberNextPrayerSecond")
        self.horizontalLayout.addWidget(self.lcdNumberNextPrayerSecond)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 360, 411, 111))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButtonOpenPrayerTimesText = QtWidgets.QPushButton(self.tab)
        self.pushButtonOpenPrayerTimesText.setGeometry(QtCore.QRect(260, 470, 221, 23))
        self.pushButtonOpenPrayerTimesText.setObjectName("pushButtonOpenPrayerTimesText")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 0, 451, 261))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 411, 211))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelCountry = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelCountry.setObjectName("labelCountry")
        self.gridLayout_3.addWidget(self.labelCountry, 0, 0, 1, 1)
        self.labelCity = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelCity.setObjectName("labelCity")
        self.gridLayout_3.addWidget(self.labelCity, 1, 0, 1, 1)
        self.labelDistrict = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelDistrict.setObjectName("labelDistrict")
        self.gridLayout_3.addWidget(self.labelDistrict, 2, 0, 1, 1)
        self.labelTown = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelTown.setObjectName("labelTown")
        self.gridLayout_3.addWidget(self.labelTown, 3, 0, 1, 1)
        self.comboBoxSelectCountry = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxSelectCountry.setObjectName("comboBoxSelectCountry")
        self.gridLayout_3.addWidget(self.comboBoxSelectCountry, 0, 1, 1, 1)
        self.comboBoxSelectCity = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxSelectCity.setObjectName("comboBoxSelectCity")
        self.gridLayout_3.addWidget(self.comboBoxSelectCity, 1, 1, 1, 1)
        self.comboBoxSelectDistrict = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxSelectDistrict.setEnabled(False)
        self.comboBoxSelectDistrict.setObjectName("comboBoxSelectDistrict")
        self.gridLayout_3.addWidget(self.comboBoxSelectDistrict, 2, 1, 1, 1)
        self.comboBoxSelectTown = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxSelectTown.setEnabled(False)
        self.comboBoxSelectTown.setObjectName("comboBoxSelectTown")
        self.gridLayout_3.addWidget(self.comboBoxSelectTown, 3, 1, 1, 1)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.tab_2)
        self.buttonBox_2.setGeometry(QtCore.QRect(280, 260, 160, 25))
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.pushButtonSetTimesManuelly = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonSetTimesManuelly.setGeometry(QtCore.QRect(220, 330, 221, 23))
        self.pushButtonSetTimesManuelly.setObjectName("pushButtonSetTimesManuelly")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 471, 681))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 320, 451, 41))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButtonWarningsReset = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.pushButtonWarningsReset.setObjectName("pushButtonWarningsReset")
        self.gridLayout_9.addWidget(self.pushButtonWarningsReset, 0, 2, 1, 1)
        self.pushButtonWarningsReturnToDefaults = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.pushButtonWarningsReturnToDefaults.setObjectName("pushButtonWarningsReturnToDefaults")
        self.gridLayout_9.addWidget(self.pushButtonWarningsReturnToDefaults, 0, 1, 1, 1)
        self.pushButtonWarningsSave = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.pushButtonWarningsSave.setObjectName("pushButtonWarningsSave")
        self.gridLayout_9.addWidget(self.pushButtonWarningsSave, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 451, 301))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinBoxFacrWarn = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBoxFacrWarn.setObjectName("spinBoxFacrWarn")
        self.gridLayout_4.addWidget(self.spinBoxFacrWarn, 0, 1, 1, 1)
        self.spinBoxAsrWarn = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBoxAsrWarn.setObjectName("spinBoxAsrWarn")
        self.gridLayout_4.addWidget(self.spinBoxAsrWarn, 3, 1, 1, 1)
        self.checkBoxAsrWarn = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxAsrWarn.setObjectName("checkBoxAsrWarn")
        self.gridLayout_4.addWidget(self.checkBoxAsrWarn, 3, 0, 1, 1)
        self.spinBoxDhuhrWarn = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBoxDhuhrWarn.setObjectName("spinBoxDhuhrWarn")
        self.gridLayout_4.addWidget(self.spinBoxDhuhrWarn, 2, 1, 1, 1)
        self.spinBoxMaghribWarn = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBoxMaghribWarn.setObjectName("spinBoxMaghribWarn")
        self.gridLayout_4.addWidget(self.spinBoxMaghribWarn, 4, 1, 1, 1)
        self.checkBoxMaghribWarn = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxMaghribWarn.setObjectName("checkBoxMaghribWarn")
        self.gridLayout_4.addWidget(self.checkBoxMaghribWarn, 4, 0, 1, 1)
        self.checkBoxDhuhrWarn = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxDhuhrWarn.setObjectName("checkBoxDhuhrWarn")
        self.gridLayout_4.addWidget(self.checkBoxDhuhrWarn, 2, 0, 1, 1)
        self.checkBoxIshaWarn = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxIshaWarn.setObjectName("checkBoxIshaWarn")
        self.gridLayout_4.addWidget(self.checkBoxIshaWarn, 5, 0, 1, 1)
        self.spinBoxIshaWarn = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBoxIshaWarn.setObjectName("spinBoxIshaWarn")
        self.gridLayout_4.addWidget(self.spinBoxIshaWarn, 5, 1, 1, 1)
        self.checkBoxFajrWarn = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxFajrWarn.setObjectName("checkBoxFajrWarn")
        self.gridLayout_4.addWidget(self.checkBoxFajrWarn, 0, 0, 1, 1)
        self.checkBoxSunriseWarn = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxSunriseWarn.setObjectName("checkBoxSunriseWarn")
        self.gridLayout_4.addWidget(self.checkBoxSunriseWarn, 1, 0, 1, 1)
        self.spinBoxSunriseWarn = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBoxSunriseWarn.setObjectName("spinBoxSunriseWarn")
        self.gridLayout_4.addWidget(self.spinBoxSunriseWarn, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(10, 9, 471, 381))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 431, 291))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBoxPlayWarnSound = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkBoxPlayWarnSound.setObjectName("checkBoxPlayWarnSound")
        self.gridLayout_6.addWidget(self.checkBoxPlayWarnSound, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 10, 0, 1, 1)
        self.checkBoxShowInTray = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkBoxShowInTray.setObjectName("checkBoxShowInTray")
        self.gridLayout_6.addWidget(self.checkBoxShowInTray, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 8, 0, 1, 1)
        self.checkBoxPlayAdhan = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkBoxPlayAdhan.setObjectName("checkBoxPlayAdhan")
        self.gridLayout_6.addWidget(self.checkBoxPlayAdhan, 4, 0, 1, 1)
        self.checkBoxMuteInAdhanTime = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkBoxMuteInAdhanTime.setObjectName("checkBoxMuteInAdhanTime")
        self.gridLayout_6.addWidget(self.checkBoxMuteInAdhanTime, 6, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 9, 0, 1, 1)
        self.comboBoxCloseOption = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.comboBoxCloseOption.setObjectName("comboBoxCloseOption")
        self.comboBoxCloseOption.addItem("")
        self.comboBoxCloseOption.addItem("")
        self.gridLayout_6.addWidget(self.comboBoxCloseOption, 10, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget_5)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_6.addWidget(self.toolButton, 8, 1, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.gridLayoutWidget_5)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_6.addWidget(self.toolButton_2, 9, 1, 1, 1)
        self.checkBoxSystemNotifications = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkBoxSystemNotifications.setObjectName("checkBoxSystemNotifications")
        self.gridLayout_6.addWidget(self.checkBoxSystemNotifications, 7, 0, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 320, 431, 31))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonPreferencesReset = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.pushButtonPreferencesReset.setObjectName("pushButtonPreferencesReset")
        self.gridLayout_5.addWidget(self.pushButtonPreferencesReset, 0, 2, 1, 1)
        self.pushButtonPreferencesSave = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.pushButtonPreferencesSave.setObjectName("pushButtonPreferencesSave")
        self.gridLayout_5.addWidget(self.pushButtonPreferencesSave, 0, 0, 1, 1)
        self.pushButtonPreferencesReturnToDefaults = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.pushButtonPreferencesReturnToDefaults.setObjectName("pushButtonPreferencesReturnToDefaults")
        self.gridLayout_5.addWidget(self.pushButtonPreferencesReturnToDefaults, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 0, 311, 311))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(40, 30, 231, 261))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 5, 0, 1, 1)
        self.spinBoxZuhrCount = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBoxZuhrCount.setObjectName("spinBoxZuhrCount")
        self.gridLayout_7.addWidget(self.spinBoxZuhrCount, 2, 1, 1, 1)
        self.spinBoxAsrCount = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBoxAsrCount.setObjectName("spinBoxAsrCount")
        self.gridLayout_7.addWidget(self.spinBoxAsrCount, 3, 1, 1, 1)
        self.spinBoxMaghribCount = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBoxMaghribCount.setObjectName("spinBoxMaghribCount")
        self.gridLayout_7.addWidget(self.spinBoxMaghribCount, 4, 1, 1, 1)
        self.spinBoxIshaCount = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBoxIshaCount.setObjectName("spinBoxIshaCount")
        self.gridLayout_7.addWidget(self.spinBoxIshaCount, 5, 1, 1, 1)
        self.spinBoxFajrCount = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBoxFajrCount.setObjectName("spinBoxFajrCount")
        self.gridLayout_7.addWidget(self.spinBoxFajrCount, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(30, 70, 432, 106))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_17.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_41.setObjectName("label_41")
        self.gridLayout_17.addWidget(self.label_41, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_17.addWidget(self.pushButton_3, 3, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_17.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_17.addWidget(self.pushButton, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_42.setObjectName("label_42")
        self.gridLayout_17.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_43.setObjectName("label_43")
        self.gridLayout_17.addWidget(self.label_43, 3, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_44.setObjectName("label_44")
        self.gridLayout_17.addWidget(self.label_44, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 20))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(self.menubar)
        self.menuMen.setObjectName("menuMen")
        self.menuG_r_n_m = QtWidgets.QMenu(self.menuMen)
        self.menuG_r_n_m.setObjectName("menuG_r_n_m")
        self.menuNas_l_kullan_l_r = QtWidgets.QMenu(self.menubar)
        self.menuNas_l_kullan_l_r.setObjectName("menuNas_l_kullan_l_r")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_k = QtWidgets.QAction(MainWindow)
        self.action_k.setObjectName("action_k")
        self.actionCleanlooks = QtWidgets.QAction(MainWindow)
        self.actionCleanlooks.setObjectName("actionCleanlooks")
        self.actionGTK = QtWidgets.QAction(MainWindow)
        self.actionGTK.setObjectName("actionGTK")
        self.actionPlastique = QtWidgets.QAction(MainWindow)
        self.actionPlastique.setObjectName("actionPlastique")
        self.actionWindows = QtWidgets.QAction(MainWindow)
        self.actionWindows.setObjectName("actionWindows")
        self.actionG_ncelle_2 = QtWidgets.QAction(MainWindow)
        self.actionG_ncelle_2.setObjectName("actionG_ncelle_2")
        self.actionBespin = QtWidgets.QAction(MainWindow)
        self.actionBespin.setObjectName("actionBespin")
        self.actionQtcurve = QtWidgets.QAction(MainWindow)
        self.actionQtcurve.setObjectName("actionQtcurve")
        self.actionMotif = QtWidgets.QAction(MainWindow)
        self.actionMotif.setObjectName("actionMotif")
        self.actionCDE = QtWidgets.QAction(MainWindow)
        self.actionCDE.setObjectName("actionCDE")
        self.actionOxygen = QtWidgets.QAction(MainWindow)
        self.actionOxygen.setObjectName("actionOxygen")
        self.actionNas_l_kullan_l_r = QtWidgets.QAction(MainWindow)
        self.actionNas_l_kullan_l_r.setObjectName("actionNas_l_kullan_l_r")
        self.actionHide = QtWidgets.QAction(MainWindow)
        self.actionHide.setObjectName("actionHide")
        self.actionShow = QtWidgets.QAction(MainWindow)
        self.actionShow.setObjectName("actionShow")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuG_r_n_m.addAction(self.actionBespin)
        self.menuG_r_n_m.addAction(self.actionCleanlooks)
        self.menuG_r_n_m.addAction(self.actionGTK)
        self.menuG_r_n_m.addAction(self.actionPlastique)
        self.menuG_r_n_m.addAction(self.actionWindows)
        self.menuG_r_n_m.addAction(self.actionQtcurve)
        self.menuG_r_n_m.addAction(self.actionMotif)
        self.menuG_r_n_m.addAction(self.actionCDE)
        self.menuG_r_n_m.addAction(self.actionOxygen)
        self.menuMen.addAction(self.menuG_r_n_m.menuAction())
        self.menuMen.addAction(self.actionG_ncelle_2)
        self.menuMen.addAction(self.actionShow)
        self.menuMen.addAction(self.actionHide)
        self.menuMen.addAction(self.actionExit)
        self.menuNas_l_kullan_l_r.addAction(self.actionNas_l_kullan_l_r)
        self.menubar.addAction(self.menuMen.menuAction())
        self.menubar.addAction(self.menuNas_l_kullan_l_r.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionCleanlooks.triggered.connect(MainWindow.repaint)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "VAKİTLER"))
        self.label_5.setText(_translate("MainWindow", "YATSI"))
        self.label_4.setText(_translate("MainWindow", "AKŞAM"))
        self.label_2.setText(_translate("MainWindow", "ÖĞLE"))
        self.label.setText(_translate("MainWindow", "İMSAK"))
        self.label_3.setText(_translate("MainWindow", "İKİNDİ"))
        self.label_24.setText(_translate("MainWindow", "GÜNEŞ"))
        self.label_6.setText(_translate("MainWindow", "Saat:"))
        self.labelCurrentDate.setText(_translate("MainWindow", "::tarih::"))
        self.labelNextPrayer.setText(_translate("MainWindow", "SONRAKİ VAKTE KALAN SÜRE"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Kalan süre"))
        self.pushButtonOpenPrayerTimesText.setText(_translate("MainWindow", "Namaz vakitleri dosyasını aç"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Anasayfa"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.labelCountry.setText(_translate("MainWindow", "ÜLKE"))
        self.labelCity.setText(_translate("MainWindow", "ŞEHİR"))
        self.labelDistrict.setText(_translate("MainWindow", "İLÇE"))
        self.labelTown.setText(_translate("MainWindow", "KÖY/KASABA"))
        self.pushButtonSetTimesManuelly.setText(_translate("MainWindow", "Manuel olarak Ayarla"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Bölge"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Vakit Uyarıları"))
        self.pushButtonWarningsReset.setText(_translate("MainWindow", "Reset"))
        self.pushButtonWarningsReturnToDefaults.setText(_translate("MainWindow", "Varsayılana Dön"))
        self.pushButtonWarningsSave.setText(_translate("MainWindow", "Kaydet"))
        self.checkBoxAsrWarn.setText(_translate("MainWindow", "İkindi"))
        self.checkBoxMaghribWarn.setText(_translate("MainWindow", "Akşam"))
        self.checkBoxDhuhrWarn.setText(_translate("MainWindow", "Öğle"))
        self.checkBoxIshaWarn.setText(_translate("MainWindow", "Yatsı"))
        self.checkBoxFajrWarn.setText(_translate("MainWindow", "İmsak"))
        self.checkBoxSunriseWarn.setText(_translate("MainWindow", "Güneş"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Uyarılar"))
        self.groupBox.setTitle(_translate("MainWindow", "Seçenekler"))
        self.checkBoxPlayWarnSound.setText(_translate("MainWindow", "Uyarı sesleri çal"))
        self.label_16.setText(_translate("MainWindow", "Kapatma ayarı"))
        self.checkBoxShowInTray.setText(_translate("MainWindow", "Sistem tepsisinde simge göster"))
        self.label_12.setText(_translate("MainWindow", "Ezan sesi"))
        self.checkBoxPlayAdhan.setText(_translate("MainWindow", "Vakitlerde ezan oku"))
        self.checkBoxMuteInAdhanTime.setText(_translate("MainWindow", "Ezan vaktinde sesi kapat"))
        self.label_26.setText(_translate("MainWindow", "Uyarı sesi"))
        self.comboBoxCloseOption.setItemText(0, _translate("MainWindow", "Tamamen kapat"))
        self.comboBoxCloseOption.setItemText(1, _translate("MainWindow", "Gizle"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.checkBoxSystemNotifications.setText(_translate("MainWindow", "Sistem bildirimleri açık"))
        self.pushButtonPreferencesReset.setText(_translate("MainWindow", "Reset"))
        self.pushButtonPreferencesSave.setText(_translate("MainWindow", "Kaydet"))
        self.pushButtonPreferencesReturnToDefaults.setText(_translate("MainWindow", "Varsayılana Dön"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Seçenekler"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_21.setText(_translate("MainWindow", "Öğle"))
        self.label_22.setText(_translate("MainWindow", "Sabah"))
        self.label_19.setText(_translate("MainWindow", "Akşam"))
        self.label_20.setText(_translate("MainWindow", "İkindi"))
        self.label_18.setText(_translate("MainWindow", "Yatsı"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Kazalar"))
        self.pushButton_2.setText(_translate("MainWindow", "mustafairan.wordpress.com"))
        self.label_41.setText(_translate("MainWindow", "Vakit Bağlantısı"))
        self.pushButton_3.setText(_translate("MainWindow", "github.com/mustafairan/pynamaz"))
        self.pushButton_4.setText(_translate("MainWindow", "diyanet.gov.tr/tr/PrayerTime/WorldPrayerTimes"))
        self.pushButton.setText(_translate("MainWindow", "www.diyanet.gov.tr"))
        self.label_42.setText(_translate("MainWindow", "Geliştirici Sayfası"))
        self.label_43.setText(_translate("MainWindow", "Uygulama Deposu"))
        self.label_44.setText(_translate("MainWindow", "Diyanet.gov.tr"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Linkler"))
        self.menuMen.setTitle(_translate("MainWindow", "Menü"))
        self.menuG_r_n_m.setTitle(_translate("MainWindow", "Görünüm"))
        self.menuNas_l_kullan_l_r.setTitle(_translate("MainWindow", "Nasıl kullanılır?"))
        self.action_k.setText(_translate("MainWindow", "Çıkış"))
        self.actionCleanlooks.setText(_translate("MainWindow", "Cleanlooks"))
        self.actionGTK.setText(_translate("MainWindow", "GTK+"))
        self.actionPlastique.setText(_translate("MainWindow", "Plastique"))
        self.actionWindows.setText(_translate("MainWindow", "Windows"))
        self.actionG_ncelle_2.setText(_translate("MainWindow", "Güncelle"))
        self.actionBespin.setText(_translate("MainWindow", "Bespin"))
        self.actionQtcurve.setText(_translate("MainWindow", "Qtcurve"))
        self.actionMotif.setText(_translate("MainWindow", "Motif"))
        self.actionCDE.setText(_translate("MainWindow", "CDE"))
        self.actionOxygen.setText(_translate("MainWindow", "Oxygen"))
        self.actionNas_l_kullan_l_r.setText(_translate("MainWindow", "Kullanımı Anlat"))
        self.actionHide.setText(_translate("MainWindow", "Gizle"))
        self.actionShow.setText(_translate("MainWindow", "Göster"))
        self.actionExit.setText(_translate("MainWindow", "Çıkış"))

